### ISSUE TITLE
Import Dangerfile timeout

### ISSUE THREAD

**Issue by FranciscoAmado** [danger/danger#1000]
Hi there!

# Report

## What did you do?

We have Danger set up in TeamCity for a while but only recently we've been having erratic behaviour when using it. More specifically when using the `import_dangerfile`

We're struggling to find the cause of it and would like to know if you guys have experienced such error.

The most probable cause we can find may be related to `rate limiting` of Github API

## What did you expect to happen?

`import_dangerfile` fetches the shared Dangerfile in a github repository.

## What happened instead?

`import_dangerfile` request timeout.

<details>
  <pre>
Danger::DSLError: 
[!] Invalid `Dangerfile` file: execution expired
 #  from Dangerfile:1
 #  -------------------------------------------
 >  danger.import_dangerfile(
 #    github: "Organization/danger-ios", 
 #  -------------------------------------------

  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:904:in `initialize'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:904:in `open'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:904:in `block in connect'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:902:in `connect'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:876:in `start'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1407:in `request'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1165:in `get'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:85:in `perform_request'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:43:in `block in call'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:38:in `call'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.15.2/lib/faraday/connection.rb:138:in `get'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/danger-5.6.2/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb:183:in `download'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/danger-5.6.2/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb:160:in `import_dangerfile_from_github'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/danger-5.6.2/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb:80:in `import_dangerfile'
  Dangerfile:1:in `block in parse'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/danger-5.6.2/lib/danger/danger_core/dangerfile.rb:200:in `eval'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/danger-5.6.2/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/danger-5.6.2/lib/danger/danger_core/dangerfile.rb:196:in `instance_eval'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/danger-5.6.2/lib/danger/danger_core/dangerfile.rb:196:in `parse'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/danger-5.6.2/lib/danger/danger_core/dangerfile.rb:274:in `run'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/danger-5.6.2/lib/danger/danger_core/executor.rb:28:in `run'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/danger-5.6.2/lib/danger/commands/runner.rb:68:in `run'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/xcodeserver/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/danger-5.6.2/bin/danger:5:in `<top (required)>'
  /Users/xcodeserver/.rbenv/versions/2.4.1/bin/danger:22:in `load'
  /Users/xcodeserver/.rbenv/versions/2.4.1/bin/danger:22:in `<top (required)>'
Process exited with code 1
</pre>
</details>

## Your Environment

* Which CI are you running on?
TeamCity
* Are you running the latest version of Danger?
Yes, 5.6.2
* What is your Dangerfile?

```ruby

danger.import_dangerfile(
  github: "Organization/danger-ios", 
  branch: "master"
)
  ```

Thanks for the help 👍🏻

**Comment by hotbott** [comment]
@FranciscoAmado are you trying a `Dangerfile` from a private or a public repo?

**Comment by FranciscoAmado** [comment]
It's from a private repo

**Comment by hotbott** [comment]
Can you try to verify your credentials / setup via the API directly?

e.g. via the command line:
```sh
curl -H "Authorization: token $DANGER_GITHUB_API_TOKEN" https://api.github.com/repos/Organization/danger-ios/contents/Dangerfile
```

**Comment by FranciscoAmado** [comment]
It works great. Prints out the JSON response with all the details related to the Dangerfile

**Comment by hotbott** [comment]
The `import_dangerfile` method calls that API internally and downloads the file given in the `download_url` property.
Not sure how to help you now 🤔 It's hard to debug without an option to reproduce it...

**Comment by FranciscoAmado** [comment]
I understand. Even we can't reproduce it either.
Thanks for the support. I'll let you know if we find anything related to this in the future.
