### ISSUE TITLE
base_commit for gitlab wrong in certain workflows

### ISSUE THREAD

**Issue by twk3** [danger/danger#1009]
# Report

## What did you do?

Run danger on a branch when its merge request has been updated with a merge from the target branch (rather than rebasing) 

## What did you expect to happen?

Similar to bitbucket or github, ideally the base_commit should have been updated to the tip of the target branch at the time of merge request being updated.

## What happened instead?

The base_commit was unchanged, and now the modified files list in danger includes changes that have gone into master.

## Your Environment

* Which CI are you running on?

GitLab CI

* Are you running the latest version of Danger?

yes

* What is your Dangerfile?

https://gitlab.com/charts/gitlab/blob/master/scripts/support/changelog/Dangerfile

**Comment by twk3** [comment]
This appears to be an issue with the data not being available in the gitlab merge request api. Instead the plugin just looks at the commit before the first commit in the MR. Which would work for a rebase workflow, but not if you are merging master into your branch.

GitLab should have this data somewhere, as it is used to update the diff. We should find if it's stored somewhere we can access from the api, or propose adding it if it is not.

cc\ @rymai

**Comment by rymai** [comment]
I'm not sure why we don't only use the MR diff: https://github.com/danger/danger/blob/master/lib/danger/request_sources/gitlab.rb#L84-L89

**Comment by orta** [comment]
Danger Ruby was built entirely with using the local filesystem to figure out all of the diff I'm afraid, which should be coordinated by the API calls for the MR. Maybe we change the gitlab support to use the API instead? It'd probably be quite a drastic refactor though.

**Comment by rymai** [comment]
Maybe we could use this API to get the `base_sha`: https://docs.gitlab.com/ee/api/merge_requests.html#get-mr-diff-versions similarly to what's done for GitHub https://github.com/danger/danger/blob/1687f6d9d89b318900a488a8ea31cac78153e0e1/lib/danger/danger_core/plugins/dangerfile_github_plugin.rb#L167?
