### ISSUE TITLE
Support else  catch on newline

### ISSUE THREAD

**Issue by pavankataria** [danger/danger#1032]
It should be possible to enforce the position of trailing block headers like else/catch statements:

Instead of this: 
``` Swift
if (myVar) {
    //...
} else {
    //...
}
```
We want to enforce the trailing block bumped a line like this::

``` Swift
if (myVar) {
    //...
}
else {
    //...
}
```
Or for try/catch
``` Swift
try {
    //..
}
catch (e) {
    //..
}
```
And all other similar structures.

We find it easier to read as the keyword is tight on the left margin and the closing brace's position enforces a new blank line, just like in the starting block.

**Comment by orta** [comment]
I think you've put this on the wrong repo. Danger doesn't do anything with styling.
