### ISSUE TITLE
Github + Gitlab CI, get_repo_source is getting gitlab (it's a mirror), but the code is on github

### ISSUE THREAD

**Issue by javaguirre** [danger/danger#1044]
# Report

## What did you do?

I want to run my tests on Gitlab CI through the Gitlab project mirror, I set the DANGER_GITHUB_API_TOKEN on Gitlab CI config. It executes the CI on Gitlab but fails asking for a DANGER_GITLAB_API_TOKEN

## What did you expect to happen?

I expected to not ask for a GITLAB token, since I don't want to open the PR/MR on Gitlab, but on Github.

## What happened instead?

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Fetching public_suffix 3.0.3
Installing public_suffix 3.0.3
Fetching addressable 2.5.2
Installing addressable 2.5.2
Using bundler 1.16.1
Fetching claide 1.0.2
Installing claide 1.0.2
Fetching colored2 3.1.2
Installing colored2 3.1.2
Fetching cork 0.3.0
Installing cork 0.3.0
Fetching nap 1.1.0
Installing nap 1.1.0
Fetching open4 1.3.4
Installing open4 1.3.4
Fetching claide-plugins 0.9.2
Installing claide-plugins 0.9.2
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Fetching faraday 0.15.4
Installing faraday 0.15.4
Fetching faraday-http-cache 1.3.1
Installing faraday-http-cache 1.3.1
Fetching git 1.5.0
Installing git 1.5.0
Fetching kramdown 1.17.0
Installing kramdown 1.17.0
Fetching no_proxy_fix 0.1.2
Installing no_proxy_fix 0.1.2
Fetching sawyer 0.8.1
Installing sawyer 0.8.1
Fetching octokit 4.13.0
Installing octokit 4.13.0
Fetching unicode-display_width 1.4.0
Installing unicode-display_width 1.4.0
Fetching terminal-table 1.8.0
Installing terminal-table 1.8.0
Fetching danger 5.8.2
Installing danger 5.8.2
Fetching danger-plugin-api 1.0.0
Installing danger-plugin-api 1.0.0
Fetching danger-pep8 0.0.5
Installing danger-pep8 0.0.5
Fetching danger-todoist 1.3.0
Installing danger-todoist 1.3.0
Bundle complete! 3 Gemfile dependencies, 23 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
$ bundle exec danger
bundler: failed to load command: danger (/usr/local/bundle/bin/danger)
RuntimeError: No API token given, please provide one using `DANGER_GITLAB_API_TOKEN`
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/request_sources/gitlab.rb:31:in `client'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/ci_source/gitlab_ci.rb:40:in `determine_merge_request_id'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/ci_source/gitlab_ci.rb:31:in `validates_as_pr?'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/danger_core/environment_manager.rb:15:in `pr?'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/danger_core/executor.rb:62:in `validate_pr!'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/danger_core/executor.rb:46:in `validate!'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/danger_core/executor.rb:21:in `run'
  /usr/local/bundle/gems/danger-5.8.2/lib/danger/commands/runner.rb:70:in `run'
  /usr/local/bundle/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /usr/local/bundle/gems/danger-5.8.2/bin/danger:5:in `<top (required)>'
  /usr/local/bundle/bin/danger:29:in `load'
  /usr/local/bundle/bin/danger:29:in `<top (required)>'
ERROR: Job failed: exit code 1
```

## Your Environment

* Which CI are you running on?

Gitlab CI.

* Are you running the latest version of Danger?

Yes.

* What is your Dangerfile?

Not relevant.

If I had a way of forcing using Github as the source of the project, the problem would go away, but it detects a gitlab uri because on gitlab you can set this mirror kind of project, any suggestions?

Thank you and kudos for the project!

**Comment by orta** [comment]
Maybe the order that a request source is chosen from needs to change? right now it's pretty indeterminate - https://github.com/danger/danger/blob/master/lib/danger/danger_core/environment_manager.rb#L28-L44 

Then it could take the GitHub one before the GitLab one

**Comment by javaguirre** [comment]
FYI I'm using this option 
![screenshot 2018-11-28 at 09 39 01](https://user-images.githubusercontent.com/488556/49139214-7cd25780-f2f1-11e8-9f79-71e1ad903a29.png)

**Comment by javaguirre** [comment]
I fixed the issue, I'll try to send a PR soon. :-)

**Comment by AdamMc331** [comment]
What was the issue? I haven't tried this yet, I'm just exploring if it's possible. We use GitLab CI but our code is on GitHub Enterprise and I'm not sure if I can actually use Danger. This makes it sound like I should be able to?

**Comment by javaguirre** [comment]
@AdamMc331 You have an idea of what was failing here https://github.com/TheNeonProject/danger/commits/feature/gitlab-ci%3Dplus-github but I didn't fix it properly because we finally decided to use another solution.

If I remember correctly the problem was the Gitlab service on danger is expecting to have a merge request from Gitlab, but in case of a PR coming from GitHub this doesn't exist so we need to check if there is one on GitHub.

**Comment by AdamMc331** [comment]
@javaguirre So all you did was fork Danger, update it so that it was checking for the PR against GitHub instead of GitLab, and everything was good to go?

**Comment by javaguirre** [comment]
There were some envvars I had to set too, but you can check in the Gitlab and GitHub service code to see which ones you need to set. I can search those for you if it doesn't work. :-)

**Comment by philipqnguyen** [comment]
I encountered the same problem, and I’ve made a PR to try and resolve this here #1238
