### ISSUE TITLE
repo_slug supports only one parent

### ISSUE THREAD

**Issue by Kyaak** [danger/danger#1049]
# Report

## What did you do?

Run Danger against a gitlab repository within multiple sub groups

## What did you expect to happen?

Find repository

## What happened instead?

`fetch_details` receives a 404 because a group is missing

e.g.
```
git@gitlab.com:first/second/project.git 
```
results to repo_slug
```
second/project
```

## Your Environment

* Which CI are you running on?
Gitlab
* Are you running the latest version of Danger?
Yes
* What is your Dangerfile?
Doesn't matter because it is an error in danger setup.

 ```ruby
Gitlab::Error::NotFound: Server responded with code 404, message: 404 Project Not Found. Request URI: https://gitlab.com/api/v4/projects/second%2project/merge_requests/1
  /home/jenkins/.gem/gems/gitlab-4.7.0/lib/gitlab/request.rb:66:in `validate'
  /home/jenkins/.gem/gems/gitlab-4.7.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
  /home/jenkins/.gem/gems/gitlab-4.7.0/lib/gitlab/client/merge_requests.rb:43:in `merge_request'
  /home/jenkins/.gem/gems/danger-5.10.1/lib/danger/request_sources/gitlab.rb:104:in `fetch_details'
  /home/jenkins/.gem/gems/danger-5.10.1/lib/danger/danger_core/environment_manager.rb:51:in `fill_environment_vars'
  /home/jenkins/.gem/gems/danger-5.10.1/lib/danger/danger_core/dangerfile.rb:266:in `run'
  /home/jenkins/.gem/gems/danger-5.10.1/lib/danger/danger_core/executor.rb:28:in `run'
  /home/jenkins/.gem/gems/danger-5.10.1/lib/danger/commands/runner.rb:70:in `run'
  /home/jenkins/.gem/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /home/jenkins/.gem/gems/danger-5.10.1/bin/danger:5:in `<top (required)>'
  /home/jenkins/.gem/bin/danger:23:in `load'
  /home/jenkins/.gem/bin/danger:23:in `<top (required)>'
  ```

**Comment by orta** [comment]
Cool, yeah, sounds like a bug 👍

**Comment by Kyaak** [comment]
I can see in `ci_source/jenkins` that this is strictly matched to two fields. For an ssh link the regex should be easy to capture everything after `:`. https://github.com/danger/danger/blob/8f9ba9472e9d1fd55add72f1898d60523b5c3b4a/lib/danger/ci_source/jenkins.rb#L86
An http/s link could habe another path so it is hard to find where the repository begins `https://company.com/gitlab/first/second/project.git`.
Could we use the `DANGER_XY_HOST` env to match here correctly?

**Comment by orta** [comment]
Yeah, that could work or could even specify a specific ENV var just for picking up the full project root?

**Comment by orta** [comment]
Less is probably better, I agree, maybe we need two regexes, one for `http://` and one for `git:`? The ?

**Comment by Kyaak** [comment]
Sounds good 👍
