### ISSUE TITLE
Duplicated constant REGEXPBB

### ISSUE THREAD

**Issue by JanStevens** [danger/danger#1052]
# Report

## What did you do?
Used the latest version of danger v5.10.3

## What did you expect to happen?
To not see any warnings

## What happened instead?
Saw following warnings

```
/.ruby/vendor/ruby/2.5.0/gems/danger-5.10.3/lib/danger/ci_source/support/find_repo_info_from_url.rb:22: warning: already initialized constant Danger::FindRepoInfoFromURL::REGEXPBB
/.ruby/vendor/ruby/2.5.0/gems/danger-5.10.3/lib/danger/ci_source/support/find_repo_info_from_url.rb:13: warning: previous definition of REGEXPBB was here
```

## Your Environment
- ruby 2.5.3
- rails 5.2.2
- danger 5.10.3

## Reference
https://github.com/danger/danger/blob/v5.10.3/lib/danger/ci_source/support/find_repo_info_from_url.rb#L13

**Comment by jmromanos** [comment]
It seems that it is my fault 😓 . I don't know how it got duplicated. I'll fix it in a moment 👍
