### ISSUE TITLE
Support danger for Appcenter CI system

### ISSUE THREAD

**Issue by RishabhTayal** [danger/danger#1056]
Are there any plans to add support for [AppCenter](http://appcenter.ms) CI system?

**Comment by RishabhTayal** [comment]
@orta If you want I can create a PR for this.

**Comment by orta** [comment]
Sure, I have no plans to add it, but happy to support it

**Comment by RishabhTayal** [comment]
Awesome! I have already started working on it. Will let you know if I have any question.

**Comment by cojoj** [comment]
I've conctacted App Center's support and they asked me to create a **feature request**. With this I guess it'd be way easier to create Danger's integration to the App Center. Would be greate to bump this request: https://github.com/Microsoft/appcenter/issues/79

**Comment by cojoj** [comment]
This issue has been resolved in #1086. I guess we can close it now.
