### ISSUE TITLE
android lint messages are not posted on PR

### ISSUE THREAD

**Issue by RishabhTayal** [danger/danger#1059]
# Report

## What did you do?

`bundle exec danger`

## What did you expect to happen?

post the lint result on PR

## What happened instead?

danger passed but the lint violations were not posted on PR

## Your Environment

* Which CI are you running on?
Bitrise
* Are you running the latest version of Danger?
Yes
* What is your Dangerfile?

  ```ruby
    # Sometimes it's a README fix, or something like that - which isn't relevant for
    # including in a project's CHANGELOG for example
    declared_trivial = github.pr_title.include? '#trivial'

    # Make it more obvious that a PR is a work in progress and shouldn't be merged yet
    warn('PR is classed as Work in Progress') if github.pr_title.include? '[WIP]'

    # Warn when there is a big PR
    warn('Big PR') if git.lines_of_code > 500

    android_lint.gradle_task = 'checkstyle'
    android_lint.report_file = 'app/build/reports/checkstyle/checkstyle.xml'
    android_lint.lint(inline_mode: true)

  ```

**Comment by orta** [comment]
This is likely either a problem with your setup of that plugin, or you've not configured danger correctly.

**Comment by bartwell** [comment]
I am faced with the same problem. I spent several days trying to find a reason, but without any success.  @RishabhTayal did you find a solution? May be you have working example?
