### ISSUE TITLE
Danger not able to get PR data from Bitbucket Server

### ISSUE THREAD

**Issue by RtgrV** [danger/danger#1077]
# Report

## What did you do?

1. Install Danger using bundler
2. Danger init
3. Call Danger from our Jenkins CI using bundler using env variables required for the Bitbucket server setup

(FYI: we use a pipeline setup)

## What did you expect to happen?

I expected it to run Danger, though I was unable to get it starting.

## What happened instead?

```
15:28:54 + bundle exec danger --verbose
15:28:55 bundler: failed to load command: danger (/Users/<username>/.rbenv/versions/2.3.7/bin/danger)
15:28:55 NoMethodError: undefined method `[]' for nil:NilClass
15:28:55   /Users/<username>/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/danger-5.13.0/lib/danger/request_sources/bitbucket_server.rb:50:in `setup_danger_branches'
15:28:55   /Users/<username>/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/danger-5.13.0/lib/danger/danger_core/environment_manager.rb:57:in `ensure_danger_branches_are_setup'
15:28:55   /Users/<username>/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/danger-5.13.0/lib/danger/danger_core/dangerfile.rb:259:in `setup_for_running'
15:28:55   /Users/<username>/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/danger-5.13.0/lib/danger/danger_core/dangerfile.rb:270:in `run'
15:28:55   /Users/<username>/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/danger-5.13.0/lib/danger/danger_core/executor.rb:28:in `run'
15:28:55   /Users/<username>/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/danger-5.13.0/lib/danger/commands/runner.rb:70:in `run'
15:28:55   /Users/<username>/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
15:28:55   /Users/<username>/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/danger-5.13.0/bin/danger:5:in `<top (required)>'
15:28:55   /Users/<username>/.rbenv/versions/2.3.7/bin/danger:22:in `load'
15:28:55   /Users/<username>/.rbenv/versions/2.3.7/bin/danger:22:in `<top (required)>'
```

It crashed on a certain line, where it expects the `json` data to be there. By mimicking the code, I was able to retrieve data though. Using Postman. Here I used the same Basic auth as the code is using.

## Your Environment

* Which CI are you running on?
Jenkins

* Are you running the latest version of Danger?
Yes, danger 5.13.0

* What is your Dangerfile?
It's the file I get when initializing, with applying fixes according to our rubocop setup.

```ruby
# Sometimes it's a README fix, or something like that - which isn't relevant for
# including in a project's CHANGELOG for example
github.pr_title.include? '#trivial'

# Make it more obvious that a PR is a work in progress and shouldn't be merged yet
warn('PR is classed as Work in Progress') if github.pr_title.include? '[WIP]'

# Warn when there is a big PR
warn('Big PR') if git.lines_of_code > 500

# Don't let testing shortcuts get into master by accident
raise('fdescribe left in tests') if `grep -r fdescribe specs/ `.length > 1
raise('fit left in tests') if `grep -r fit specs/ `.length > 1
```

I hope someone could help me track down what is going wrong or if I'm putting some wrong value anywhere.

**Comment by orta** [comment]
Looks like it can't access your repo maybe? Perhaps your env vars are set wrong?

**Comment by RtgrV** [comment]
Yea, it seems it can't parse the `json` data. So probably it returns an error. Is there any way I can see the error?

But it is weird that with a normal authorized GET call I am able to get it from our bitbucket server. And it actually is in the right format (from what I saw in code).

**Comment by orta** [comment]
I'd make a fork that logs it out (or see if it does that in verbose) and see what's up, I think someone else has had an issue like this before too - so it might be worth diving into the issues too

**Comment by RtgrV** [comment]
Good thinking, I can try with a Fork. Thanks! The verbose one didn't say anything differently.
Hmm good to know, I'll start diving then.

**Comment by RtgrV** [comment]
I didn't have the time to look into the issue and due to circumstances I won't be able to do it soon. Some priorities shifted. I'm sorry, I wish I was able to use such a nice product :-)
