### ISSUE TITLE
Add support for enterprise github

### ISSUE THREAD

**Issue by dbgrandi** [danger/danger#108]
Should be a few minor points to change.

- add support for setting a custom GH host
- make sure that host is passed into the Octokit config

**Comment by jeroenvisser101** [comment]
- it'd also need to work with `danger local`, which includes some references to github.com too

**Comment by orta** [comment]
@dbgrandi I want to pair on this sometime

**Comment by dbgrandi** [comment]
Definitely. I've got `Octokit` working with our GH instance now.

**Comment by dbgrandi** [comment]
Started here: https://github.com/danger/danger/pull/139/files

**Comment by jeroenvisser101** [comment]
@dbgrandi can this be closed now that #139 is merged? :)

**Comment by orta** [comment]
Yes

**Comment by jeroenvisser101** [comment]
We're getting closer and closer to 1.0.0 :dancer:
