### ISSUE TITLE
Fail if no PR?

### ISSUE THREAD

**Issue by ghiculescu** [danger/danger#1080]
Not sure if this is the right place to ask, but would you accept a PR that adds a command line flag for Danger to fail if there's no PR found?

Currently it will `exit(0)`: https://github.com/danger/danger/blob/master/lib/danger/danger_core/executor.rb#L61

I would like to have that cause a red build, so that we can ensure that danger has 100% run before we merge. We use [CircleCI](https://danger.systems/guides/troubleshooting.html#circle-ci-doesnt-run-my-build-consistently) for context.

**Comment by orta** [comment]
I'm pretty sure that flag already exists?

**Comment by ghiculescu** [comment]
Not sure if ^ is the right label, but I'm happy to build this if it will get accepted.

**Comment by ghiculescu** [comment]
@orta 	I'm not seeing it in https://github.com/danger/danger/blob/master/lib/danger/danger_core/executor.rb#L7

There's `fail_on_errors` but that only fails if Danger runs - which won't happen if no PR is found. (Which tbh I would consider an error, but I'm wary of repurposing that flag.)

**Comment by orta** [comment]
Oh, wait, you want it when it's not a PR - yeah, there wouldn't be something for that. 

Yeah, I don't see a reason why not. Most CIs do both PR and the merge build by default, so it seems fine as an edge case.

**Comment by orta** [comment]
Sure, give it a shot
