### ISSUE TITLE
Danger status don't right

### ISSUE THREAD

**Issue by wongkaking** [danger/danger#1083]
# Report

## What did you do?

Set up Danger and them make a PR and test it

## What did you expect to happen?

ℹ If these are some swiftlint problem show on the GitHub and has a right status

## What happened instead?

ℹ There is a danger report but the status is wrong
![image](https://user-images.githubusercontent.com/42529593/52853025-37d1fa80-3155-11e9-9d43-0963991cb9f3.png)

## Your Environment

* Which CI are you running on? `Bitrise`
* Are you running the latest version of Danger? Yes
* What is your Dangerfile?
![image](https://user-images.githubusercontent.com/42529593/52852995-225cd080-3155-11e9-87ff-8ea9b8eada49.png)

**Comment by orta** [comment]
Maybe the swiftlint plugin isn't declaring these as fails?
