### ISSUE TITLE
Bogus error from DANGER_GITLAB_HOST

### ISSUE THREAD

**Issue by glensc** [danger/danger#1088]
1. set `DANGER_GITLAB_HOST=https://gitlab.example.com`
2. danger

```
$ bundle exec danger --fail-on-errors=true
RuntimeError: Port number included in `DANGER_GITLAB_HOST`, this will fail with GitLab CI Runners
```

duh? there's no port in that url.

suggestion: use `CI_API_V4_URL` variable, not require hosted environments to setup 
 `DANGER_GITLAB_HOST` and `DANGER_GITLAB_API_BASE_URL` variables

see: https://docs.gitlab.com/ee/ci/variables/#predefined-environment-variables

**Comment by orta** [comment]
Happy to have it prefer that env var, got to be careful for backwards compatibility though 👍

**Comment by glensc** [comment]
all there: #1089
