### ISSUE TITLE
PR Body could move in to the DSL attributes table?

### ISSUE THREAD

**Issue by orta** [danger/danger#109]
Experiment: if instead of putting `pr.body` - we chucked in `pr.body.lines` we might get it working in the terminal. We could also run it through the markdown parser. 

Might work?

**Comment by KrauseFx** [comment]
But the body might be a just one very long line, right?

**Comment by orta** [comment]
Then could split based on characters counts and limit it to a number that seems to work well for Circle/Travis

**Comment by orta** [comment]
https://github.com/CocoaPods/CLAide/pull/61 shows that we can pull out the terminal size too

**Comment by orta** [comment]
We should just cap at 80 characters, after looking at how they show in travis

**Comment by jeroenvisser101** [comment]
@orta what is this for actually? I see you guys talking about the size, any particular issue on that?

**Comment by orta** [comment]
Older versions of danger included the full pr_body in the table, but it wouldn't wrap in CI, so it stretched off forever, occasionally breaking out of the table and it  felt wrong. You saw my attempt at using lines to strip it. 

I think this is still worth a quick look,  splitting at 80, then joining with newlines could probably look good ( judging on the multi-line git commit stuff we show )

**Comment by jeroenvisser101** [comment]
Ah alright, that makes sense, cool! Is it due to the library we use for displaying tables?

**Comment by orta** [comment]
Yes

On my phone, replies will be curt.

**Comment by orta** [comment]
This is fixed 👍
