### ISSUE TITLE
Issue with version 6.0 and 'danger-gitlab' gem

### ISSUE THREAD

**Issue by JanPawlov** [danger/danger#1105]
# Report

Specyfying 
```ruby
gem 'danger'
gem 'danger-gitlab'
```
in `Gemfile` and running `bundle install` results in installing 
```
Using danger 5.16.1
Using danger-gitlab 6.0.0
```

However, explicitly specifying gem versions to match the lastest:

```
gem 'danger', '~> 6.0'
gem 'danger-gitlab', '~> 6.0'
```

result in:
```
Bundler could not find compatible versions for gem "danger":
  In Gemfile:
    danger (~> 6.0)

    danger-gitlab (~> 6.0) was resolved to 6.0.0, which depends on
      danger (~> 5.0)
```

So, either I have the lastest `danger` version with downgraded `danger-gitlab` or vice versa, both resulting in gitlab inline comments to fail.

**Comment by orta** [comment]
cool, looks like danger-gitlab needs a release

**Comment by orta** [comment]
OK, this should be fixed with https://github.com/danger/danger-gitlab-gem/commit/47ed0471737490d2f87d97359de88e728da8ec0b

which allows 6.x
