### ISSUE TITLE
Provide an official Docker image

### ISSUE THREAD

**Issue by pbendersky** [danger/danger#1110]
# Report

For projects that are not Ruby based (let's say Java), it would be great to have an official Docker image that tracks the latest version of Danger so we can run it easily from CI.

In my use case, we run maven to compile a Java project, and that leaves some checkstyle output files. Without a Danger image, I need to add Ruby to the Docker image that runs the build. With a danger image, I could simple run my Dangerfile from it.

I can contribute it, but need some pointers on what repo to use, and who can set up the automation in Docker Hub (I noticed there's something set for danger/peril already).

**Comment by orta** [comment]
Cool, I've added the auto generator to this repo: https://cloud.docker.com/repository/registry-1.docker.io/dangersystems/danger-rb

It fails right now, but I'll take PRs adding it 👍

**Comment by RDIL** [comment]
If you invite me to the Docker organization, I can give it a try.  Docker ID is jumbocakeyumyum.

**Comment by orta** [comment]
I'd try building it locally to fix it, it's hooked up to deploy on any merged PRs to master (I don't have access myself either, I have it going through a bot account)

**Comment by jk** [comment]
For what it's worth, we use the docker image, GitLab uses for its GitLab itself and install some additional stuff. Our dockerfile (which is build on our internal gitlab-ci) looks like this:

```dockerfile
FROM registry.gitlab.com/gitlab-org/gitlab-build-images:danger

RUN env | sort && \
    danger --version && \
    gem update danger danger-gitlab && \
    gem install \
    danger-commit_lint \
    danger-the_coding_love \
    danger-mention \
    danger-welcome_message \
    danger-prose \
    danger-lgtm \
    danger-junit \
    danger-linear_history \
    --no-document
```

The base image itself is defined here: https://gitlab.com/gitlab-org/gitlab-build-images/blob/master/Dockerfile.danger

**Comment by okainov** [comment]
Is there any update on this one?

**Comment by orta** [comment]
Nope, you're welcome to take a look

**Comment by fkorotkov** [comment]
BTW it seems the GitLab image mentioned above is published as `registry.gitlab.com/gitlab-org/gitlab-build-images:danger`
