### ISSUE TITLE
Danger uses github.com API for enterprise repository

### ISSUE THREAD

**Issue by ignazioc** [danger/danger#1126]
# Report

## What did you do?

I configured the environment variable to use my github enterprise instance
```bash
export DANGER_GITHUB_API_TOKEN=**********6356;
export DANGER_GITHUB_HOST=github.corp.*****.com;
export DANGER_GITHUB_API_BASE_URL=https://github.corp.*****.com/api/v3/;
```
then I run

```bash
bundle exec danger local --verbose
```

## What did you expect to happen?
Expected to see the result of danger.

## What happened instead?
I get an error and from the log I can see that Danger is trying to use github.com instead of the enterprise one.
```
Running your Dangerfile against this PR - https://github.corp.****.com/*******/pull/2020

GET https://api.github.com/repos/**********/pulls/2020: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
	/Users/****/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/octokit-4.13.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
```

## Your Environment

* Which CI are you running on?
Jenkins, but so far I'm running locally.

* Are you running the latest version of Danger?
`0.9.1`

* What is your Dangerfile?
Just a simple

 ```ruby
message("This is a message from danger")
  ```

**Comment by orta** [comment]
Yeah, this sounds like a bug 👍

**Comment by RDIL** [comment]
Was just able to reproduce this. Definitely a bug.

**Comment by ignazioc** [comment]
I'm embarrassed to say that I was running the very old version `0.9.1` of Danger.
My Gemfile.lock had `faraday-http-cache` v2.0 that was not compatible with the latest version of Danger. 
Rolling back `faraday-http-cache` to the `v.1.3.1` I was able to update Danger to the latest release and this fixed the _bug_.
