### ISSUE TITLE
Can't get inline comments to work on GitLab, even though other plugins generate them successfully

### ISSUE THREAD

**Issue by unikitty37** [danger/danger#1146]
# Report

## What did you do?

Run `bundle exec danger --fail-on-errors=true --remove-previous-comments` from CI.

## What did you expect to happen?

The Brakeman warning should be posted as an inline comment attached to the relevant piece of code.

I expected this to work as`danger-rubocop` manages it when called with `inline_comment: true`:

<img width="1164" alt="Screenshot 2019-07-31 at 12 07 03" src="https://user-images.githubusercontent.com/139183/62209487-a6b4b000-b391-11e9-9ccf-06608af74796.png">

## What happened instead?

The Brakeman warning was posted in a table with all the other warnings and errors, and there was no easy way to see the relevant code.

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/139183/62209227-ed55da80-b390-11e9-9068-4de2635d4ee5.png">

## Your Environment

* Which CI are you running on?
GitLab CI, on GitLab Community Edition 12.1.2
* Are you running the latest version of Danger?
Danger 6.0.9 with danger-gitlab 7.0.0
* What is your Dangerfile?

```ruby
# frozen_string_literal: true

CHANGED_FILES = (git.added_files + git.modified_files).freeze
ADDED_FILES = git.added_files.freeze

# Check that db/structure.sql is changed if migrations changed
updated_migrations_files = CHANGED_FILES.select { |path| path =~ %r{db/migrate} }
structure_updated = CHANGED_FILES.include?('db/structure.sql')

if updated_migrations_files.any? && !structure_updated
  warn <<~MESSAGE
    Check if db/structure.sql needs to be updated.
    You have the following migrations updated or added:
    #{gitlab.html_link(updated_migrations_files)}
  MESSAGE
end

# RuboCop
rubocop_reports = rubocop.lint(inline_comment: true)
if rubocop_reports&.any?
  failure <<~MESSAGE
    There are Rubocop violations that need to be fixed.
  MESSAGE
end

# Brakeman
require 'brakeman'

brakeman = Brakeman.run(app_path: '.')
if brakeman.filtered_warnings&.any?
  brakeman.filtered_warnings.each do |warning|
    failure("**#{warning.check}**: #{warning.message}", file: warning.relative_path, line: warning.line)
  end
end
if brakeman.errors&.any?
  brakeman_message = <<~MESSAGE
    Brakeman failed!
    Errors: #{brakeman.errors.count}
    Warnings: #{brakeman.filtered_warnings.count}
  MESSAGE
  failure brakeman_message
end

if CHANGED_FILES.include?('config/brakeman.ignore')
  warn <<~MESSAGE
    Brakeman ignore config has been updated.
    Don't forget to explain this change in the merge commit message.
  MESSAGE
end
```
* Output from CI job:
```
$ bundle exec danger --fail-on-errors=true --remove-previous-comments --verbose
Results:

Errors:
- [ ] app/controllers/beer_festivals_controller.rb#L56: **Brakeman::CheckRedirect**: Possible unprotected redirect

Warnings:
- [ ] Brakeman ignore config has been updated.
Don't forget to explain this change in the merge commit message.
```

**Comment by orta** [comment]
Is it possible that plugin isn't using the inline API?

**Comment by unikitty37** [comment]
It seems to be… at least, I'm doing the same as it is:

https://github.com/ashfurrow/danger-rubocop/blob/3959cca96dca031a0740576ac22471b80f671b82/lib/danger_plugin.rb#L93

**Comment by orta** [comment]
Are you sure they're the same regex etc? 

Otherwise it could be that the warnings are outside of the diff, and the APIs for inline comments are only for inside the diff

**Comment by unikitty37** [comment]
Yes, that's it — I generated the test by removing a `brakeman.ignore` entry for that line, rather than adding something that would trigger Brakeman. Adding a comment to the end of the caused it to appear in the diff and things worked as expected. Thanks!

**Comment by unikitty37** [comment]
Incidentally, is there a way for the Dangerfile to determine if a given line is part of the diff?

I'd quite like to be able to only show warnings for things that have changed in this MR in the case of things like adding "FIXME" comments, and ignore those that were already there…
