### ISSUE TITLE
GitHub group mentions are not linkified

### ISSUE THREAD

**Issue by tmlshapr** [danger/danger#1147]
# Report

## What did you do?

We had danger already set up for our CI flow and it works fine. I wanted to add a mention message to a team, so I extended the Dangerfile with the following:

```
markdown("@myorg/team1 @tmlshapr")
```

## What did you expect to happen?

I expected GitHub to linkify both mentions.

## What happened instead?

Only the user mention is linkified, the group mention is not. On the other hand, if I put the same group mention in the PR description by hand, `@myorg/team1` gets linkified as expected.

## Your Environment

* Which CI are you running on? -- Bitrise
* Are you running the latest version of Danger? -- danger-6.0.9
* What is your Dangerfile?

```ruby
markdown("@myorg/team1 @tmlshapr")
```

**Comment by orta** [comment]
is it possible they're private and the bot doesn't have access?

**Comment by tmlshapr** [comment]
It's quite possible, although I was not familiar with the notion of private teams (from within my org, the team in question just appears as a normal team in the list, that is, not secret or anything). How do I go around it?

**Comment by orta** [comment]
I'm not sure, it's a guess - it's very unlikely to be an issue on Danger's side (it just posts dumb markdown to GitHub) so it's likely something on the system side related to that user account

**Comment by tmlshapr** [comment]
Do you think it could be related to the permissions granted by the access token?

**Comment by orta** [comment]
Yep, or the user account maybe

**Comment by tmlshapr** [comment]
not solved but closing because I worked around the notification part which doesn't rely on mentions anymore
