### ISSUE TITLE
Add DSL attribute for draft PR status

### ISSUE THREAD

**Issue by mike-weshop** [danger/danger#1150]
Is there any planned support for draft PRs, so we'd be able to show a warning if the github PR is in draft mode, for example?

**Comment by mike-weshop** [comment]
Reference: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by orta** [comment]
It will be in the `pr_json` somewhere, I don't think any extra support will be needed except documentation if you want to do that 👍

**Comment by orta** [comment]
closing as inactive.

**Comment by connorshea** [comment]
FWIW I would like this feature as well, I think it'd be worth at least documenting how this works.

Based on my testing, it can be checked with `github.pr_body['mergeable_state'] == 'draft'` for a GitHub PR.

**Comment by orta** [comment]
I don't get what 'support' looks like in this case, Danger has always already supported drafts because it's just a boolean in the JSON? Is the goal a new exposed DSL attribute?

**Comment by connorshea** [comment]
Yup, just a convenience method, something like `github.pr_draft?`

**Comment by orta** [comment]
Seems reasonable to me
