### ISSUE TITLE
[trivial] how do you say ‘danger’?

### ISSUE THREAD

**Issue by bangtoven** [danger/danger#1152]
sorry to bug you here but i couldn’t find better place to ask this. 
this is a stupid question, but
is it dang-er or dangerous danger?
i always read it in my mind dang-er, since it’s like “dang, i missed this”, but started to wonder what’s correct way to say it. 
thanks 😊

**Comment by orta** [comment]
Haha, no worries - here's me saying it a lot of times! https://www.youtube.com/watch?v=3HNmiNHCvdA
