### ISSUE TITLE
Support to include Dangerfile from remote url

### ISSUE THREAD

**Issue by glensc** [danger/danger#1155]
apparently, it's not possible to import `Dangerfile` from plain http url:

- https://danger.systems/reference.html
- https://danger.systems/guides/faq.html#i-want-to-run-danger-across-multiple-repos

even looked source code and `file:` only loads local files, not urls:
- https://github.com/danger/danger/blob/v6.1.0/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb

the actual problem i'm having that danger is unable to import `Dockerfile` from private gitlab instance. Found similar issues for github and seems these are not resolved either:
- https://github.com/danger/danger/issues/819
- https://github.com/danger/danger/issues/770

**Comment by Jeehut** [comment]
@orta Any updates or ETA on this?

**Comment by orta** [comment]
I don't actively work on Danger in Ruby, so if it doesn't come for the community it's not probably happening

**Comment by manicmaniac** [comment]
Looks https://github.com/danger/danger/pull/1271 already solved this issue.

Let me close this issue and feel free to reopen it if you have a trouble.
