### ISSUE TITLE
Can I change danger-gitlab MR comment format? (html -> json or markdown)

### ISSUE THREAD

**Issue by mcauto** [danger/danger#1158]
Hello!

I use danger-gitlab and slack.

Slack is not support HTML and markdown so slack message is just plain text both.

Markdown is better to read than html.

Can I change default format?

**Comment by orta** [comment]
I'm afraid not, you're welcome to add custom template support if you'd like (or a comment preview chunk at the top like in danger-js) but for now I'll close this and someone's welcome to start an implementation.
