### ISSUE TITLE
Self-hosted gitlab dangerfile import

### ISSUE THREAD

**Issue by AgapovOne** [danger/danger#1159]
# Report

## What did you do?

Tried to use Dangerfile with configuration: 
```ruby
danger.import_dangerfile(gitlab: "mobile/ci", branch: "develop", path: "ios/Dangerfile")
```

## What did you expect to happen?

To get running with danger imported from gitlab repo. Or at least show any error on fail.

## What happened instead?

CI ran danger without any messages
```
$ bundle exec danger



Job succeeded
```
And didn't post anything to MR.
There is a message on start inside remote Dangerfile. No message were there.

## Your Environment

* Which CI are you running on?
Gitlab CI
* Are you running the latest version of Danger?
Yes
* What is your Dangerfile?

```ruby
danger.import_dangerfile(gitlab: "mobile/ci", branch: "develop", path: "ios/Dangerfile")
```

Gitlab seems to not work with import_dangerfile

As in https://gitlab.com/gitlab-org/gitlab-foss/issues/55081 said - this was unintentional feature to use private token inside query params. 

Now they require to use an api method https://docs.gitlab.com/ee/api/repository_files.html#get-raw-file-from-repository

There are no proper messages on failed import. Had to run more than 10+ times to test this behaviour.

Finally this works on [my fork](https://github.com/AgapovOne/danger) with 2 changes:
- [added header](https://github.com/AgapovOne/danger/commit/94f4447d27408e4e798ff15e04d6abcd5b149d5d)
- [changed gitlab api url](https://github.com/AgapovOne/danger/commit/68ecb3582c09e286727abfa67fe45582dbae7a02)

This works with Dangerfile:
```ruby
danger.import_dangerfile(gitlab: 4020, branch: "develop", path: "ios%2FDangerfile")
```

I can use project_id or slug. But path has to be url encoded. Otherwise it doesn't work.

I'm interested if someone have the same issues on gitlab ci with mr's.

Latest issue with gitlab I found was on #1132 - May 21. So I suppose it worked back then.

Now I'm using danger gem from my git.

**Comment by orta** [comment]
Sounds like a bug, you're welcome to look at figuring it out 👍

**Comment by AgapovOne** [comment]
Also I'm unable to test with `danger pr` using gitlab url - it's trying to fetch github and fails with 404.

```
bundle exec danger pr https://gitlab.x.com/mobile/ios/merge_requests/42                                    15:52:30
Octokit::NotFound: GET https://api.github.com/repos/mobile/common-ios/pulls/42: 404 - Not Found // See: https://developer.github.com/v3/pulls/#get-a-single-pull-request
```

**Comment by orta** [comment]
Yeah, no one has submitted support for GitLab for `danger pr` I'm afraid

**Comment by glensc** [comment]
It should be `gitlab mr` for gitlab ;)
