### ISSUE TITLE
danger local crashing due to missing repo_slug

### ISSUE THREAD

**Issue by KrauseFx** [danger/danger#116]
Haven't had time to look into this yet, I get the following error:

```
~/Developer/fastlane/danger/bin/danger local --verbose

Danger local requires a repository hosted on github.
Not a Pull Request - skipping `danger` run
/Users/fkrause/Developer/fastlane/danger/lib/danger/commands/local.rb:25:in `run': undefined method `repo_slug' for nil:NilClass (NoMethodError)
	from /Users/fkrause/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
	from /Users/fkrause/Developer/fastlane/danger/bin/danger:5:in `<main>'
```

**Comment by KrauseFx** [comment]
```ruby
    def run
      ENV["DANGER_USE_LOCAL_GIT"] = "YES"

      dm = Dangerfile.new
      dm.env = EnvironmentManager.new(ENV)

      source = dm.env.ci_source
      unless source.repo_slug
````

where `source` is nil

**Comment by orta** [comment]
What is your repo origin?

On my phone, replies will be curt.

**Comment by KrauseFx** [comment]
Ah, that's probably it:

```
$ git remote -v
grill	https://github.com/fastlane/playground (fetch)
grill	https://github.com/fastlane/playground (push)
````

There is no `origin`, just a `grill`. I'll update `danger` to handle that more gracefully :+1:

**Comment by orta** [comment]
:+1: - we can also do better on the messaging there

**Comment by jeroenvisser101** [comment]
@orta would it be nice if, along with better messaging, you could specify a remote with say, `--remote`?

**Comment by orta** [comment]
For the local command? I think that could make sense if we don't find any remotes :+1: - i this case I think it's fine to also just use any remote, but prioritise `origin` if there's more than oen.

**Comment by jeroenvisser101** [comment]
If you wouldd clone and fork using [hub/hub](https://github.com/hub/hub), you'd have 2 remotes, origin being the original repository and your username being the fork. Not sure which one you would want to use in that case, but I guess origin would do then, right?

**Comment by orta** [comment]
in that case, we should prioritise origin, as that's the one with the pull requests anyway

**Comment by orta** [comment]
OK, we have better repo checking, this issue now only corresponds to doing a proper nil check on the repo slug, so that Danger doesn't crash

**Comment by jeroenvisser101** [comment]
@orta I can have a look at that tonight
