### ISSUE TITLE
In danger-gitlab, ability to ignore ssl errors

### ISSUE THREAD

**Issue by fishgills** [danger/danger#1160]
# Report

## What did you do?

I'm trying to set up Danger in a weird situation where our Gitlab installation has an invalid SSL certificate. But, since I'm not the owner of it, can not fix the certificate.

## What did you expect to happen?

It'd be nice to have an option to ignore SSL Errors... so I can use Danger. :)

## What happened instead?

```/usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
	from /usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
	from /usr/local/lib/ruby/2.6.0/net/http.rb:996:in `connect'
	from /usr/local/lib/ruby/2.6.0/net/http.rb:930:in `do_start'```

## Your Environment

* Running Gitlab Enterprise
* Latest and greatest Danger
* My Dangerfile is just one line that outputs a message.

**Comment by orta** [comment]
Sure, as long as it's not a default.

**Comment by fishgills** [comment]
Yeah, most definitely should not be a default.

**Comment by fishgills** [comment]
Is this something that can be added easily? Wondering if I should wait. I'd help but I'm not a Ruby guy. ;)

**Comment by georgewilli-am** [comment]
Did some experimenting with @fishgills, you are able to disable Gitlab's SSL verification by passing in the environment variable `GITLAB_API_HTTPARTY_OPTIONS="{verify: false}"` as documented in the README.md of the [Gitlab gem](https://github.com/NARKOZ/gitlab). I think we can close this one for Gitlab in particular, might be useful for other VSC systems though.

**Comment by fishgills** [comment]
Thanks @georgewilli-am . You sound like a good employee.
