### ISSUE TITLE
Bitbucket cloud post comment not working

### ISSUE THREAD

**Issue by kokhong20** [danger/danger#1163]
# Report
Danger doesn't post a comment in bitbucket cloud in version `6.0.9` (latest in ruby gems).
This is due to the changes in bitbucket comment API which has been fixed in `6.1.0`.  However rubygems doesn't publish the latest release version (`6.1.0`). Currently I can workaround by putting `gem 'danger', '6.1.0', :git => 'https://github.com/danger/danger.git'` in my Gemfile

## What did you expect to happen?
Danger is able to publish a comment
## What happened instead?
Danger is unable to publish a comment

ℹ Please replace this with of what happened instead.
e.g. 💥

## Your Environment

* Which CI are you running on?
Bitrise
* Are you running the latest version of Danger?
Yes. Version 6.0.9 (latest in rubygems)
* What is your Dangerfile?
  ```ruby
  # please paste here, with 2-space identation, thank you!
  # Warn about develop and master branch
  warn("Please target PRs to `develop` or `master` branch") if bitbucket_cloud.branch_for_base != "develop" && bitbucket_cloud.branch_for_base != "master"

  # Sometimes it's a README fix, or something like that - which isn't relevant for
  # including in a project's CHANGELOG for example
  declared_trivial = bitbucket_cloud.pr_title.include? "#trivial"

  # Make it more obvious that a PR is a work in progress and shouldn't be merged yet
  warn("PR is classed as Work in Progress") if bitbucket_cloud.pr_title.include? "[WIP]"

  # Warn no CHANGELOG
  warn("No CHANGELOG changes made") if git.lines_of_code > 50 && !git.modified_files.include?("CHANGELOG.md") && !declared_trivial

  # Warn pod spec changes
  warn("NLauncher.podspec changed") if git.modified_files.include?("NLauncher.podspec")

  # Warn summary on pull request
  if bitbucket_cloud.pr_body.length < 5
    warn "Please provide a summary in the Pull Request description"
  end
  ```

**Comment by orta** [comment]
Thanks for the reminder - 6.1.0 is now shipped 👍
