### ISSUE TITLE
Run danger without remote repository

### ISSUE THREAD

**Issue by olbrichj** [danger/danger#1179]
Is there a way to run danger without a remote repository configured? 
Currently I'm unable to integrate danger into the CI but would like to improve my personal PR workflow.

In `danger init` you can not skip setting up the repository. If I don't configure it and just create a `Dangerfile`, running `danger local` complains: ` danger cannot find your git remote` (of course, since non is setup)

Danger-Swift works without the repository, but doesn't support quite a lot of plugins ^^

**Comment by orta** [comment]
I don't think so, at least I only built that feature for Danger JS, you're welcome to port it over

**Comment by olbrichj** [comment]
can you give me any hints neither my ruby nor my js is even close to usable :D I'll try then to have a look

**Comment by orta** [comment]
I'm afraid I don't have the architecture for danger ruby in my head anymore, but it already uses git's details locally - so you'll probably have to find a way to make that use either staging data or the diff to master. Then you'd need some kind of flag to indicate that it will only echo out to STDOUT and that it doesn't need to get PR-like metadata, so that the DSL doesn't try to grab the extra info. Then you'd need a CLI command to trigger all that.

**Comment by olbrichj** [comment]
thanks :) I'll dig around and see if I can find a way

**Comment by olbrichj** [comment]
Soo I dug around and think this should be quite easy to implement. If I'm right we would have to change the env var in `Local` from `DANGER_USE_LOCAL_GIT` to `DANGER_USE_LOCAL_ONLY_GIT`. A corresponding `CI` exists and it should work fine with the `RequestSource`.
Furthermore we'll need to set the `repo_slug` in `LocalOnlyGitRepo`. 

 It seems like this is all which needs to be done (Please correct me if I'm wrong).

Now three problems :D
1. The `local` command is deprecated in favor of `pr`. So would it be okay to reuse `local`? or should we create a new command? like `localonly`..
2. What is the repo_slug? Or rather which value should it have?
3. I really suck at getting this to run at all. So the tests are executing, but how would I go about manually testing my changes to danger? Basically if I want to execute it, what would I need to call? `ruby lib/danger.rb local`?

**Comment by olbrichj** [comment]
So I got this running and the above changes work as expected. Still have to create specs accordingly, but at least the concept is proven.

@orta , regarding question 1 and 2 I'm still unsure. What is your preference? I would refurbish `local` but this would be a breaking change.

**Comment by orta** [comment]
yeah, there's 4 years of inertia on `danger local` . 

I wonder if `danger staging` could work?

**Comment by olbrichj** [comment]
Actually `danger staging` sounds about right, as you would normally only run this either, if you as a developer want to improve your pr flow, or you are testing your Dangerfile before deploying to your CI.
