### ISSUE TITLE
Comment based fail suppression?

### ISSUE THREAD

**Issue by orta** [danger/danger#118]
Looking a real example: https://github.com/artsy/eigen/pull/1236

In this case I _definitely_ know that this will fail the build, but I want this to be correct. What about if inside the message for the PR I wrote:

> Danger: Ignore "Developer Specific file shouldn't be changed"

Wherein it won't fail the build if a fail is found with the same string. 

Ideas / Opinions?

**Comment by KrauseFx** [comment]
What do you classify as `Developer Specific file`?

**Comment by orta** [comment]
I should have provided more context, in that PR, you see danger fail with this fail:

<img width="780" alt="screen shot 2016-03-05 at 20 21 18" src="https://cloud.githubusercontent.com/assets/49038/13551666/e22169e0-e30f-11e5-83c8-a8a1d04e97a2.png">

I was thinking that it could be possible to tell danger in the body that a specific fail should be ignored.

**Comment by orta** [comment]
When #126 is in - we'll need to think about documenting this, and maybe more
