### ISSUE TITLE
Message aggregation

### ISSUE THREAD

**Issue by telyn** [danger/danger#1183]
This is a problem I've noticed with the bitbucket-cloud request source, at least. I believe it might already be implemented in the Github request source, but it's actually a general feature that should be refactored out.

The problem is: Multiple messages for the same line of a file go in multiple comments, rather than in one comment that's a simple list.

![Screenshot from 2020-02-07 11-05-05](https://user-images.githubusercontent.com/175827/74024405-b690fa80-4999-11ea-9a2a-9825f9be5ab2.png)

I propose we add a `type` field to `Violation` (with `:error`, `:warning`, or `:message`), and a `type` method to `Markdown`, which always returns `:markdown`.

Then add a `MessageAggregator` which would take the warnings, errors, messages and markdowns lists, and produce just one list of `MessageGroup`s:

**MessageGroup**
| Field | Description |
| ----- | ----- |
| file | Possibly-nil filename |
| line | Possibly-nil line number |
| messages | array of `Markdown` & `Violations` |

The list of messages should be sorted, errors at the top, followed by warnings, then messages, then markdowns.
Ultimately perhaps `line` should be a range, and `MessageGroup` should have a `merge` method - to combine the messages arrays & `line` ranges as long as the `file` is equal, but I'm keen to not over-design this at this point. That'd allow a potentially-customisable minimum-distance-between-

`Danger::Dangerfile#post_results` would have two code paths: one to use `MessageAggregator` and a new method on `request_source` (say, `update_pr_message_groups!`), and one to use the old violation_report and `update_pull_request!`, all based on whether the request support has a method `message_groups?` that returns positive.

Longer-term, I see `MessageGroup` and `Violation` taking over a lot of the logic in the `GitHub` class relating to figuring out whether violations can be ticked-off, and request sources having a new method for fetching the comments as `MessageGroup`s. All the markdowns can be chucked away, as there's no way to give them a white tick anyway.

If that doesn't sound like a total load of arse then I'll write some code sometime Feb/March :)

**Comment by orta** [comment]
This sounds good - yep!

**Comment by Kaspik** [comment]
@telyn Hey! Are you still planning to add it for Github too? We have currently 7 Danger files on PR, and having 7 PR comments by the same "bot" user is really annoying especially with combination of posting PR comments to Slack channel.

Thanks!

**Comment by telyn** [comment]
Ah - I think you're thinking of a different feature - I hadn't considered aggregation with multiple danger instances - #1183 and the PRs that implement it only aggregate within the one dangerId.

Where I work we run a bunch of danger checks in sequence with one Dangerfile rather than in parallel with multiple Dangerfiles

Regardless of this not quite implementing what you're after (though I could probably extend it to) - I've no immediate plans to implement anything further on Danger - I've a PR open for mutant that I need to finish off before I can consider working on danger again I'm afraid! Like many others in OSS I only tend to work on things as I need them or as I have free time and fancy it.

I'd be happy to help out if you end up digging in and have any questions around the message aggregation stuff or Danger in general - I pretty much have the flow of info/control figured out now for most of the codebase. I'm available on the Danger slack, or just @ me in an issue / PR 😸
