### ISSUE TITLE
Inline comments are always stuck out

### ISSUE THREAD

**Issue by jschmid** [danger/danger#1189]
# Report

## What did you do?

I am running Danger on Bitrise (using the [built-in step](https://www.bitrise.io/integrations/steps/danger)).

The command that is ran is:

    bundle "exec" "danger" "--fail-on-errors=true"

I configured the Dangerfile to have inline comments. It looks like the inline comments are always struck out. If I disable inline comments, the main comment sent to the PR has regular formatting.

At first, I thought that this was a bug in the `android_lint` plugin, but then I configured our iOS project with `swiftlint` and the behavior is the same.

## What did you expect to happen?

The inline comments show without a strike.

Here is an example without inline comments. The text is normal.

<img width="652" alt="Screenshot 2020-02-19 at 07 39 32" src="https://user-images.githubusercontent.com/574168/74809485-8c223400-52ed-11ea-8e42-3b24eed60dc8.png">

## What happened instead?

<img width="819" alt="Screenshot 2020-02-19 at 07 37 13" src="https://user-images.githubusercontent.com/574168/74809445-79a7fa80-52ed-11ea-91d0-3e0574a41171.png">

As you can see, the text is struck out, which is not expected. It looks like the error was corrected, which is not the case.

## Your Environment

* Which CI are you running on?
  * Bitrise
* Are you running the latest version of Danger?
  * Yes, 6.2.2
* What is your Dangerfile?

On iOS:

  ```ruby
  swiftlint.config_file = 'app/.swiftlint.yml'
  swiftlint.verbose = true
  swiftlint.max_num_violations = 20
  swiftlint.lint_files inline_mode: true
  ```
On Android:

  ```ruby
  checkstyle_dir = "**/build/reports/detekt/detekt.xml"
  Dir[checkstyle_dir].each do |file_name|
    checkstyle_format.base_path = Dir.pwd
    checkstyle_format.report file_name
  end

  lint_dir = "**/build/reports/lint-**.xml"
  Dir[lint_dir].each do |file_name|
    android_lint.skip_gradle_task = true
    android_lint.filtering = true
    android_lint.report_file = file_name
    android_lint.lint(inline_mode: true)
  end

  junit_tests_dir = "**/test-results/**/*.xml"
  Dir[junit_tests_dir].each do |file_name|
    junit.parse file_name
    junit.report
  end
  ```

**Comment by orta** [comment]
Could you be running danger twice somehow?

**Comment by jschmid** [comment]
That is a question I asked myself. But I think it's run only once. It's hard to say with Bitrise because they don't really show you the whole commands that are run.

I was wondering if it was running once to find errors, then running once more to see no errors and strike them. But if that was the case, the "main comment" would be edited and removed. The main comment keeps those errors. So I would say this is not why there is the strike.

**Comment by jschmid** [comment]
I see that there are warnings in the Bitrise log:

```
Running danger
$ bundle "exec" "danger" "--fail-on-errors=true"
/usr/local/lib/ruby/gems/2.7.0/gems/git-1.6.0/lib/git/lib.rb:1054: warning: Using the last argument as keyword parameters is deprecated
/usr/local/lib/ruby/gems/2.7.0/gems/git-1.6.0/lib/git/lib.rb:1054: warning: Using the last argument as keyword parameters is deprecated
... Hundreds of lines ...
/usr/local/lib/ruby/gems/2.7.0/gems/git-1.6.0/lib/git/lib.rb:1054: warning: Using the last argument as keyword parameters is deprecated
/usr/local/lib/ruby/gems/2.7.0/gems/git-1.6.0/lib/git/lib.rb:1054: warning: Using the last argument as keyword parameters is deprecated
/usr/local/lib/ruby/gems/2.7.0/gems/git-1.6.0/lib/git/lib.rb:1054: warning: Using the last argument as keyword parameters is deprecated
/usr/local/lib/ruby/gems/2.7.0/gems/danger-6.2.2/lib/danger/request_sources/github/github.rb:170: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/lib/ruby/gems/2.7.0/gems/danger-6.2.2/lib/danger/request_sources/github/github.rb:255: warning: The called method `submit_inline_comments!' is defined here
/usr/local/lib/ruby/gems/2.7.0/gems/danger-6.2.2/lib/danger/request_sources/github/github.rb:188: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/lib/ruby/gems/2.7.0/gems/danger-6.2.2/lib/danger/helpers/comments_helper.rb:94: warning: The called method `generate_comment' is defined here
```

**Comment by ondererguven** [comment]
Hey there, I've been having the same issue since upgrading to 6.2.2. I don't get any warnings on Bitrise though. Have you found something why this might be happening?

**Comment by jschmid** [comment]
I only started using Danger. So I started with 6.2.2.

**Comment by jschmid** [comment]
I can now confirm that downgrading to 6.2.0 fixes my problem.

**Comment by ondererguven** [comment]
Downgrading indeed fixed the problem for me too. Thanks for updating us!

**Comment by austinwright** [comment]
I'm having this same issue as described above. See https://github.com/ashfurrow/danger-ruby-swiftlint/issues/145 for more information.

**Comment by Mkohm** [comment]
Also having the same issue. Running danger on travis:
You can see the log here:
https://travis-ci.com/github/Mkohm/detekt-hint-sample/builds/153193853

All comments are striked through.

**Comment by inickt** [comment]
Can also confirm downgrading to 6.2.0 fixed the issue for me.

**Comment by orta** [comment]
I wonder if this is from https://github.com/danger/danger/pull/1186 - can someone test  https://github.com/danger/danger/pull/1207 to see if it fixes it?

**Comment by inickt** [comment]
I just updated my version of Danger to target master at 69809e8 and I am still seeing the issue

**Comment by orta** [comment]
Ah, sorry, I mean https://github.com/danger/danger/pull/1201

**Comment by jschmid** [comment]
Sorry @orta, still the same error.

<img width="815" alt="Screenshot 2020-03-25 at 13 45 15" src="https://user-images.githubusercontent.com/574168/77537827-0753a880-6e9f-11ea-8ca2-9179ef7213b1.png">

**Comment by telyn** [comment]
I think I know what it is - the change from `resolved: false` to `resolved: []` in `generate_inline_comment_body` in `lib/danger/helpers/comments_helper.rb`.

I'll put in a fix to the github_inline template. My fault; Sorry everyone!

**Comment by jschmid** [comment]
I can confirm that this is fixed. Thanks!

**Comment by uziasferreirazup** [comment]
in version 7.0.1 this bug return

**Comment by Kaspik** [comment]
@uziasferreirazup Try version 8.0.0 :)
