### ISSUE TITLE
Add highlighting on GitHub

### ISSUE THREAD

**Issue by jeroenvisser101** [danger/danger#120]
Opened a PR here: https://github.com/github/linguist/pull/2871

**Comment by orta** [comment]
Thanks! I hadn't thought about this!

**Comment by jeroenvisser101** [comment]
I thought it'd be nice, let's wait and see if they accept it :)

**Comment by KrauseFx** [comment]
Thanks for adding this @jeroenvisser101. GitHub actually looks at how many repos have this project set up before merging: https://github.com/github/linguist/pull/2393#issuecomment-101409465
So let's see what GitHub says :+1:

**Comment by jeroenvisser101** [comment]
@KrauseFx hmm, let's keep our fingers crossed and hope for the best!

**Comment by orta** [comment]
Ah yeah, this might be a bit too early then we've only really been calling it production ready for a 2-3 weeks, lets see :+1:

**Comment by jeroenvisser101** [comment]
Yep, we'll have to wait for usage to go up and reach into 'the hundreds'. Should we keep this issue open so it's a reminder once usage has gone up?

**Comment by orta** [comment]
[We're up to 175](https://github.com/search?utf8=✓&q=filename%3ADangerfile&type=Code&ref=searchresults) -  Maybe once it hits around 250, 300 we can re-apply

**Comment by JuanitoFatas** [comment]
Atom already recognized Dangerfile

https://github.com/atom/language-ruby/blob/49229b7b6e81fa29c64b653408a2c910ceee9b84/grammars/ruby.cson#L14

**Comment by JuanitoFatas** [comment]
Highlighting has been added https://github.com/github/linguist/pull/3333.
