### ISSUE TITLE
`danger pr` crashes with "undefined method `sha' for nil:NilClass (NoMethodError)"

### ISSUE THREAD

**Issue by AliSoftware** [danger/danger#1202]
# Report

## What did you do?

I ran this command, to try and debug locally a Dangerfile behavior on a given PR

```
$ DANGER_GITHUB_API_TOKEN=<mytoken> bundle exec danger pr "https://github.com/MyCompany/my-private-repo/pull/10879" --dangerfile=danger-ci/Dangerfile
```

## What did you expect to happen?

Danger to locally run the rules in the Dangerfile using the metadata of the mentioned PR

## What happened instead?

Crash with following backtrace:

```
Traceback (most recent call last):
  15: from /Users/me/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `<main>'
  14: from /Users/me/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `eval'
  13: from /Users/me/.rvm/gems/ruby-2.6.4/bin/danger:23:in `<main>'
  12: from /Users/me/.rvm/gems/ruby-2.6.4/bin/danger:23:in `load'
  11: from /Users/me/.rvm/gems/ruby-2.6.4/gems/danger-6.3.1/bin/danger:5:in `<top (required)>'
  10: from /Users/me/.rvm/gems/ruby-2.6.4/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
   9: from /Users/me/.rvm/gems/ruby-2.6.4/gems/danger-6.3.1/lib/danger/commands/pr.rb:60:in `run'
   8: from /Users/me/.rvm/gems/ruby-2.6.4/gems/danger-6.3.1/lib/danger/commands/pr.rb:60:in `new'
   7: from /Users/me/.rvm/gems/ruby-2.6.4/gems/danger-6.3.1/lib/danger/danger_core/environment_manager.rb:30:in `initialize'
   6: from /Users/me/.rvm/gems/ruby-2.6.4/gems/danger-6.3.1/lib/danger/danger_core/environment_manager.rb:30:in `new'
   5: from /Users/me/.rvm/gems/ruby-2.6.4/gems/danger-6.3.1/lib/danger/ci_source/local_git_repo.rb:45:in `initialize'
   4: from /Users/me/.rvm/gems/ruby-2.6.4/gems/danger-6.3.1/lib/danger/ci_source/local_git_repo.rb:95:in `found_pull_request'
   3: from /Users/me/.rvm/gems/ruby-2.6.4/gems/danger-6.3.1/lib/danger/ci_source/support/pull_request_finder.rb:17:in `call'
   2: from /Users/me/.rvm/gems/ruby-2.6.4/gems/danger-6.3.1/lib/danger/ci_source/support/pull_request_finder.rb:31:in `check_if_any_pull_request!'
   1: from /Users/me/.rvm/gems/ruby-2.6.4/gems/danger-6.3.1/lib/danger/ci_source/support/pull_request_finder.rb:52:in `pull_request'
/Users/me/.rvm/gems/ruby-2.6.4/gems/danger-6.3.1/lib/danger/ci_source/support/pull_request_finder.rb:83:in `generate_remote_pull_request': undefined method `sha' for nil:NilClass (NoMethodError)
```

The PR url is a copy/paste from the window open in my browser so it should be correct, the Pull request still exists and is still open, and both the base and head branches are still existing on the remote.

`base` branch name is of the form `devname/sdk/feature1` and `head` branch name is on the form `devname/sdk/feature1-part2`

## Your Environment

* Which CI are you running on?

  This was when attempting to run Danger locally, on a PR from our private GitHub repo. Using RVM with Ruby 2.6.4 locally.

* Are you running the latest version of Danger?

  Yes, just updated to 6.3.1

* What is your Dangerfile?

Too long to paste here (it is even split in multiple files that we include using `require_relative`), and I don't think it's relevant to the problem because the crash happens before the `Dangerfile` is even interpreted, at the step where Danger tries to find the Pull Request reference to run its rules on.

**Comment by AliSoftware** [comment]
Strange thing though: if I try to run what I believe is the set of ruby commands run by Danger internally, I get non-nil results though

```
$ pry                                                                                                                                                                                                                   ‹ruby-2.6.4›
[1] pry(main)> require 'octokit'
=> true
[2] pry(main)> c = Octokit::Client.new(access_token: 'redacted', api_endpoint: 'https://api.github.com/')
=> #<Octokit::Client:0x00007ffd908d1ef0 ...>
[3] pry(main)> p = c.pull_request('Babylonpartners/babylon-ios',10879)
=> {:url=>"https://api.github.com/repos/babylonhealth/babylon-ios/pulls/10879",
 :id=>385688262,
…
}
[4] pry(main)> p.base.sha
=> "d1abe3839373a655ac0bb15f818d2dd274251121"
[5] pry(main)> p.head.sha
=> "3aa6b3c26e5a6ceec5b26d8a09fc3ab605c59d13"
```

When I instead add some `puts` in the source of `Danger` to debug the `def remote_pull_request` method in `pull_request_finder.rb:91`, the result of `client.pull_request(repo_slug, specific_pull_request_id)` is printed as `#<Sawyer::Resource:0x00007faded1a9f08>` and not as the huge Hash I see in `pry`. And then its `.head` and `.base` properties are indeed `nil`.

**Comment by AliSoftware** [comment]
Ah! Found the issue: The repo has been moved to a new org a while ago (like, maybe 8 month ago).

For some reason I was still using the old repo_slug in my invocation to `danger pr`.

* In `pry` that didn't seem to be a problem and Octokit was able to follow the redirect and return the proper metadata.
* In `Danger` code itself though, adding a `puts r.to_h` to dump the result of `r = client.pull_request(repo_slug, specific_pull_request_id)` led to the following output:
```
{:message=>"Moved Permanently", :url=>"https://api.github.com/repositories/18095916/pulls/10879", :documentation_url=>"https://developer.github.com/v3/#http-redirects"}
```

Not sure why in `pry` it follows redirects but in `Danger` it doesn't. I think it would be nice to still fix this and enable the case of repo redirects when using Octokit from within Danger

**Comment by orta** [comment]
Interesting, maybe there's some flag for this in OctoKit?

**Comment by telyn** [comment]
I think the version of octokit we've got set in the Gemfile.lock (4.16) should be following redirects by default. It relates to the 'accept' parameter on the `client.pull_request` call which defaults to `default_media_type`.

Ah - *as long* as we use the `Octokit::Middleware::FollowRedirects` middleware. I suspect we have a custom middleware stack sneaking in somewhere. Should be a relatively easy one :)
