### ISSUE TITLE
fetch_details: undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by fadhlimaulidri** [danger/danger#1204]
# Report

## What did you do?
`bundle exec danger local`

## What did you expect to happen?
I expected the Dangerfile to be run to PR of local branch

## What happened instead?
```
$ bundle exec danger local
Running your Dangerfile against this PR - https://github.com/<organization>/<repo_name>/pull/7335
Turning on --verbose

Traceback (most recent call last):
        11: from /Users/fadhlimaulidri/.rvm/gems/ruby-2.5.5@repo/bin/ruby_executable_hooks:24:in `<main>'
        10: from /Users/fadhlimaulidri/.rvm/gems/ruby-2.5.5@repo/bin/ruby_executable_hooks:24:in `eval'
         9: from /Users/fadhlimaulidri/.rvm/gems/ruby-2.5.5@repo/bin/danger:23:in `<main>'
         8: from /Users/fadhlimaulidri/.rvm/gems/ruby-2.5.5@repo/bin/danger:23:in `load'
         7: from /Users/fadhlimaulidri/.rvm/gems/ruby-2.5.5@repo/gems/danger-6.3.1/bin/danger:5:in `<top (required)>'
         6: from /Users/fadhlimaulidri/.rvm/gems/ruby-2.5.5@repo/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
         5: from /Users/fadhlimaulidri/.rvm/gems/ruby-2.5.5@repo/gems/danger-6.3.1/lib/danger/commands/local.rb:55:in `run'
         4: from /Users/fadhlimaulidri/.rvm/gems/ruby-2.5.5@repo/gems/danger-6.3.1/lib/danger/commands/local_helpers/local_setup.rb:43:in `setup'
         3: from /Users/fadhlimaulidri/.rvm/gems/ruby-2.5.5@repo/gems/danger-6.3.1/lib/danger/commands/local.rb:56:in `block in run'
         2: from /Users/fadhlimaulidri/.rvm/gems/ruby-2.5.5@repo/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:266:in `run'
         1: from /Users/fadhlimaulidri/.rvm/gems/ruby-2.5.5@repo/gems/danger-6.3.1/lib/danger/danger_core/environment_manager.rb:52:in `fill_environment_vars'
/Users/fadhlimaulidri/.rvm/gems/ruby-2.5.5@repo/gems/danger-6.3.1/lib/danger/request_sources/github/github.rb:118:in `fetch_details': undefined method `[]' for nil:NilClass (NoMethodError)
```

## Your Environment

* Which CI are you running on?
`local`
* Are you running the latest version of Danger?
`yes` - 6.3.1
* What is your Dangerfile?
`message("Hello, this worked")`

**Comment by orta** [comment]
Are you in a git repo?

**Comment by fadhlimaulidri** [comment]
> Are you in a git repo?

@orta : yes, of course

**Comment by orta** [comment]
Looks like somehow you're not getting any pull request data then, maybe it is a private repo and you aren't auth'd?

https://github.com/danger/danger/blob/master/lib/danger/request_sources/github/github.rb#L116-L120

**Comment by fadhlimaulidri** [comment]
true, it's a private repository.
when i try `bundle exec danger local`, how Danger get the PR?

i have branch `A` where i run `bundle exec danger local`, this branch have open PR as https://github.com/orgz/repo/pull/7344. but at log i get https://github.com/orgz/repo/pull/7335 as descrition above

**Comment by telyn** [comment]
When you use `bundle exec danger local` Danger looks through the `git log` looking for a commit with a message like 'Merged pull request <something> from', parses out a number looking like '#1234' and uses that as the pull request's id.

**Comment by fadhlimaulidri** [comment]
i see. thank you @telyn
