### ISSUE TITLE
Pset4 Recover issue with Hexadecimal comparision 

### ISSUE THREAD

**Issue by KISHOR-DOBARIYA** [danger/danger#1233]
# Report

## I have just completed my Pset4 set including recovery. in recovery had to use values e.g. int value of 0Xff  as -1 and 0Xd0 as -40, the program runs correctly all check50 green, already submitted but want to know a better way to directly compare Hex value from the buffer block   

ℹ Please replace this with what you did.
e.g. Run `danger local`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.
e.g. Running your Dangerfile without it crashing.

## What happened instead?

ℹ Please replace this with of what happened instead.
e.g. 💥

## Your Environment

* Which CI are you running on?
* Are you running the latest version of Danger?
* What is your Dangerfile?

  ```ruby
  # please paste here, with 2-space identation, thank you!

  ```

**Comment by KISHOR-DOBARIYA** [comment]
I tried to read through google sources on C on this matter but could find a satisfactory answer to my quest for better ways doing program instead of what i could do on my own

**Comment by orta** [comment]
Think you're looking for a different repo

**Comment by KISHOR-DOBARIYA** [comment]
Hi Orta
i did not get response/suggestions. why you closed it
