### ISSUE TITLE
Recommendation for testing Dangerfile

### ISSUE THREAD

**Issue by vibin** [danger/danger#1240]
Ruby beginner here, I'm sorry if this question is too basic: do you have any recommendation on how to go about testing the logic in Dangerfiles? The logic I'm referring here is non-trivial git shell commands, hitting external APIs, and file read/write.

Should I mock these pieces out individually and write unit tests with rspec? (like https://thoughtbot.com/blog/how-to-stub-external-services-in-tests)
Or is there simpler way to run end-to-end tests with test fixtures?

**Comment by orta** [comment]
I'd recommend moving them to their own Ruby files and making them functions which you can call from the Dangerfile. Then only the `Dangerfile` has the magic globals, and you can write tests using any normal ruby testing tool like rspec.

**Comment by vibin** [comment]
I'll give this approach a try, thank you!
