### ISSUE TITLE
Not enough space for warning emoji on Gitlab

### ISSUE THREAD

**Issue by Ram-Z** [danger/danger#1243]
# Report

## What did you do?

* run `danger`
* get summary comment

## What did you expect to happen?

It looks nice.

![2020-07-09-122312_276x111_scrot](https://user-images.githubusercontent.com/1587259/87033934-fb39ef80-c1de-11ea-94b1-7e490302ae43.png)

This is manually redoing the table in markdown, see #1242.

## What happened instead?

The warning emoji is squished.

![2020-07-09-122302_810x106_scrot](https://user-images.githubusercontent.com/1587259/87034017-17d62780-c1df-11ea-8554-72d1c233b22c.png)

## Your Environment

* Which CI are you running on? Gitlab
* Are you running the latest version of Danger? Yes
* What is your Dangerfile?

  ```ruby
  warn "Please add labels to this MR" if gitlab.mr_labels.empty?
  ```

**Comment by Ram-Z** [comment]
Maybe this is a browser issue. This is using qutebrowser. Cannot reproduce with Firefox or Chromium.

**Comment by orta** [comment]
Try editing the HTML to see if there's a table heading size which makes it fit, and maybe we can just bump it to that if it's not a breaking change everywere

**Comment by Ram-Z** [comment]
I can actually reproduce in Chromium now and also Falkon (another qtwebengine based browser), not on Firefox.

I could tweak the heading size, but since it's given in %', there will always be a size at which it'll start being squished together.

The cell is rendered with this snippet.

```html
<td><gl-emoji ...><img class="emoji" ... src="https://assets.gitlab-static.net/-/emojis/1/warning.png" width="20" height="20" align="absmiddle"></gl-emoji></td>
```
And it seems that the `<gl-emoji>` does not properly inherit the width/height from the `<img>`. Setting the `width: 20px` on `gl-emoji` works, or setting `min-width: 20px` on the `img`.

`gl-emoji` is an element that [Gitlab has created](https://gitlab.com/gitlab-org/gitlab/-/blob/master/app/assets/javascripts/behaviors/gl_emoji.js)

I don't think there's anything that Danger can or should do about this. I'll open a report on Gitlab.
