### ISSUE TITLE
docker image dangersystems/danger-rb needs a rebuid

### ISSUE THREAD

**Issue by aol-nnov** [danger/danger#1246]
Gitlab integration was broken due to https://github.com/NARKOZ/gitlab/issues/574 (now fixed)

could you please update the official docker image to make it play nicely with gitlab again?

Thank you in advance!

**Comment by aol-nnov** [comment]
whoopsie.. duplicate of https://github.com/danger/danger/issues/1241 (docker image still needs to be updated, though...)

**Comment by WonderCsabo** [comment]
Docker image was updated, it now works correctly, thanks!

**Comment by orta** [comment]
👍  thanks for the update
