### ISSUE TITLE
[Ruby 2.7] Warnings for gitlab.rb

### ISSUE THREAD

**Issue by Baltazardoung** [danger/danger#1250]
# Report

## What did you do?

Run danger on CI (GitLab) with Ruby 2.7.1

## What did you expect to happen?

Everything should work correctly.

## What happened instead?

Everything works except is throwing warnings. 

**Identical to #1220 but for `gitlab.rb`**

## Your Environment

* Which CI are you running on? GitLab
* Are you running the latest version of Danger? Yes

```ruby
/usr/local/bundle/gems/danger-8.0.4/lib/danger/request_sources/gitlab.rb:226: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/danger-8.0.4/lib/danger/helpers/comments_helper.rb:94: warning: The called method `generate_comment' is defined here
```

**Comment by orta** [comment]
Cool, open to PRs 👍🏻  - so long as it doesn't break backwards compat

**Comment by Baltazardoung** [comment]
I'm not sure #1254 fixes this problem.

I'm not familiar with ruby but first tested the same thing just taking inspiration from #1220. And I still had these warnings.

This has been confirmed by testing the new version 8.0.5:

```yaml
test danger:
  before_script:
    - danger --version
  script:
    - danger --fail-on-errors=true
```

What produced the result :

```shell
$ danger --version
8.0.5
$ danger --fail-on-errors=true
...
/usr/local/bundle/gems/danger-8.0.5/lib/danger/request_sources/gitlab.rb:208: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/danger-8.0.5/lib/danger/request_sources/gitlab.rb:348: warning: The called method `submit_inline_comments!' is defined here
...
/usr/local/bundle/gems/danger-8.0.5/lib/danger/request_sources/gitlab.rb:226: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/danger-8.0.5/lib/danger/helpers/comments_helper.rb:94: warning: The called method `generate_comment' is defined here
```

So were you able to test these patches (#1254 && #1222) with version 2.7.x of ruby?

thanks,

**Comment by afaucogney** [comment]
Same for me. Warning are still there !
