### ISSUE TITLE
Passing parameters to Dangerfile 

### ISSUE THREAD

**Issue by GauravP123** [danger/danger#1261]
# Report

## What did you do?

I have one Dangerfile which contains different checks like lint,detect, etc. right now we have dedicated jenkins jobs for each check and job runs parallelly. 
the command to execute dangerfile is
` bundle exec danger --verbose --dangerfile=Dangerfile --new-comment`

## What did you expect to happen?
It's possible to pass a parameter to dangerfile which will take input and it will pick which check to execute. for eg I can pass lint as param in the danger file and Inside dangerfile, I can check if the input is lint then execute lint n ignore the rest of the checks 

## What happened instead?
As all checks are in one file it executes all checks for all jobs

## Your Environment

* Which CI are you running on? Jenkins

**Comment by orta** [comment]
You can use process env vars to do this today, but maybe you can expose the `danger-id` param to the runtime somehow and that can be available for comparing against?

**Comment by GauravP123** [comment]
will get `danger-id ` inside dangerfile?
