### ISSUE TITLE
HTML tables vs Markdown tables

### ISSUE THREAD

**Issue by jeroenvisser101** [danger/danger#127]
I noticed we're creating comments with HTML tables, but I'm not sure why we chose them above Markdown tables.

Any reason for this?

**Comment by orta** [comment]
They look better: #37 

It makes a bit more effort on our part, but IMO is worth it

**Comment by jeroenvisser101** [comment]
But no markdown anymore :sob:

**Comment by jeroenvisser101** [comment]
Would be great if we would be able to use `<style>table { width: 100% }</style>` within GitHub

**Comment by orta** [comment]
Markdown in comments should work!

**Comment by jeroenvisser101** [comment]
@orta but then *we* do the rendering? Right?

**Comment by orta** [comment]
Yes, so it's not perfect

example: https://github.com/artsy/eigen/blob/79436cebc5f4c73a0a15b6dfb773d325be9591d1/Dangerfile#L45-L47

**Comment by jeroenvisser101** [comment]
I wonder if there is a way to trick GitHub in making it 100% width without using HTML, but I guess not

**Comment by orta** [comment]
I'm definitely open to ideas there ;)

**Comment by jeroenvisser101** [comment]
I've tried and failed, sadly, this seems the only possible solution!
