### ISSUE TITLE
Web reference shows wrong regexp which was already fixed in code

### ISSUE THREAD

**Issue by nekketsuuu** [danger/danger#1276]
# Report

I noticed that the web reference <https://danger.systems/reference.html> shows a wrong regexp `^+` instead of `^\+`, even though https://github.com/danger/danger/pull/1167 fixed this problem.

Screenshot:

<img width="826" alt="It shows `^+`" src="https://user-images.githubusercontent.com/4374702/98694602-fcf60880-23b4-11eb-9a96-891151131281.png">

Possibly this page isn't updated, or a static page generator un-escapes `\+`.

Would you please update this regexp?

(Feel free to close this issue if this issue should be opened at <https://gitlab.com/danger-systems/danger.systems>.)

**Comment by orta** [comment]
This should be fixed
