### ISSUE TITLE
Inline comments are always striked through

### ISSUE THREAD

**Issue by imminent** [danger/danger#1277]
I've been testing inline comments generated by Danger, I haven't seen any discussion of this from my research either. Regardless of what line I pass the `message` the inline comment is always including a `<del>` tag which is causing the resulting message to be <del>striked through</del>. This is pretty distracting to the reader, makes it seem like a message to be ignored.

In my testing, I originally thought it was a limitation for commenting on deleted lines, since the inline comment would never line up with the right line in Github Pull Request. I have also tested modified lines, and the inline comment is on the right line in the Pull Request, but it is still striked through. I see in the Danger code that it is intentionally putting the `<del>` tag, but I can't see how to get the inline comments to ever be submitted without it.

This is showing on Danger v7.0.0

**Comment by orta** [comment]
Yeah, you are close there, there needs to be separate IDs for each run otherwise they clash and you get the cross outs. 
It's a CLI flag, no idea how it works in fast lane

**Comment by imminent** [comment]
Ok, so in config.yml for CircleCI we have:
```yaml
- run:
          name: Run Danger
          command: bundle exec danger --danger_id=standard
```
and in Fastfile for Fastlane we have:
```ruby
      # Runs Dangers to report the difference in build size.
      danger(
        dangerfile: "./Dangerfile-APK-Report",
        danger_id: "APK-Size",
        use_bundle_exec: true,
        verbose: true
      )
```
(we have __now__ in my testing, the config.yml didn't have an id CLI flag originally)

**Comment by imminent** [comment]
update: I think there's a good chance that this was because of the IDs. My latest test with a fresh PR and updated to Danger 8.2.1 is posting comments without the strikethrough!

**Comment by orta** [comment]
Cool 👍🏻
