### ISSUE TITLE
For Danger's "is not a contributor" it could look inside the GitHub org?

### ISSUE THREAD

**Issue by orta** [danger/danger#128]
Could use the GitHub API, or could just check to see if someone is publicly on the Danger org?

Note this is specific to danger/danger - not in general.

**Comment by jeroenvisser101** [comment]
I guess it would need more permissions too, then

**Comment by orta** [comment]
Would need to invite the bot to the org, and to add this to the token

![screen shot 2016-03-10 at 9 40 13 am](https://cloud.githubusercontent.com/assets/49038/13672768/1ef9fca0-e6a4-11e5-8526-1699d3ff8727.png)

**Comment by jeroenvisser101** [comment]
It might be cool to show in which org-teams the user is, so you could filter on that, say a member of 'Frontend' changing `lib/*.rb` files, that might trigger a warning.

**Comment by orta** [comment]
Ideally, I can automate some of this stuff with these ideas too: https://github.com/Moya/contributors/issues/6

**Comment by jeroenvisser101** [comment]
You mean with these 'squad_goals'?

**Comment by orta** [comment]
Yep, then instead of "not a contributor" it's "not yet a contribute - welcome!"

**Comment by jeroenvisser101** [comment]
That'd be nice. I also imagine people joining different teams based on their interest (maybe not so much with Danger though, but I could see people interested in implementing new APIs and others liking it more to extend the DSL)

**Comment by orta** [comment]
Shipped
