### ISSUE TITLE
Problem with displaying emojis on Bitbucket

### ISSUE THREAD

**Issue by mar-comp** [danger/danger#1281]
# Report

## What did you do?
Every time our pull request runs Danger on TeamCity by `bundle exec danger`.

## What did you expect to happen?
I expect that emoji is displayed in some message in our repo on Bitbucket.

## What happened instead?
Emojis aren't displayed. Instead it I see some text.

<img width="633" alt="102614317-11ac8580-4145-11eb-94c2-d421dbd6c58c" src="https://user-images.githubusercontent.com/15248225/102911219-c8ce3700-448c-11eb-9a02-30aff06aeb1e.png">

## Your Environment

* Which CI are you running on?
TeamCity + Fastlane

* Are you running the latest version of Danger?
Yes

* What is your Dangerfile?
```
swiftlint.lint_all_files = true
swiftlint.lint_files(fail_on_error: true, inline_mode: true)

xcode_summary.ignores_warnings = true
xcode_summary.report 'build/reports/errors.json'
```

**Comment by orta** [comment]
Cool, you're welcome to give it a shot.

**Comment by manicmaniac** [comment]
Does this issue still exist? Looks https://github.com/danger/danger/pull/1182 has solved the same problem :eyes:

**Comment by manicmaniac** [comment]
I think this issue is similar to #1290 and it's been solved in https://github.com/danger/danger/pull/1326.

Let me close this one and feel free to reopen it if you have a trouble.
