### ISSUE TITLE
Why should the Github token be visible on the travis build log?

### ISSUE THREAD

**Issue by mjobin-mdsol** [danger/danger#1283]
# Report

## What did you do?

Getting setup

I noticed in your instructions you suggest making the GitHub Token in the Travis build log.
I don't understand why. Does not it makes it possible for anyone to find it and use it? Especially for an open source repo?

https://github.com/danger/danger/blob/907cf4e12e3d9ee95a665c8339ac54ba80d3d13f/lib/danger/ci_source/travis.rb#L27

Also, do my user needs write access to the repo? I have only given `public-repo` as you instructed, but it can't post comments to PR

Thanks

## Your Environment

* Which CI are you running on? : Travis-CI
* Are you running the latest version of Danger? : Yes
* What is your Dangerfile? : Default from `danger init`

**Comment by orta** [comment]
public repo access with "display value" set should be enough for the account to comment on any public repo unless travis or GitHub has changed. I'd recommend re-looking at your settings and build logs.
