### ISSUE TITLE
📖 :book: icon in Bitbucket

### ISSUE THREAD

**Issue by swiftyfinch** [danger/danger#1290]
Hello! Seems to be the 📖 `:book:` icon don't render in Bitbucket:

<img width="338" alt="Screenshot 2021-02-06 at 20 35 58" src="https://user-images.githubusercontent.com/64660122/107125427-0b23ca00-68bb-11eb-99e5-bd164dd9abb8.png">

I wonder If I can replace it somehow?

**Comment by orta** [comment]
Sure, its probably in a template somewhere 👍🏻

**Comment by swiftyfinch** [comment]
Seems to be it's Bitbucket problem. Couldn't find easy solution for change that icon.
So, let it be 😔

**Comment by orta** [comment]
I'll leave it open because it is a real bug and someone is welcome to fix it 👍🏻

**Comment by manicmaniac** [comment]
Looks https://github.com/danger/danger/pull/1326 solved this issue.

Let me close this issue and feel free to reopen this one if you have any trouble.
