### ISSUE TITLE
Encourage reusing different Danger snippets like in pre-commit

### ISSUE THREAD

**Issue by okainov** [danger/danger#1302]
The tool is really nice, but putting all rules into one Dangerfiles makes it not really nice and not really reusable from team to team. In contrast, https://github.com/pre-commit/pre-commit takes approach of having each "rule" independently, so end users just list list of "rules" with some parameters.

I think it would be great to allow something similar, to include existing Danger rules from different places, this would significantly improve reusability, simplify maintenance and encourage further development.

**Comment by orta** [comment]
At this point, Danger ruby is probably not going to really change anymore. 

The goal for Danger is to give a runtime for your rules, and something like that could be built on top of the runtime (people have done similar for Danger JS) but Danger is maintainable by me in 4 languages by having a tiny core and leaves that sorta stuff to be decided in user-land code

**Comment by okainov** [comment]
I don't really care whether Danger JS or Ruby or Python or Swift, the idea is for core.

Yeah, I understand current situation and its benefits (like full blown programming language power for any kind of rules), but that's the double-sided sword. While giving insane flexibility, it effectively discourages reusing. Just look even at the home page, sections "examples" and/or "show me some dangerfiles". Basically, you show just code snippets to be copypasted. There is no such thing as "danger-snippet 'No merge commit is in history'", that's what everyone has to copy-paste or implement itself.

In contrast, take a look at [pre-commit](https://pre-commit.com/) approach, one is encouraged to take something else already created by others:
```
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
 ```

And even if the logic behind each small snippet is really small ("commit title should start with Capital Letter" / "no trailing whitespaces"), it still makes sense to make it reusable and don't ask people to copy-paste the logic every time...

**Comment by orta** [comment]
Yeah, I don't think it's a bad idea, it's just not what Danger is. Danger provides the primitives.

I don't expect projects to have the same dangerfiles, if you do want that at scale that's what Peril solves  https://github.com/danger/peril

You can use plugins, gems, eggs, etc if people want to create re-usable  chunks of code, vendored by your environment's dependency managers and correctly locked and semver'd.

**Comment by okainov** [comment]
>I don't expect projects to have the same dangerfiles

dangerfiles - of course not.  But their "ingridients" are mostly the same. But if you take several projects using Danger I'm 100% sure they will have the same (or similar) snippets for one or another check. Like I mentioned "check commit message is Capitalized" (or "check commit message is not capitalized", why not), or "check no merge commits", or "mark WIP PRs" or "PR is too big" - and while there will be still some uniqueness, probably most of real-project Dangerfiles consist of the same snippets...

>that's what Peril solves https://github.com/danger/peril

From the first sight it seems I don't understand how is something mentioning "github hooks", comparing with Github Actions is related to small reusable snippets of danger-code... Maybe better examples there would help, but from the first sight Peril feels something completely different, more like complete CI system, I'd say looking at readme?

**Comment by orta** [comment]
Yeah, I think it's just a fundamental difference in design philosophy, I want people to write their dangerfiles and write their own rules. These cultural rules have impact on teams, and any new rules should be taken very seriously. Plugins do a good job of letting people share ingredients, but dropping the runtime and being an arbitrary eslint/rubocop for a PR isn't a goal for me.

**Comment by okainov** [comment]
>Plugins do a good job of letting people share ingredients

Could you please elaborate here a bit, how is it applicable to Danger? If in our team we have 50 repos which would share 15 rules in different combinations, how can we extract the rules from each individual repo?

**Comment by orta** [comment]
You make a plugin: https://danger.systems/guides/creating_your_first_plugin.html

The plugin has a set of functions which you choose to call or not in each Dangerfile. Or look at Or look at `danger.import_dangerfile` in the reference. That said, if you have 50 repos in the same GitHub org, Peril is a better fit https://artsy.github.io/blog/2017/09/04/Introducing-Peril/ IMO ( and what we did for hundreds of Artsy's repos )

**Comment by okainov** [comment]
>You make a plugin: https://danger.systems/guides/creating_your_first_plugin.html

This sounds like too much and it does affect the environment (we're using Docker image with only danger installed and it's somehow static). Ideally I'd see it as pushing Dangerfile snippet somewhere and just specifying the link in the final Dangerfile or so...

I gave example of pre-commit configuration above, but even some dirty way like this would be still much preferable than copypasting:

Dangerfile with some semi-pseudocode of `execute`:
```
execute https://our.gitlab.com/repos/dangerfiles/no-merge-commits.danger
execute https://our.gitlab.com/repos/dangerfiles/capitalize-commits.danger

warn "Test message"
```

We can do something similar with some random script preprocessing danger.config into real Dangerfile for sure, but I was hoping something like that should exist already... Seems no =(

> That said, if you have 50 repos in the same GitHub org, Peril is a better fit https://artsy.github.io/blog/2017/09/04/Introducing-Peril/ IMO ( and what we did for hundreds of Artsy's repos )

I really don't see how can it be applied for repos with existing infrastructure. We do have our own CI already and do not want to migrate it to anything else. We see Danger run as just one initial stage of pipeline check which is done in parallel with `pre-commit`. Not to mention that you say "github app" and we cannot use github apps due to security policies.

**Comment by orta** [comment]
You're welcome to use `danger.import_dangerfile` to share a single dangerfile from one repo,  use plugins, or Danger JS's import dangerfiles but providing a task abstraction and building out a set of dependency management stuff isn't going to happen in danger.

**Comment by okainov** [comment]
Yay, `danger.import_dangerfile` is apparently exactly what I was missing, I took a deeper look and now refactored our dangerfiles so they now look much cleaner and nicer IMO.

FYI if someone will find this issue in the future, you might get something like this:

```
dangerSnippetsRepo = "our-github/dangerfiles-snippets"

danger.import_dangerfile(github: dangerSnippetsRepo, path: "ruby/no-merge-commits.danger")

danger.import_dangerfile(github: dangerSnippetsRepo, path: "ruby/commit-message-basic.danger")
danger.import_dangerfile(github: dangerSnippetsRepo, path: "ruby/commit-message-length-body-72.danger")
danger.import_dangerfile(github: dangerSnippetsRepo, path: "ruby/commit-message-length-title-50.danger")
danger.import_dangerfile(github: dangerSnippetsRepo, path: "ruby/commit-message-no-fullstop.danger")
danger.import_dangerfile(github: dangerSnippetsRepo, path: "ruby/commit-message-title-imperative.danger")
danger.import_dangerfile(github: dangerSnippetsRepo, path: "ruby/commit-message-with-component-start-lowercase.danger")

danger.import_dangerfile(github: dangerSnippetsRepo, path: "ruby/wip-github-notify.danger")
```

I miss passing arguments/options (like exact line length), but it's already good and much better than copypaste.
