### ISSUE TITLE
Consider exposing `mr_changes`

### ISSUE THREAD

**Issue by rymai** [danger/danger#1308]
I would be interested to access `DangerfileGitLabPlugin#mr_changes` directly.

I wrongly assumed it was exposed already here: https://gitlab.com/gitlab-org/gitlab-dangerfiles/-/blob/8802a22a5e18cc13abe5e2ee39377a1eb0f1597f/lib/danger/plugins/helper.rb#L419 but it's not.

I'll open a MR for that unless there's strong opinions against it.

**Comment by orta** [comment]
Seems reasonable to me 👍🏻

**Comment by rymai** [comment]
Cool, I've opened https://github.com/danger/danger/pull/1309 for this. 🙏

**Comment by orta** [comment]
shipped
