### ISSUE TITLE
Danger Plugins as Gems

### ISSUE THREAD

**Issue by orta** [danger/danger#131]
They should have two major abilities:

- Provide DSL attributes
- Support providing it's own linting, if requested by a Dangerfile, with the current context variables provided by the system.

What does this look like?

```  Ruby
# Gemfile
gem 'danger'
gem 'danger-jekyll'
```

```  Ruby
# Dangerfile
[... usual stuff specific to a project]

# `danger-jekyll` exposes a DSL attribute for `validate_prose`
validate_prose "_site/pages/*.md"

# runs any plugin linting
plugin 'jekyll', { :project => "Artsy" }
```

This isn't too new, CocoaPods does all this stuff, and we spend a long time figuring out how this should work.

TODOs for this issue to be done:

- [ ] Adds plugin DSL attributes
- [x] Adds plugin linter hooks, with optional hash support
- [ ] Documentation
- [ ] `danger plugin create` - generates a stubbed plugin, see [cocoapods-plugins](https://github.com/CocoaPods/cocoapods-plugins/blob/master/lib/pod/command/plugins/create.rb) - this can be expanded upon in a different issue if needed.

**Comment by jeroenvisser101** [comment]
Oh that'd be cool! I was thinking about allowing custom templates for the comment, but that could totally be possible with a plugin, too!

**Comment by orta** [comment]
One of the advantages of this, is that you can have org-wide Dangerfiles without duplication, so `danger-cocoapods` could validate rubocop how we like it, and the same for specific types of CHANGELOG styles. We put it all in a gem, it is done on every build. Ace.

**Comment by jeroenvisser101** [comment]
Plus: you could have plugins for framework specific stuff, such as Rails checking if tests are written when certain files change, or if you ran `bundle install` after changing your `Gemfile`.

**Comment by jeroenvisser101** [comment]
There seems to already be some logic for plugins, but they can now only exist within the danger repository.

- [`protected_files.rb`](https://github.com/danger/danger/blob/99425352b62bbff7f559448234c72896ecab351f/lib/danger/plugins/protect_files.rb)
- [`def load_plugins`](https://github.com/danger/danger/blob/60a72be4907bb8011e00df4e3bb29d15818b30a7/lib/danger/dangerfile_dsl.rb#L19-L23)

**Comment by jeroenvisser101** [comment]
So then `plugin '...'` would register a plugin? And it's DSL would only be available after registering? Or would it auto-register itself if it's present in the `Gemfile`?

**Comment by orta** [comment]
I think the plugin would register DSL attributes automatically, but to run the automatic ones you have to trigger it with `plugin '...'`

**Comment by jeroenvisser101** [comment]
We could have *just the DSL*, and a plugin such as Rails would bind to `check_rails!` or something?

**Comment by orta** [comment]
I know where you're coming from, and there's definitely overlap, given that they can expose the things it does as functions. 

I think one of the biggest factors towards separating the the `plugin` from the DSL is consistency between all gems and forwards source-compatibility with new versions.

**Comment by jeroenvisser101** [comment]
> I think one of the biggest factors towards separating the the plugin from the DSL is consistency between all gems and forwards source-compatibility with new versions.

I have to agree with that, I think that's a really good reason to go for the `plugin` function instead.
