### ISSUE TITLE
How to Ignore Error in Android project

### ISSUE THREAD

**Issue by YevhenTroshchii** [danger/danger#1323]
I got `Using 'Log' instead of 'Timber'` Danger error.

Cause is that `launchdarkly` inside itself uses `timber` logging library.

| | | | | | +--- com.launchdarkly:**launchdarkly**-android-client-sdk:2.14.2
| | | | | | | +--- com.google.code.gson:gson:2.8.2 -> 2.8.6
| | | | | | | +--- com.launchdarkly:okhttp-eventsource:1.8.0
| | | | | | | | +--- com.squareup.okhttp3:okhttp:3.8.1 -> 3.14.7 ()
| | | | | | | | +--- org.slf4j:slf4j-api:1.7.22 -> 1.7.25
| | | | | | | | --- com.google.code.findbugs:jsr305:3.0.2
| | | | | | | +--- com.squareup.okhttp3:okhttp:3.12.2 -> 3.14.7 ()
| | | | | | | +--- com.jakewharton.timber:**timber**:4.7.1

But when I run `Lint` check I don't get report about it.
Could you please tell me how can I ignore this report in Danger?

• I've tried added ignore to lint file.
• I've checked https://danger.systems/guides/faq.html And was trying add
```    // > Danger: Ignore "Using 'Log' instead of 'Timber'"```
To the files where Danger found these errors  but still se these errors in the Dangers report.

## Your Environment
* CI - Jenkins
* Version danger (8.3.1)

  ```ruby
  # ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
  ```

**Comment by orta** [comment]
You'd probably need to figure out how to make that only apply in your code or the plugin, this isn't an issue with Danger itself 👍🏻
