### ISSUE TITLE
lines_of_code not correct

### ISSUE THREAD

**Issue by KrauseFx** [danger/danger#133]
With the Dangerfile https://github.com/fastlane/fastlane/blob/master/Dangerfile
```ruby
warn("Big PR") if lines_of_code > 500
```

it would still trigger the Big PR message on this pull request https://github.com/fastlane/fastlane/pull/3699 which only has 173 new lines of code (note: I removed danger's comment here)

**Comment by orta** [comment]
Was there a merge in the commit range, that would have triggered #88 ?

**Comment by KrauseFx** [comment]
Good point, maybe that's causing it

**Comment by KrauseFx** [comment]
Ah, another one: https://github.com/fastlane/fastlane/pull/3700

**Comment by jeroenvisser101** [comment]
Interesting, could it be that the range is wrong, and it takes the merge commit into account that's already in master? That last PR could never be 'big'

**Comment by orta** [comment]
@KrauseFx can you run with `--verbose` for a bit, so it's easier to inspect?

**Comment by orta** [comment]
#135 will fix this

**Comment by KrauseFx** [comment]
oh yeah :tada:
