### ISSUE TITLE
occasionally getting "authenticity of host 'github.com...' can't be established prompt

### ISSUE THREAD

**Issue by tinder-terrychu** [danger/danger#1337]
# Report

## What did you do?
I currently have a Buildkite build that performs Danger tasks. One of the Buildkite steps run this command
`bundle exec danger --dangerfile=build-configuration/danger/DangerfileReportDiffuse --danger_id=${DANGER_PREFIX}_diffuse`

## What did you expect to happen?
Expect the build to swiftly perform the tasks with no user prompts or failures.

## What happened instead?
A user prompt of such pops up instead and causes the build to hang
```
The authenticity of host 'github.com (140.82.112.4)' can't be established.
--
  | RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
  | Are you sure you want to continue connecting (yes/no)?
```
which eventually leads to the build to time out after being stuck here.
The weird thing is after a few retries, the build would actually work and and the prompt wouldn't show up anymore. If something is wrong with the git ssh connection, I would expect it to fail consistently but this only happens sometime.

## Your Environment
The build is performed in Docker container running on the image `cimg/android:2021.10.2`

* Which CI are you running on?
Buildkite
* Are you running the latest version of Danger?
unsure - will update it here when I find out
* What is your Dangerfile?

```
diffuseFile = File.open("diffuse_report", "r+").read
dependencyTreeDiffFile = File.open("dependency_tree_diff_report", "r+")
textToReport = diffuseFile.split("=================")

markdown "```diff"

if File.size(dependencyTreeDiffFile) > 0
  markdown "Dependency Tree Diff"
  markdown dependencyTreeDiffFile.read
  markdown ""
end

markdown "Apk Diffuse"
markdown textToReport[0]
markdown "```"
```

**Comment by orta** [comment]
The git pull under the hood is literally a `git pull` I believe, perhaps there's a git flag you can add to force accepting something like this?

**Comment by tinder-terrychu** [comment]
Hmm what confounds me is the part where the first couple times would show that prompt but then eventually with enough retries we would get past that prompt. This doesn't happen all the time but occasionally so I am wondering if there is some underlying implementation of the way danger system performs git ssh connections that I need to be aware of?

**Comment by orta** [comment]
Nope, nothing special, it's just using git commands based on the remotes your CI set up

**Comment by tinder-terrychu** [comment]
Perhaps something is off with the environment/image the builds are running in. Will investigate further. Closing issue. Thank you.
