### ISSUE TITLE
`github.pr_draft?` is returning false even though the PR is a draft

### ISSUE THREAD

**Issue by rogerluan** [danger/danger#1338]
# Report

## What did you do?

In my Dangerfile, when querying `github.pr_draft?` it returns false even though the PR is a draft.

## What did you expect to happen?

It'd expect `github.pr_draft?` to return true.

## What happened instead?

`github.pr_draft?` returns false.

## Your Environment

* Which CI are you running on? **_Bitrise CI_**
* Are you running the latest version of Danger? **_Nope, I'm on v8.3.1_** 
* What is your Dangerfile?

```ruby
# Skip If Needed
if defined?(github) and github.pr_draft?
  # If it's a draft PR, skip. If it's running locally, don't skip.
  message("Test: skipping early")
  return
else
  # Log debugging information
  if defined?(github)
    is_github_defined = true
  else
    is_github_defined = false
  end
  if is_github_defined
    is_draft_pr = github.pr_draft?
  end
  message("Test: not skipping. is_github_defined  = #{is_github_defined}, is_draft_pr = #{is_draft_pr}")
end
```

This is the result:

>Test: not skipping. is_github_defined = true, is_draft_pr = false

**Comment by orta** [comment]
Perhaps there's more states in the API than before? 

https://github.com/danger/danger/blob/af3d856d5cbaaebf534b853df347373dbd0ee30b/lib/danger/danger_core/plugins/dangerfile_github_plugin.rb#L146-L152

**Comment by rogerluan** [comment]
Good catch, I'll print the pr_json mergeable_state and report back 😁

**Comment by rogerluan** [comment]
Btw https://docs.github.com/en/graphql/reference/enums#mergestatestatus
