### ISSUE TITLE
Allow `danger local` to receive a PR reference

### ISSUE THREAD

**Issue by jeroenvisser101** [danger/danger#134]
Instead of getting the `git log` and finding the last merge, in the case of a issue like #133, it'd help a lot if we could say `danger local --pr="my/repo#123"` to specify we'd want to test the local `Dangerfile` on a specific PR.

**Comment by orta** [comment]
I agree, I think this makes sense.

**Comment by jeroenvisser101** [comment]
Great! I might be able to take some time to make that work, I think it's fairly trivial :)

**Comment by jeroenvisser101** [comment]
This seems to be a little harder than I initially thought, since we mix and match local git operations with GitHub API calls. Testing it on a specific repo would require you to have that repository locally, so `modified_files` is available.

**Comment by orta** [comment]
ah, I understand, yeah, two options: 
* don't support `danger local` against repos that don't have the same set of commits ( forks are fine for example )
* see if there's github apis for the diff stuff

**Comment by jeroenvisser101** [comment]
@orta I'd like the second the most, but that would also mean you'd have to have a GitHub API token for the `danger local` command

**Comment by orta** [comment]
Yeah, that's not really doable IMO, which makes the former more reasonable

**Comment by orta** [comment]
unless you can find a way to pull it out of a keychain or something?

**Comment by jeroenvisser101** [comment]
Yeah or using [dotenv](https://github.com/bkeepers/dotenv) or something?

**Comment by orta** [comment]
I mean like literal keychain.app

**Comment by jeroenvisser101** [comment]
Oh, yeah, but that would make it Mac specific, having a `.env` (ignored) and `.env.sample` (as template) for `danger local` would allow people from all platforms to work with it

**Comment by orta** [comment]
I think I can live with mac specific, having another dependency and all that setup doesn't really seem worth it for Danger `local` I, not sure I see people using it that much. 

Or maybe that's just how I work

**Comment by jeroenvisser101** [comment]
It wouldn't be an issue for me, I'm on OS X. It would however be an issue for contributors using Linux/Unix/Windows, wanting to test locally.

Another option would be to create a alias locally (`alias danger_local='DANGER_GITHUB_TOKEN="..." bundle exec danger local'`)

**Comment by orta** [comment]
Turns out I'm using `danger local` a lot now, and this is now something I want 👯
