### ISSUE TITLE
5.16.1 is failing CI due to a version bump in oktokit.

### ISSUE THREAD

**Issue by afilbert** [danger/danger#1343]
# Report

4.22.0 of oktokit caused our [CI builds to start failing](https://github.com/octokit/octokit.rb/issues/1389). I realize we're on an old version of danger, so please close if not relevant.

**Comment by orta** [comment]
Sure, you're welcome to take a look at updating octokit 👍🏻

**Comment by jlo1** [comment]
Note: the latest version (8.4.5) is now failing with Octokit 4.22. But reportedly, 8.4.2 works fine: https://github.com/octokit/octokit.rb/issues/1389#issuecomment-1012725903

**Comment by manicmaniac** [comment]
Danger has migrated to Octokit 5 at https://github.com/danger/danger/pull/1377.

So let me close this issue.
