### ISSUE TITLE
Allow faraday 2.x?

### ISSUE THREAD

**Issue by jrochkind** [danger/danger#1349]
Danger's gemspec does not allow faraday 2.x

https://github.com/danger/danger/blob/626c450619d19377424feb1071b22fda8a8a8141/danger.gemspec#L27

Faraday 2.0 was [released on January 4th](https://rubygems.org/gems/faraday/versions/2.0.0)

Danger gemspec not allowing it means that any project that uses danger can't run with faraday 2.x. 

Can Danger gemspec be updated to allow faraday 2.x?  I would recommend still allowing faraday 1.x as well, it should be possible to work with both, and will ease the (not insignificant) pain of trying to migrate things to faraday 2.x when one's whole dependency tree has to allow whatever version of faraday you are using.

**Comment by orta** [comment]
Yep, happy to support two versions of faraday - I'd take a PR which updates the gemfile lock to 2.0 + gem spec to also support and passes CI 👍🏻

**Comment by jrochkind** [comment]
Thanks! I will give it a shot and see if it Just Passes with faraday 2. 

(You don't seem to have a Gemfile.lock file in the repo? Which is typical and expected for a gem repo! So I think the PR just needs to update gemspec... if that passes CI).

**Comment by jrochkind** [comment]
OK, the dependency tree here doesn't actually let us upgrade to Faraday 2.0 yet. (Surprise surprise! I arrive here already like 3 levels deep in my own dependency tree, I don't even know what `danger` is myself, I'm just trying to get my dependency tree to allow me to upgrade to faraday 2.  Why not go deeper!

```
    chandler was resolved to 0.9.0, which depends on
      octokit (>= 2.2.0) was resolved to 4.22.0, which depends on
        sawyer (~> 0.8.0, >= 0.5.3) was resolved to 0.8.2, which depends on
          faraday (> 0.8, < 2.0)
```

Those are the latest version of chandler, octokit, and sawyer. 

OK, I'll go one more level down my dependency tree, and go file a ticket on sawyer asking if it can support faraday 2.x!  It hasn't had a release since 2019... 

Filed on sawyer: https://github.com/lostisland/sawyer/issues/70

Wow, I am on a deep journey here to try to get my dependency tree to allow faraday 2.

**Comment by jrochkind** [comment]
I've done v2 upgrade in a bunch of gems now, on my journey. 

It usually requires more than zero changes, but fairly minor ones -- and ones that can be made such that your code will now work with both 1.x (at least latest 1.x versions) and 2.x. 

The hard part is just travelling up and down the dependency tree trying to get indirect dependencies to allow/work with faraday 2.x. 

Even making a PR, as we all know, often PR's just sit there and don't attract maintainer attention. :(

So I appreciate you making comments here! :)

**Comment by vilmantas** [comment]
@orta 

There doesn't seem to be any blockers to remove the strict versioning. I've made a PR https://github.com/danger/danger/pull/1415 and the specs run fine. Could you please take a look at it or ping someone who has the ability to merge it check whether it's okay?
