### ISSUE TITLE
Consider not storing environment variables in an instance variable in Danger::GitLabCI

### ISSUE THREAD

**Issue by rymai** [danger/danger#1351]
# Report

## What did you do?

When a `Dangerfile` is invalid, depending on the error, the API token can be leaked since environment variables are stored as `@env`: https://github.com/danger/danger/blob/626c450619d19377424feb1071b22fda8a8a8141/lib/danger/ci_source/gitlab_ci.rb#L70

## What did you expect to happen?

Environment variables shouldn't be dumped when a `Danger::Dangerfile`/`Danger::GitLabCI` object is inspected.

Given the `@env` is only used [in the lazy `#pull_request_id` method](https://github.com/danger/danger/blob/626c450619d19377424feb1071b22fda8a8a8141/lib/danger/ci_source/gitlab_ci.rb#L82), we can probably just set `self.pull_request_id` in `#initialize`, similarly to how other CI sources are doing, e.g.:

- https://github.com/danger/danger/blob/626c450619d19377424feb1071b22fda8a8a8141/lib/danger/ci_source/circle.rb#L82
- https://github.com/danger/danger/blob/626c450619d19377424feb1071b22fda8a8a8141/lib/danger/ci_source/codeship.rb#L40

## What happened instead?

The token from `@env` was leaked when an error including the `Danger::Dangerfile`/`Danger::GitLabCI` objects happened.

## Your Environment

* Which CI are you running on?
  * GitLab CI
* Are you running the latest version of Danger?
  *  `8.4.2`
* What is your Dangerfile?

Doesn't really matter here.

**Comment by manicmaniac** [comment]
Fixed in https://github.com/danger/danger/pull/1353
