### ISSUE TITLE
Consider not posting "Invalid `Dangerfile` file" error as comment

### ISSUE THREAD

**Issue by rymai** [danger/danger#1352]
# Report

## What did you do?

When a `Dangerfile` is invalid, [the error is posted as a comment](https://github.com/danger/danger/blob/626c450619d19377424feb1071b22fda8a8a8141/lib/danger/danger_core/dangerfile.rb#L298). This can create security problems if the error contains tokens that are masked as CI/CD variable, but wouldn't be masked when printed in a comment.

Similarly to https://github.com/danger/danger/issues/1351, here the problem is that the error is actually posted as a comment, circumventing any CI/CD "masking" feature (such as the one GitLab provides) that hides variable values from job logs.

## What did you expect to happen?

Danger should not post a message in the PR/MR when the `Dangerfile` is invalid. The error can already be seen in the job logs, which should be sufficient and less confusing for people looking at the PR/MR comments.

## What happened instead?

Similarly to https://github.com/danger/danger/issues/1351, here the problem is that the error is actually posted as a comment, circumventing any CI/CD "masking" feature (such as the one GitLab provides) that hides variable values from job logs.

## Your Environment

* Which CI are you running on?
  * GitLab
* Are you running the latest version of Danger?
  * `8.4.2`
* What is your Dangerfile?

Doesn't really matter here.

**Comment by manicmaniac** [comment]
Fixed in #1354
