### ISSUE TITLE
Authentication broken w/ Octokit 4.22

### ISSUE THREAD

**Issue by BobbyMcWho** [danger/danger#1361]
# Report

## What did you do?
Run `DANGER_GITHUB_API_TOKEN=[redacted] danger local`

## What did you expect to happen?
Expected danger to run against last PR

## What happened instead?
```
Local repository was not found on GitHub. If you're trying to test a private repository please provide a valid API token through DANGER_GITHUB_API_TOKEN environment variable.
```

I ended up resolving this by installing octokit 4.21
See https://github.com/octokit/octokit.rb/issues/1392

**Comment by manicmaniac** [comment]
Danger has migrated to Octokit 5 at https://github.com/danger/danger/pull/1377.

So let me close this issue.
