### ISSUE TITLE
Cannot specify danger_id testing locally

### ISSUE THREAD

**Issue by lukeredpath** [danger/danger#1362]
# Report

## What did you do?

I'm trying to test changes to my Dangerfile locally - every time I make changes I can never remember how to do this and the documentation for this isn't that great. I just want to run my Dangerfile against my local file system rather than a specific PR - I just want to test my changes work!

`bundle exec danger pr https://github.com/danger/danger/pull/662 --danger_id=prebuild`

We use two separate Danger IDs to run pre and post-build checks on CI. I'm trying to test the prebuild flow but the Danger ID is not getting set. It defaults to "danger" every time.

What I really want to be able to do:

`bundle exec danger local --danger_id=prebuild`

This should not require Github authentication or a PR, it should just run against my local filesystem. Otherwise it isn't really "local", is it?

## What did you expect to happen?

I'd expect the danger ID to get set to "prebuild".

## What happened instead?

The danger ID is "danger".

## Your Environment

* Local environment
* Danger 8.3.1
* Ruby 2.7.1

**Comment by orta** [comment]
`danger local` works that way in danger js, I feel like there's an issue somewhere to handle it in a similar manner in danger ruby with another command to not break existing scripts.

**Comment by manicmaniac** [comment]
It is because that `Danger::Local#run` doesn't pass `danger_id` to `Danger::Dangerfile` and `Danger::EnvironmentManager` objects.

https://github.com/danger/danger/blob/v9.2.0/lib/danger/commands/local.rb#L52
https://github.com/danger/danger/blob/v9.2.0/lib/danger/commands/local.rb#L60

#1422 will fix this issue.
