### ISSUE TITLE
danger pr posts to the pr as a check

### ISSUE THREAD

**Issue by BobbyMcWho** [danger/danger#1364]
## What did you do?
 Run `danger pr [link]`

## What did you expect to happen?
Runs against the PR, but does not post to the PR

## What happened instead?
It posts the result to the PR as a check

**Comment by orta** [comment]
That's not the intention of that command, use `danger ci` for leaving comments

**Comment by BobbyMcWho** [comment]
Can we fix it so that it doesn't post to the PR when running locally then? The behavior does not match the current description
