### ISSUE TITLE
danger Mac OS machine keychain

### ISSUE THREAD

**Issue by seeramasri** [danger/danger#1367]
## What did you do?

`bundle exec danger - --danger_id=myId --dangerfile=Danger/file`

## What did you expect to happen?
run danger without asking me to add GitHub username and password into the CI machine 

## What happened instead?

when I use Mac OS machine and run danger first time asking me to enter my GitHub username and password because danger uses git HTTP and needs to save these credentials in the keychain, I already added  `DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

## Your Environment
 * MacOS 12.3
 * danger 8.5.0

**Comment by manicmaniac** [comment]
@seeramasri 
Could you run `git remote -v` and check the origin URL uses `git` protocol?

**Comment by manicmaniac** [comment]
I guess it is because of your git fetch URL uses HTTPS protocol and the repository requires authentication. Please make sure you are using git protocol and configure your SSH settings properly.

Let me close this issue for now but feel free to reopen this one later.
