### ISSUE TITLE
How can I get branch name?

### ISSUE THREAD

**Issue by jsouzapp** [danger/danger#1368]
# Report

## What did you do?
Tried to get the branch name on dangerfile

## What did you expect to happen?
Return the branch name for me to do a verification on danger

## What happened instead?

ℹ Please replace this with of what happened instead.
e.g. 💥

## Your Environment
* Which CI are you running on? bitrise
* Are you running the latest version of Danger? yes
* What is your Dangerfile? 
* Basically I want to verificy if the branch matches with the regex pattern.
  ```if (git.lines_of_code > 800 and github.pr.head.ref.match(branch_refactor_or_removed_regex))  ```

I already tried with github.pr_head, or danger.github.pr.head... and nothing works.

**Comment by manicmaniac** [comment]
Perhaps `github.branch_for_base` could be the one you were looking for.

**Comment by manicmaniac** [comment]
Feel free to reopen this one if the solution on my last comment is not suitable one.
