### ISSUE TITLE
Repo suggestions

### ISSUE THREAD

**Issue by sandstrom** [danger/danger#1372]
1. Remove the old project at https://github.com/danger/danger/projects/3
2. Open a discussions tab, that you can move a lot of "issues" into (questions, suggestions, etc). That way, the actual list of issues will be much fewer. Easier to get an overview.

**Comment by orta** [comment]
I removed the project, but I don't think we need discussions turned on, we get so few non Feature Request or Bug Report issues that opening a new space just doesn't seem worth the split.

**Comment by sandstrom** [comment]
@orta Alright, makes sense!
