### ISSUE TITLE
9.1.0 release with release-notes missing, only tag

### ISSUE THREAD

**Issue by apps4everyone** [danger/danger#1407]
9.1.0 release with release-notes missing, would be nice to have notes with changes.
Thank you

**Comment by orta** [comment]
The changelog in the repo is always the source of truth here, sometimes people who refer using the release notes feature keep that up to date but it's not a part of the release process

**Comment by manicmaniac** [comment]
I just updated GitHub releases.
https://github.com/danger/danger/releases/tag/v9.1.0
