### ISSUE TITLE
Cannot find a merge base between danger_base and danger_head

### ISSUE THREAD

**Issue by SugiKent** [danger/danger#1409]
# Report

## What did you do?

`bundle exec danger`

## What did you expect to happen?

Running your Dangerfile without it crashing

## What happened instead?

`Cannot find a merge base between danger_base and danger_head.` error occurred.

## Your Environment

* Which CI are you running on?
Bitrise

* Are you running the latest version of Danger?
8.6.1

* What is your Dangerfile?
it is not a problem in this issue.

## My guess

The error is caused with forked repository. Bitrise released a new version `Git Clone Repository` https://github.com/bitrise-steplib/steps-git-clone/releases/tag/7.0.0 to clone repository shallowly. However danger command tries to [fetch repository with increasing the depth recursively to find a mere-base](https://github.com/danger/danger/blob/f0a0ae079578f5a21f842b334812243a3b3a36de/lib/danger/scm_source/git_repo.rb#L128), it fetches from original repository(not-forked) so danger cannot find it.

### Using downgrade before 7.0.0

It worked in my environment.

### Entering enough clone-depth number to find head commit hash in Edit Workflows page of Git Clone Repository in Bitrise

Then Bitrise would clone enough depth from forked repository initially before execute danger command.

**Comment by manicmaniac** [comment]
Looks similar to https://github.com/danger/danger/issues/913

Currently shallow clone breaks Danger in any CI sources.
