### ISSUE TITLE
I can't install Danger

### ISSUE THREAD

**Issue by rodolfoggp** [danger/danger#1413]
# Report

## What did you do?

I ran these instructions on my machine:
```
git clone https://github.com/danger/danger.git
cd danger
bundle install
```

## What did you expect to happen?

I expected Danger to be successfully installed

## What happened instead?

I got this error:
```
Git error: command `git fetch --force --quiet --no-tags --depth 1 --
https://github.com/sourcelevel/faraday-http-cache.git
refs/heads/master:refs/heads/master` in directory
/Library/Ruby/Gems/2.6.0/cache/bundler/git/faraday-http-cache-e57b4c9971b386331e184414b539c095a0af0523
has failed.
error: cannot open FETCH_HEAD: Permission denied
```

## Your Environment

* I'm running these commands on a Mac machine (MacBook Air, M1 - MacOS 11.6.8)
* Are you running the latest version of Danger? Yes

**Comment by ydah** [comment]
Perhaps, but Ruby 2.6 seems to be unsupported.
https://github.com/danger/danger/pull/1378

**Comment by ydah** [comment]
I could not reproduce it.
But looking at the following it looks like a permission error.

```
error: cannot open FETCH_HEAD: Permission denied
```

I don't fully understand your environment, but it looks like it would be a good idea to grant permissions to the directory as follows.

```console
sudo chown -R (username) /Library/Ruby/Gems/2.6.0/cache/bundler/git/
```

**Comment by rodolfoggp** [comment]
You're right! Now it worked, thanks a lot.
