### ISSUE TITLE
Support custom CI check names

### ISSUE THREAD

**Issue by Vacxe** [danger/danger#1431]
# Feature request:

We have a multiple checks on CI with Danger
```
@acoe-mobile
danger/pull-request
danger/swiftformat
danger/swiftlint 
danger/androidcodestyle
....
````

Is it possible to customise prefix name? for example `android/codestyle, android/detekt, global/pull-request`

If this functionality not provided or not documented Ill be happy to implement it

**Comment by orta** [comment]
I think the danger id argument does this, if not it probably should 

On Mon, Mar 27, 2023, at 6:38 AM, Konstantin Aksenov wrote:
> 
> 
> Feature request:
> 
> We have a multiple checks on CI with Danger
> 
> ***@***.***
> danger/pull-request
> danger/swiftformat
> danger/swiftlint 
> danger/androidcodestyle
> ....
`

**Comment by Vacxe** [comment]
@orta appreciate for assistance! Looks right to me.

**Comment by Vacxe** [comment]
I checked with `danger_id`. The behaviour is slightly different. 
For example I setting it as `Foo` then report id will be "danger/Foo". Wanna have the same configuration flexibility for prefix. to have smth like "Bar/Foo" instead of "danger/Foo"
