### ISSUE TITLE
SwiftLint usage and exclusion rules in .swiftlint.yml

### ISSUE THREAD

**Issue by cprince-foreflight** [danger/danger#1453]
# Question

I'm considering adding `Danger` SwiftLint usage to a Github repo something like this:

```
let filesToLint = (danger.git.modifiedFiles + danger.git.createdFiles).filter { !$0.contains("Documentation/") }

SwiftLint.lint(.files(filesToLint), inline: true)
```

However, I assume that is not going to respect exclusion rules in the .swiftlint.yml file(s) in the repo. For example, I have .swiftlint.yml setup to exclude certain directories.
Also, I assume it will run the linter on added or modified files that are *not* Swift.

Is there a way I can have Danger respect the exclusion rules in the .swiftlint.yml file(s) in the repo?

Is there a way I can exclude non-Swift files?

Thanks!

**Comment by manicmaniac** [comment]
@cprince-foreflight 

Sorry, this is Danger (Ruby) repository.

Your code looks like Swift and your question is related to danger-swiftlint plugin.
You may better to open an issue on [danger/swift](https://github.com/danger/swift) or [danger-swiftlint](https://github.com/ashfurrow/danger-swiftlint) repository.
