### ISSUE TITLE
Bitbucket Cloud access token

### ISSUE THREAD

**Issue by gbero** [danger/danger#1463]
Hey,

I cannot find how to use Bitbucket Cloud access token using danger (ruby). 
This is working fine with danger-js.

Is this not implemented here ?

Thanks for your help

**Comment by manicmaniac** [comment]
@gbero Is this your what you are looking for?

https://github.com/danger/danger/blob/02ceb1f3bbd580982ca6e986130c9f0b36c20f9c/lib/danger/ci_source/bitbucket_pipelines.rb#L11-L16

**Comment by gbero** [comment]
The method you're suggesting is through OAUTH. 
What I'm looking for is repository access token
See danger-js documentation [here](https://github.com/danger/danger-js/blob/main/docs/usage/bitbucket_cloud.html.md)

**Comment by manicmaniac** [comment]
This feature will be added in the next release.
