### ISSUE TITLE
Better icon/logo for GitHub org/README

### ISSUE THREAD

**Issue by jeroenvisser101** [danger/danger#147]

**Comment by dbgrandi** [comment]
This is in the works, but will take some time. :wink:

**Comment by marcelofabri** [comment]
![687474703a2f2f692e67697068792e636f6d2f6b6a384d31785252726959336d2e676966](https://cloud.githubusercontent.com/assets/275822/13506088/2a8d2b6e-e131-11e5-840c-95a267a4ab82.gif)

**Comment by orta** [comment]
This is in https://github.com/danger/design
