### ISSUE TITLE
without GITHUB_TOKEN

### ISSUE THREAD

**Issue by huthe98** [danger/danger#1474]
I just want to give danger access to the project repo without using GITHUB_TOKEN because it is associated to my account

**Comment by manicmaniac** [comment]
@huthe98 
I think it could be achieved by using a [fine-grained token](https://docs.github.com/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token). If you use GitHub Actions, `secrets.GITHUB_TOKEN` could be another option.

**Comment by manicmaniac** [comment]
Feel free to reopen this issue if my answer is not suitable for your question.
