### ISSUE TITLE
Compatibility with Octokit v8

### ISSUE THREAD

**Issue by kuranari** [danger/danger#1475]
# Report
After upgrading to Danger v9.4.2, line comments are not being posted.

The API for `create_pull_request_comment` has changed in Octokit v8. 
* https://github.com/octokit/octokit.rb/pull/1566
* https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#create-a-review-comment-for-a-pull-request

However, it seems that Danger is still using `position`.
* https://github.com/danger/danger/blob/9ba87e9758d1851d3a4449e5827555abb3e3772f/lib/danger/request_sources/github/github.rb#L346-L347

I am not certain if this is due to the changes in Octokit v8, but I will report it nonetheless.

## What did you do?
* Upgrad danger to v9.4.2
* Run danger on GitHub Actions

## What did you expect to happen?
* A line comment is posted

## What happened instead?
* An issue comment was posted (not as a line comment).
* A 422 error occurred with the GitHub API.
<img width="1658" alt="image" src="https://github.com/danger/danger/assets/2577343/70dec4d9-fa0d-46f3-b8db-ec7425568e12">

## Your Environment

* Which CI are you running on?
    * GitHub Actions
* Are you running the latest version of Danger?
    * Yes(v9.4.2)
* What is your Dangerfile?

I use [danger-regexp](https://github.com/mtsmfm/danger-regexp) plugin.

```ruby
regexp.lint do
  match(/: any/, <<~MESSAGE)
    Don't use `any` in the new ts(tsx) file.
    (It is OK to use `any` temporarily for migrated file from existing js files.)

    #{feedback_link("never-use-any")}
  MESSAGE
end
```

**Comment by manicmaniac** [comment]
> An issue comment was posted (not as a line comment).

I reproduced the issue with a minimal repository on https://github.com/manicmaniac/danger-issue-1475/pull/2.
Another pull request with the same changes but with octokit 7.1.1 did not reproduce the issue (https://github.com/manicmaniac/danger-issue-1475/pull/3).

As you said, it could be a bug of danger.

> A 422 error occurred with the GitHub API.

However I could not reproduce this one.

**Comment by kuranari** [comment]
Thank you for your confirmation.

> However I could not reproduce this one.

The 422 error refers to the output below: 
https://github.com/manicmaniac/danger-issue-1475/actions/runs/7501381794/job/20421920622#step:4:12
