### ISSUE TITLE
[bug] GitHub api request fails when PR diff is > 300 files

### ISSUE THREAD

**Issue by ilynehan** [danger/danger#1489]
# Report

## What did you do?

We are running a custom danger file on PR diff:
```
bundle exec danger --dangerfile=danger/DangerCheckDiff.rb --danger_id=check_diff --fail-on-errors=true
```

We have started to see failures on CI within the last month or so when running this for PRs that have more than 300 files diff. 

Here's the error log:

```
GET https://api.github.com/repos/procore/android/pulls/18757: 406 - Sorry, the diff exceeded the maximum number of files (300). Consider using 'List pull requests files' API or locally cloning the repository instead. (Octokit::NotAcceptable)
Error summary:
  resource: PullRequest
  field: diff
  code: too_large // See: https://docs.github.com/rest/pulls/pulls#list-pull-requests-files
```

## What did you expect to happen?
Danger runs successfully on PRs with diff of over 300 files.

## What happened instead?
Danger fails with error (see above)

## Your Environment

* Which CI are you running on? - CircleCI
* Are you running the latest version of Danger? - Yes, we are on `danger 9.4.3`
* What is your Dangerfile?

  ```ruby
  # we are checking all our modified & added files
  (git.modified_files + git.added_files).each do |file|
    ...
  ```

**Comment by orta** [comment]
This is how we solved it in danger js, for anyone interested in making a PR: https://github.com/danger/danger-js/pull/1440

**Comment by technicalpickles** [comment]
Did some poking around to see where this change would need to be, and think I narrowed it down to here:

https://github.com/danger/danger/blob/b5e62e87bcdc919707afb93e1a39347964ff527b/lib/danger/request_sources/github/github.rb#L79-L81

**Comment by erik-agens** [comment]
Hi!
Any updates or this or any viable work arounds?

**Comment by timbaev** [comment]
Thanks to @orta and @technicalpickles, I opened a PR with fixes:
https://github.com/danger/danger/pull/1491

**Comment by mvandervelden** [comment]
It would be great to have a patch release for this fix, since it breaks our CI pipelines every once in a while.
Is this to be expected anytime soon?

**Comment by manicmaniac** [comment]
I will publish a new release in a couple of days. You may want to use `master` branch until then.
