### ISSUE TITLE
README needs to explain how to set up auth

### ISSUE THREAD

**Issue by orta** [danger/danger#15]

**Comment by jeroenvisser101** [comment]
:+1:

**Comment by jeroenvisser101** [comment]
As far as I can see, the only thing you need to do is:

1. Create a new account for the bot to use (with a awesome robot profile picture)
2. Create a API token with full-access
3. Add that token to the environment variables with `DANGER_GITHUB_API_TOKEN` as the variable name
4. ...
5. :moneybag: 

Correct me if I'm wrong here

**Comment by orta** [comment]
This is done via `danger init` now, the issue can be closed :+1: 

but yeah! you're right ;)

**Comment by jeroenvisser101** [comment]
Ah, alright!
