### ISSUE TITLE
danger --version doesn't print out version

### ISSUE THREAD

**Issue by KrauseFx** [danger/danger#151]
```
$ danger --version

$ 
```

**Comment by jeroenvisser101** [comment]
Do we want `danger --version` or more like `git`'s `git version`?

**Comment by KrauseFx** [comment]
I'd prefer to have `danger -v` :+1:

**Comment by orta** [comment]
yeah, option not command :+1:

**Comment by jeroenvisser101** [comment]
Claide supports aliases for options? Like `-v, --version`?

**Comment by orta** [comment]
https://github.com/CocoaPods/CLAide/pull/60 in discussion ATM

**Comment by dbgrandi** [comment]
Fixed `--version` in #214, but it did not add a `-v` alias.

**Comment by marcelofabri** [comment]
I think we can close this and open a new issue if we want to add an alias.
