### ISSUE TITLE
Cross out resolved issues

### ISSUE THREAD

**Issue by KrauseFx** [danger/danger#153]
When first submitting a PR and getting this:
  
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">2 Warnings</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:warning:</td>
      <td>I don't like the code style</td>
    </tr>
            <tr>
      <td>:warning:</td>
      <td>Too many lines of code</td>
    </tr>
    
  </tbody>
</table>

Let's assume I'd push another commit fixing the issue, we could run a diff and do the following

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%">2 Warnings</th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:white_check_mark: </td>
      <td><strike>I don't like the code style</strike></td>
    </tr>
            <tr>
      <td>:warning:</td>
      <td>Too many lines of code</td>
    </tr>
    
  </tbody>
</table>

Idea from @camacho :+1:

**Comment by camacho** [comment]
:+1:

**Comment by camacho** [comment]
it leaves the history intact - in case anyone was talking about it in the PR or whatever

**Comment by orta** [comment]
This is clever, good thinking.

**Comment by orta** [comment]
I guess I'd advise leaving that metadata inside the `<table>`'s data attributes, then pull it out to compare?

**Comment by KrauseFx** [comment]
@orta putting metadata is a great idea, but we don't have a unique way to identify each message, except for the string, right? This way we might run into issues when you have the same message multiple times

**Comment by marcelofabri** [comment]
@KrauseFx but does it make sense to have the same message multiple times? It wouldn't help to identify the issue at all (in general, not talking about this idea).

**Comment by KrauseFx** [comment]
@marcelofabri It doesn't, but it might happen easily.

**Comment by jeroenvisser101** [comment]
Would you consider this as something you could turn on/off? I like the idea, just not sure if it would be something you'd want all the time.

**Comment by KrauseFx** [comment]
@jeroenvisser101 the crossing off of items?

**Comment by jeroenvisser101** [comment]
@KrauseFx yeah, I see that sometimes I want to see old comments on diff (the outdated ones), but mostly, I don't need them, which is nice, since they're collapsed. This list will always be visible.

Also, having 'This PR has no description'-like messages persistent in a list (even if crossed off) wouldn't make sense. Could you define this per message maybe (`warn '...', sticky: true`?)

**Comment by KrauseFx** [comment]
How about just having a third table for resolved issues?

**Comment by jeroenvisser101** [comment]
Not sure if that'd fix the part where some messages (such as 'PR is marked as WIP') would fix.

You can also do it the other way around, `warn 'PR is WIP', sticky: false`, if we'd chose to have it 'sticky' as default.

**Comment by KrauseFx** [comment]
:rocket:
