### ISSUE TITLE
Ensure common array functions for `xxx_files` retain our custom class for globing

### ISSUE THREAD

**Issue by orta** [danger/danger#155]
- [ ] map
- [ ] select
- [ ] reject
- [ ] drop_while

**Comment by KrauseFx** [comment]
Sorry not sure what you mean by that?

**Comment by marcelofabri** [comment]
```ruby
[1] pry(main)> class List < Array
[1] pry(main)* end  
=> nil
[2] pry(main)> List
=> List
[5] pry(main)> List.new
=> []
[6] pry(main)> List.new.class
=> List
[7] pry(main)> List.new.map { |l| l }
=> []
[8] pry(main)> List.new.map { |l| l }.class
=> Array
```

**Comment by marcelofabri** [comment]
These functions always return `Array`, but a consumer might think they would return our custom subclass, so `include?` would work with the file globing.

**Comment by sleekybadger** [comment]
@orta hi, here [pr](https://github.com/danger/danger/pull/815) to fixes this.
