### ISSUE TITLE
Danger's commit range may include last PR's merge commit when there is only 1 commit in PR

### ISSUE THREAD

**Issue by orta** [danger/danger#160]
See Danger's notes from #159 - I've seen a similar thing in `artsy/Eigen` - this is just a guess, but it fits.

**Comment by daniel-beard** [comment]
I'm seeing this as well, the `modified_files` includes files from the PR's destination branch's last commit.

**Comment by jamtur01** [comment]
Also seeing this.

**Comment by orta** [comment]
I've not seen this, and I don't think it's fixed, if anyone sees it on an OSS project, let me know and I'll dig in with `danger local --pry --use-merged-pr=XX`

**Comment by chrismcg** [comment]
I'm seeing something similar and I think it might be down to commits being made to the base branch while the PR is open. I haven't had time to delve too deeply into what's happening but am seeing warnings on a project that could be explained by this.

* staging is at `aaaaaa`
* make feature branch PR and add some commits `111111`
* someone else merges a PR so staging is now at `bbbbbb`
* add some commits to the feature branch PR so it's a `222222`

The feature branch PR modified_files is now between `222222` and `bbbbbb`, not `222222` and `aaaaaa` where it branched off from.

Will hopefully have time to check this in the next couple of days.

**Comment by jamtur01** [comment]
Hey @chrismcg Did you puzzle this out at all? I'm stuck. :(

**Comment by yimingtang** [comment]
I came across the same problem. I the diff option that danger use is not `...`. However, GitHub uses 
`git diff commitA...commitB` usually.

Ref: https://git-scm.com/docs/git-diff

**Comment by yimingtang** [comment]
```
master:           ---a--------b--------c--------d-----e
                      \
                       \
feature-branch:         e------f----g
```

A developer sends a PR from feature-branch to master. GitHub uses `git diff e...g` command and shows the diff on web. Danger uses `ruby-git` gem which only supports `git diff e..g` command.

**Comment by orta** [comment]
Interesting, I think this [image sums it up quite nicely](http://stackoverflow.com/questions/7251477/what-are-the-differences-between-double-dot-and-triple-dot-in-git-dif)

![git-diff-help](https://cloud.githubusercontent.com/assets/49038/17720357/4e296a38-63ef-11e6-89d0-3a8dcbbf8928.png)

**Comment by jamtur01** [comment]
Oh nice catch.

**Comment by jamtur01** [comment]
Use the `git` exec instead of ruby-git in https://github.com/danger/danger/blob/75ac7e1d77349f7357cd91811bd32e1a6909a9e7/lib/danger/scm_source/git_repo.rb ?

**Comment by orta** [comment]
A bunch of the public API depends on the object that `git.diff` returns, would need to find a way to make the host git command map back into that original object. 

FWIW, we moved _to_ ruby-git because different CIs had different versions of git which ended up with unpredictable results.

Definitely worth looking into

**Comment by jamtur01** [comment]
Ah blast. This has forced us to turn off Danger so I'll try to look on the weekend.

**Comment by yimingtang** [comment]
Here's a quick fix:

1. Fork ruby-git and add a `git diff ...` API or a `git merge-base` API.
2. Send a PR.
3. Use the forked version of ruby-git in Danger.
4. Once the PR has been merged, use the new ruby-git.

I'm not familiar with Ruby, so anyone can help?

Here's an outdated git merge-base PR: https://github.com/schacon/ruby-git/pull/43/files

**Comment by jamtur01** [comment]
https://github.com/jamtur01/ruby-git/tree/gitbase

**Comment by orta** [comment]
Could we add these functions to the `Git::Base` object at runtime in Danger? There's a lot of un-responded to PRs in ruby-git - I'd rather not wait on a release from their side

**Comment by orta** [comment]
Looks like it, will make a PR

![screen shot 2016-08-17 at 9 07 48 am](https://cloud.githubusercontent.com/assets/49038/17737239/1d8548dc-645a-11e6-8893-1a22acda5805.png)

**Comment by orta** [comment]
This is released as 2.1.3 - will keep the issues open to see if it comes back up

**Comment by yimingtang** [comment]
Awesome! Thank you, @orta .

**Comment by BasThomas** [comment]
I think this can be closed? :)

**Comment by orta** [comment]
yeah, works for me 👍
