### ISSUE TITLE
Markdown parser parses _underscore_ text as italic

### ISSUE THREAD

**Issue by jeroenvisser101** [danger/danger#164]
https://github.com/fastlane/fastlane/pull/4058

Here, `UPPERCASE_VAR_NAME` was parsed as UPPERCASE*VAR*NAME

We should configure redcarpet to enable [`:no_intra_emphasis`](https://github.com/vmg/redcarpet#and-its-like-really-simple-to-use).

**Comment by marcelofabri** [comment]
That should be an easy fix: https://github.com/danger/danger/blob/master/lib/danger/request_sources/github.rb#L31

**Comment by jeroenvisser101** [comment]
Nice, should be doable haha :)
