### ISSUE TITLE
Support for local development

### ISSUE THREAD

**Issue by KrauseFx** [danger/danger#17]
It should be possible to run `./bin/danger` locally to setup the initial `Dangerfile`

**Comment by orta** [comment]
This could be a different command `danger local`. To not confuse people when setting up their CI. It could look through your git log for the last PR `0b49a41 Merge pull request #18 from KrauseFx/more-dynamic-emojis` as they are easy to spot.

It can then run through your `Dangerfile` with that PR, then console out the results.

**Comment by KrauseFx** [comment]
I like the idea of automatically picking the last PR.

**Comment by orta** [comment]
Closed by #40
