### ISSUE TITLE
Is it possible to use danger within the Xcode bots CI?

### ISSUE THREAD

**Issue by Antondomashnev** [danger/danger#171]
I'm not sure If I'm doing something wrong.
But my script trigger fails with the message
`Could not find a CI source`

Thanks.

**Comment by orta** [comment]
No-one has worked on adding Xcode Bots support, I imagine you'll need to set it up like [jenkins](https://github.com/danger/danger/blob/master/lib/danger/ci_source/jenkins.rb)?

**Comment by Antondomashnev** [comment]
Thanks for the quick reply.

Probably that's should be like jenkins, I'll try to take a look on it later.

**Comment by KrauseFx** [comment]
I guess that's where @czechboy0 is an expert :rocket:

**Comment by czechboy0** [comment]
It should be easy or super easy to get danger working with Xcode Server.

*Super easy* version:
If you're using [Buildasaur](https://github.com/czechboy0/Buildasaur), the automatically created bots for each PR already follow a scheme which contains both the repo name and the PR number. So all you need to do in the danger adapter is to read the bot name from the `XCS_BOT_NAME` and parse out the repo slug and the PR number. AFAIR danger takes care of the rest.

*Easy* version:
If you're **not** using Buildasaur and for some reason you manually create Bots for each PR, you would need to manually inject the environment variables in the prebuild/postbuild script with something like `export REPO_SLUG=danger/danger` and `export PR_NUMBER=17`, which you'd detect in the danger adapter. It's a stretch, tbh I think the first version using Buildasaur is just much simpler.

In both cases, you'd trigger danger from the prebuild script.

**Comment by Antondomashnev** [comment]
@czechboy0 amazing, I'm using [Buildasaur](https://github.com/czechboy0/Buildasaur). 
I think I could do a pr to make danger support Xcode Server CI.

**Comment by jeroenvisser101** [comment]
@Antondomashnev that'd be great!

**Comment by orta** [comment]
fixed by #172
