### ISSUE TITLE
Don't allow for dupes in sticky responses

### ISSUE THREAD

**Issue by orta** [danger/danger#183]
![screen shot 2016-04-23 at 13 57 04](https://cloud.githubusercontent.com/assets/49038/14761507/57b1d28c-095b-11e6-87f9-b21b2fe9ce26.png)

I've pushed some commits that also ignored the failing rule 👍

**Comment by jeroenvisser101** [comment]
Yeah, saw that too, haven't had time to report it yet 👍 , also, very nice to give an example of how to add changelog entries!

**Comment by marcelofabri** [comment]
This was fixed by #252 👍
