### ISSUE TITLE
Documentation about DANGER_GITHUB_API_TOKEN

### ISSUE THREAD

**Issue by marcelofabri** [danger/danger#186]
Currently there's no documentation about `DANGER_GITHUB_API_TOKEN` (although `init` tells about it).

Maybe we should add a note on README?

**Comment by jeroenvisser101** [comment]
When I started, I expected much more info to appear in the README, since I normally don't install/run everything, only after reading docs. So 👍  for more docs

**Comment by KrauseFx** [comment]
We should completely rewrite the README anyway I think.

**Comment by orta** [comment]
Once we've got gem plugins working, this should happen, that requires me to be in a room with Dave to force him to finish it up 👯

**Comment by orta** [comment]
This is starting to happen now as I'm moving everything user-facing into danger.systems.
