### ISSUE TITLE
Could not find a CI source?

### ISSUE THREAD

**Issue by joshrlesch** [danger/danger#189]
#Trying to get danger up and running, but we use TeamCity. Getting this error when running `bundle exec danger --verbose`

Am I missing something?

```
/Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/danger-0.7.3/lib/danger/environment_manager.rb:24:in `initialize': Could not find a CI source (RuntimeError)
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/danger-0.7.3/lib/danger/commands/runner.rb:35:in `new'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/danger-0.7.3/lib/danger/commands/runner.rb:35:in `run'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/gems/danger-0.7.3/bin/danger:5:in `<top (required)>'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/bin/danger:23:in `load'
	from /Users/josh.lesch/.rvm/gems/ruby-2.2.1/bin/danger:23:in `<main>'
```

Also, can I tell it what PR to use when using the `local` arg?

**Comment by jeroenvisser101** [comment]
@joshrlesch thanks for trying danger! Currently, we don't support (but are accepting PRs for that, you can [look at existing CI sources](https://github.com/danger/danger/tree/master/lib/danger/ci_source) if you're willing to give that a shot, it's really straight forward!)

**Comment by jeroenvisser101** [comment]
fyi: `self.validates?` method should return true if it has detected that it is able to handle it (i.e. it's being ran on TeamCity), `initialize` method should set both `self.repo_slug` to `org/repo` or `user/repo`, and it should set `self.pull_request_id` to the PR number.

**Comment by joshrlesch** [comment]
Ok cool, I will open a PR next week when I have some time. But first just trying to get it to post a comment. :/

When I use the local flag with `--verbose` it tells me the pull that it is going to use, but it doesn't actually post anything. I know my github token has the correct auth as I use it for commit status.

**Comment by jeroenvisser101** [comment]
> When I use the local flag with --verbose it tells me the pull that it is going to use, but it doesn't actually post anything. I know my github token has the correct auth as I use it for commit status.

`local` will actually not post anything, but that's by-design. It's for developers to test the workings, by outputting what would normally be posted as a comment to stdout instead.

Using it on a CI server would make it post, if you set the API token in a environment variable.

**Comment by joshrlesch** [comment]
Ok, so I got it working with teamcity but hardcoding
`GIT_URL` and `ghprbPullId`
Is there a better way to spoof it to thinking its a jenkins ci server?

But to me some scary stuff shows in the logs. Im not the best at git, but I don't like the fact that its trying to delete `danger_base` as I have to set that to `develop`
```
[15:13:57][Step 10/10] fatal: Couldn't find remote ref refs/pull/3069/merge
[15:13:58][Step 10/10] fatal: ambiguous argument 'danger_head': unknown revision or path not in the working tree.
[15:13:58][Step 10/10] Use '--' to separate paths from revisions, like this:
[15:13:58][Step 10/10] 'git <command> [<revision>...] -- [<file>...]'
[15:13:58][Step 10/10] error: The branch 'danger_base' is not fully merged.
[15:13:58][Step 10/10] If you are sure you want to delete it, run 'git branch -D danger_base'.
[15:13:58][Step 10/10] error: The branch 'danger_base' is not fully merged.
[15:13:58][Step 10/10] If you are sure you want to delete it, run 'git branch -D danger_base'.
```

**Comment by jeroenvisser101** [comment]
@joshrlesch can you send me a [Gist](https://gist.github.com) to show the code you're using to produce those errors?

**Comment by jeroenvisser101** [comment]
@joshrlesch just checking back — did everything work out? If not, feel free to reach out, we'd love to help :)

**Comment by joshrlesch** [comment]
Sorry didn't work on this over the weekend. You asked for a Gist with code to repo this, but honestly Im not doing more than the DangerFile and these three lines in a custom fastlane action.
```
ENV['GIT_URL'] = "https://github.com/org/private_repo"
ENV['ghprbPullId'] = "3069"

`bundle exec danger --base=develop --verbose`
```

Dangerfile looks like this
```
# Make it more obvious that a PR is a work in progress and shouldn't be merged yet
warn("PR is classed as Work in Progress") if pr_title.include? "[WIP]"

if pr_body.length < 5
  warn("Please provide a changelog summary in the Pull Request description @#{pr_author}")
end

# Warn when there is a big PR
warn("Big PR") if lines_of_code > 500

if ENV['AMOUNT_INCREASE'].to_f >= 1.00
    warn("You are going to increase the app size by #{ENV['PERCENT_INCREASE']}% to #{ENV['NEW_APP_SIZE']} MB's. That means we are only #{ENV['AMOUNT_REMAINING']} MB's from our 100 MB cap.")
end
```

**Comment by joshrlesch** [comment]
@jeroenvisser101 I'm curious what you guys are trying to do here?
https://github.com/danger/danger/blob/d6e1389d3c9f2de7d53b5eecbdf784f9f3f409c7/lib/danger/environment_manager.rb#L36-L69
It doesn't look like `ensure_danger_branches_are_setup` ever gets called, and you're hard coding `danger_base` and `danger_head`. What is the purpose of that?

**Comment by jeroenvisser101** [comment]
@joshrlesch 

> You're hard coding danger_base and danger_head. What is the purpose of that?
See https://github.com/danger/danger/pull/135, it's to make sure merges are not counted towards the stats.



> And what the point of calling ensure_danger_branches_are_setup?
It's being ran [here](https://github.com/danger/danger/blob/33db1d8a6713d6590259f1d8f1bbb2ae0d7153a2/lib/danger/commands/runner.rb#L39)

**Comment by jeroenvisser101** [comment]
As for your example, are you sure `ENV['GIT_URL'] = "https://github.com/org/private_repo"` is being parsed correctly?

**Comment by joshrlesch** [comment]
I believe so, Danger is posting its comments to the PR, so it has to know the repo and PR.

**Comment by jeroenvisser101** [comment]
I'm not sure, about this one... @orta @KrauseFx you mind having a look at this?

**Comment by orta** [comment]
to ensure a consistent diff, danger created her own branches which are the closest we can get to make Danger work as expected when we may not have all the information needed locally: https://github.com/danger/danger/pull/135

**Comment by jeroenvisser101** [comment]
```
[15:13:58][Step 10/10] error: The branch 'danger_base' is not fully merged.
[15:13:58][Step 10/10] If you are sure you want to delete it, run 'git branch -D danger_base'.
[15:13:58][Step 10/10] error: The branch 'danger_base' is not fully merged.
[15:13:58][Step 10/10] If you are sure you want to delete it, run 'git branch -D danger_base'.
```

I think these errors are from git's built-in protection to not delete branches that weren't merged. We might want to change the `-d` flag to `-D` to force and be silent about it.

**Comment by joshrlesch** [comment]
Yeah I think your right, I removed the `--base=develop` as I didn't need that on my build agent. It just checks out a ref of the branch by ssh. Danger still posts to the PR but its not doing the clean up, guessing because of the `-D` being needed.
```
ENV['ghprbPullId'] = "3036"
ENV['GIT_URL'] = "https://github.com/org/private_repo.git"
puts `bundle exec danger --verbose`
```
output in my build logs
```
[09:11:48][Step 4/5] From ssh://github.com/hudl/modi
[09:11:48][Step 4/5]  * [new ref]         refs/pull/3069/merge -> danger_head
[09:11:49][Step 4/5] error: branch 'danger_base' not found.
```
I ssh'ed into my build agent and did a `git branch` in the checkout dir and get this after Danger is done running. As you can see `danger_head` is still around.
```
tc-mac-03:16fab46ab991b3c qahudl$ git branch
* (HEAD detached at 23ca967)
  danger_head
```

**Comment by jeroenvisser101** [comment]
Yeah, that should be an easy fix, let me see if I can fix this tonight :)

**Comment by joshrlesch** [comment]
Awesome, I can help test that change if you need some help.

**Comment by jeroenvisser101** [comment]
@joshrlesch that'd be great. I'll ping you once I have something solid!

**Comment by jeroenvisser101** [comment]
@joshrlesch so this is actually because [the call that's being done in `runner.rb`](https://github.com/danger/danger/blob/342dac4dc17dd3bc575ab0f0384c736a2ba6023a/lib/danger/commands/runner.rb#L39) isn't in the local runner, and that call sets up the branches.

**Comment by jeroenvisser101** [comment]
*Sorry, posted this on the wrong issue 😕*

so this is actually because [the call that's being done in `runner.rb`](https://github.com/danger/danger/blob/342dac4dc17dd3bc575ab0f0384c736a2ba6023a/lib/danger/commands/runner.rb#L39) isn't in the local runner, and that call sets up the branches.

**Comment by orta** [comment]
This should be fixed in 0.7.4 if you want to give it a run

**Comment by orta** [comment]
Going to close this, mainly as I don't want to leave stale issues around. If this comes back up, totally happy to have it re-opened.

**Comment by AnandWalvekar** [comment]
Hi @jeroenvisser101 
I have posted a comment in https://github.com/danger/danger/issues/727. Can you please help me on it.
In short danger keeps saying  "Could not find the type of CI for Danger to run on"
