### ISSUE TITLE
Danger local should cache the returned JSON data from GitHub for a PR

### ISSUE THREAD

**Issue by orta** [danger/danger#198]
It'd be a common experience to re-iterate again and again when making changes to your `Dangerfile`- currently `danger local` assumes you'll need to do it enough times that you can keep it under the unauthenticated GitHub API limit, but I've hit it once or twice. 

By caching the PR response, we can make less API calls in iterations.

**Comment by KrauseFx** [comment]
Yeah, this is a great addition :+1:

**Comment by orta** [comment]
This is in.
