### ISSUE TITLE
4 of 6 links in TOC at top of project README are dead

### ISSUE THREAD

**Issue by jeremy-w** [danger/danger#202]
The README has what looks like a concise table of contents at the top:

>  Installation • Usage • DSL • Constraints • Advanced • Contributing 

These are all links, presumably to what were once sections in the README. The only links that still work are "DSL" and "Advanced". The remainder appear dead. Some sections appear to have been renamed, while others are no longer present, such as "Constraints".

**Comment by jeroenvisser101** [comment]
Good catch!
