### ISSUE TITLE
Allow to lint issues

### ISSUE THREAD

**Issue by mrackwitz** [danger/danger#209]
It would be super cool if Danger could assist linting issues. Even though GitHub introduced the `ISSUE_TEMPLATE.md`, I see overall on projects I work on, that these are not fully understood or filled correctly.

Some of them could use some heuristics, indicators or measures to figure out whether an issue is meaningful or not. Feedback from Danger is likely easier to handle for all involved than from humans.

Also Danger could help classifying issues, which need revision by their author by tagging them as such to streamline the workflow for contributors and maintainers who triage issues.

**Comment by orta** [comment]
To pull this off, we need to be able to support danger as a service - https://github.com/danger/danger/issues/42

As there would be no CI process to run

**Comment by jeroenvisser101** [comment]
Tagging could happen within CI right? It'd only run when commits are pushed though, not when comments are placed (unless you manually change the CirceCI/Travis hook settings in GitHub, but then all would run when a comment is placed)

**Comment by orta** [comment]
@mrackwitz means actual issues like this one, thing that don't or won't have related commits and thus no connection to CI

**Comment by jeroenvisser101** [comment]
Oh, actual issues would be no-go until we introduce 'DaaS', yeah

**Comment by orta** [comment]
Peril does this now 👍
