### ISSUE TITLE
Plugin access to octokit

### ISSUE THREAD

**Issue by wilrnh** [danger/danger#210]
Hey, I'm writing a plugin and would like to know if there's anyway I can access the underlying Danger octokit client for my own api calls. Or if this is recommended.

Thanks!

**Comment by jeroenvisser101** [comment]
Hi @wilrnh, you could do that, since the Dangerfile is just a normal ruby file.

``` ruby
require 'octokit' # not sure if this is necessary 
Octokit::Client.new(access_token: ENV['DANGER_GITHUB_API_TOKEN'])
```

**Comment by orta** [comment]
Yeah @jeroenvisser101 is correct, still not figured out a the right way to expose the environment to plugins yet.

**Comment by wilrnh** [comment]
cool. thanks guys.
