### ISSUE TITLE
Dangerfile in subdirectory

### ISSUE THREAD

**Issue by gabro** [danger/danger#219]
Hi there,
I'm trying to integrate Danger with a project of mine, which has this directory layout

```
.
├── .git
└── ios
     └── Dangerfile
```

However, this doesn't work because danger looks for a `.git` directory in the same directory of the Dangerfile.

Is it possible to customize this behavior? Or am I missing something else?

By the way, the reason behind this is that the repo is a monorepo, so the full structure looks something like this:

```
.
├── README.md
├── api
├── ios
└── web
```

And I definitely don't want to "pollute" the root directory with iOS specific files, such as the Dangerfile.

Thanks in advance!

**Comment by orta** [comment]
Danger has nothing to do with iOS, it should be put in the root of the repo.

Though I wouldn't be adverse to a PR adding support for it to work from inside a sub-folder 👍

**Comment by gabro** [comment]
> Danger has nothing to do with iOS, it should be put in the root of the repo.

fair enough. It happens to be in my use case, but I see it's not a general consideration.

> Though I wouldn't be adverse to a PR adding support for it to work from inside a sub-folder 👍

cool, I can put something together. I have a couple of approaches in mind:

- improve the `.git` folder lookup, i.e. finding the first `.git` folder "going up" in the directory tree
- allow a danger option to specify the location of the Dangerfile

@orta any thoughts / preference?

**Comment by orta** [comment]
I think you can go [one better](http://stackoverflow.com/questions/957928/is-there-a-way-to-get-the-git-root-directory-in-one-command#957978) 💃 `git rev-parse --show-toplevel` - which will work independent of folder structure 👍 

```
~/d/r/l/d/danger_plugins (plugins_everywhere_ok) ⏛  git rev-parse --show-toplevel
/Users/orta/dev/ruby/libs/danger
```

**Comment by gabro** [comment]
Right! I don't know why I hadn't thought of it. I used exactly the same approach on an internal project not later than yesterday 😅

More ☕️ then I'll work on a PR

**Comment by gabro** [comment]
@orta I tried to take a stab at this. Despite my limited ruby skills, I think the simplest modification would be to pass the result of `git rev-parse --show-toplevel` to `Git.open` in `GitRepo::diff_for_folder`.

However, if I run danger from the `ios` subdirectory (see the example tree above), ruby-git throws an `ArgumentError` exception because the path actually does not exists.

From what I've understood this happens because it doesn't have the permissions to perform the check, since we're in a subdir.

Unless you have other ideas, I think it's easier to let users specify the location of the `Dangerfile` instead.

**Comment by orta** [comment]
Yeah, that might have to be the case then 👍 - we do this for CocoaPods, so it's not an unheard of pattern
