### ISSUE TITLE
Failures should cause an exit code of not 0

### ISSUE THREAD

**Issue by orta** [danger/danger#22]
<img width="1060" alt="screen shot 2016-01-08 at 08 41 55" src="https://cloud.githubusercontent.com/assets/49038/12193911/bdb5323e-b5e3-11e5-87d4-4f132177940c.png">

> POSIX-compatible systems typically use a convention of zero for success and non zero for error

Looks like convention [is here](https://www.freebsd.org/cgi/man.cgi?query=sysexits&sektion=3) - perhaps  
`78`? - `EX_CONFIG (78)	   Something was found in an unconfigured or miscon-figured state.`

**Comment by KrauseFx** [comment]
Good question, assuming we have `.travis.yml`

```
script:
  - danger
  - bundle exec fastlane test
```

we'd still want to run the tests, right? How about we have a flag to return an exit code? Or what's the alternative way to configure travis? In any case, the README should explain how to use `danger` with Travis

**Comment by orta** [comment]
interesting, so we want to say this can fail but continue on travis

**Comment by KrauseFx** [comment]
@orta on the other hand we want to fail the Travis build if the pull request status can't be set because it's a bot account (open source), e.g. https://github.com/fastlane/fastlane_core/pull/72#issuecomment-169938700, right?

**Comment by orta** [comment]
Travis recommends using `command one && command two` for bailable build steps

https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step

**Comment by orta** [comment]
and I agree, I think this only makes sense if Danger doesn't have write access to the status API

**Comment by KrauseFx** [comment]
@orta Easy enough, `danger` should just fail the build if it can't set the build status, right?

**Comment by orta** [comment]
Only if there are errors, yeah

**Comment by KrauseFx** [comment]
And adding a flag something like `--return_status` to always get a return status

**Comment by KrauseFx** [comment]
Might be useful for some CI systems

**Comment by orta** [comment]
yeah, agree

**Comment by KrauseFx** [comment]
@orta Any ideas for a good name?

**Comment by orta** [comment]
`--exit_on_fail` ?

**Comment by orta** [comment]
We do this :+1:

**Comment by oliverguenther** [comment]
I can't see any flag that would indeed exit with nonzero suggests. Is this still missing or have I overlooked something?

**Comment by blindgaenger** [comment]
Looks like it changed to camelcase.

```
-f, --failOnErrors                        Fail if there are fails in the danger report
```
