### ISSUE TITLE
Tests fail on Ruby 2.3

### ISSUE THREAD

**Issue by justMaku** [danger/danger#230]
When running `bundle exec rake spec` using Ruby 2.3 several tests fail with error:

```
      TypeError:
        can't create instance of singleton class
```

Failing code:
```ruby
    def refresh_plugins
      plugins = ObjectSpace.each_object(Class).select { |klass| klass < Danger::Plugin }
      plugins.map do |klass|
        plugin = klass.new(self)
        # ... 
      end
    end
```

Full output:
[https://gist.github.com/justMaku/fa813c5b879efa26803188843c35cbf9](url)

**Comment by orta** [comment]
I just came to report this!

**Comment by orta** [comment]
In the meantime, check with 2.3.0, and I'll look at this later

**Comment by justMaku** [comment]
FWIW: 2.2.0 works fine.

**Comment by justMaku** [comment]
Upon investigating it further, the problem seems to be in `DangerfileMessagingPlugin`, if I comment out the import of this plugin from `dangerfile.rb` tests go a little further (but still fail)

**Comment by segiddins** [comment]
I've got a fix for this, will make a PR in a minute
