### ISSUE TITLE
Duplicate sticky entries on 0.8.x

### ISSUE THREAD

**Issue by orta** [danger/danger#244]
See: https://github.com/danger/danger/pull/241#issuecomment-223318779

![screen shot 2016-06-02 at 11 21 20 am](https://cloud.githubusercontent.com/assets/49038/15750351/257709e0-28b4-11e6-8ee2-9a32b180031a.png)

**Comment by marcelofabri** [comment]
Dupe of https://github.com/danger/danger/issues/183?

**Comment by orta** [comment]
Looks like it
