### ISSUE TITLE
Support a per-org Dangerfile via an `[org]/Danger` repo

### ISSUE THREAD

**Issue by orta** [danger/danger#249]
*Problem:* Want to run the same logic on CocoaPods, Xcodeproj, CocoaPods-Core, CocoaPods-App, [etc etc]

*Current solution:* Make a `danger-cocoapods` plugin, refactor logic into that, make each one have a `Dangerfile` that calls something to trigger shared logic.

*Proposed solution:* `bundle exec danger` && `bundle exec danger local` checks to see if there is an existing repo on the org called `Danger` e.g. `CocoaPods/Danger` - if this exists, it clones ( or uses the [import](https://github.com/danger/danger/blob/master/lib/danger/danger_core/plugins/dangerfile_import_plugin.rb#L2) features to pull in a shared `Dangerfile` and run it's logic at the same time. This means we can have org-level consistent checks without even needing to have a `Dangerfile` in the current repo. You just need to set the ENV vars and run `bundle exec danger`.

**Comment by paulofaria** [comment]
Might try this after WWDC if no one beats me to it.

**Comment by orta** [comment]
And support for danger plugins - https://github.com/danger/danger/tree/master/danger_plugins

**Comment by KrauseFx** [comment]
Working on this with https://github.com/danger/danger/pull/325 🚀

**Comment by orta** [comment]
This is in!

**Comment by KrauseFx** [comment]
Oh yeah :rocket:
