### ISSUE TITLE
Enterprise GitHub setup

### ISSUE THREAD

**Issue by lukewar** [danger/danger#253]
This is the best tool, great work!
I encountered small issue while setting it up to work with Enterprise Github instance. `README.md` states to define two variables:
- `DANGER_GITHUB_HOST`
- `DANGER_GITHUB_API_HOST`

My assumption was that bot have to contain host part of the URL. But turn out that it is only true for `DANGER_GITHUB_HOST`. Second variable is expected to have full url to the API, containing scheme and path components. 
Example of proper definition:
- `export DANGER_GITHUB_HOST=github.mycompany.com`
- `export DANGER_GITHUB_API_HOST=https://github.mycompany.com/api/v3/`

I was thinking about three ways of fixing it:
1. Build API URL using provided host.
2. Update `README.md` with setup example in order to avoid any confusion
3. Rename `DANGER_GITHUB_API_HOST` -> `DANGER_GITHUB_API_URL`

What do you think. Maybe you have better ideas. If we agree on something I can prepare a PR.

**Comment by orta** [comment]
@dbgrandi I'll let you make the call on the changes

But I'm very much a ++ on updating the README - thanks @lukewar

**Comment by dbgrandi** [comment]
@lukewar You're right, that's a confusing name.

We should definitely update the README and I'm on board with changing the name to `DANGER_GITHUB_API_URL`.

I do not know enough about the expected URL of the API vs a host in a corporate environment to say that we should automatically build the URL based on the provided host.

**Comment by lukewar** [comment]
Yeah, building it may cause too much issues.

How does switching to `DANGER_GITHUB_API_URL` going to play out with backward compatibility?

**Comment by orta** [comment]
For the moment, I'm okay with breaking things, we're not post-1 yet - just make sure there's docs i the CHANGELOG

**Comment by orta** [comment]
@lukewar if you want to make some of these changes, I'd recommend doing them sooner, I want to go post-1.0 pretty soon

**Comment by orta** [comment]
Personal note: changes will need reflecting in the docs - http://danger.systems/guides/faq.html#i-have-to-use-github-enterprise-which-is-always-outdated

**Comment by k0nserv** [comment]
We probably don't wanna make this a breaking change now, maybe just add support for `DANGER_GITHUB_API_URL` as well. For GitLab I've called this env variable `DANGER_GITLAB_API_ENDPOINT`, so maybe we should change that too before finalizing GitLab support

**Comment by k0nserv** [comment]
Closed by #448
