### ISSUE TITLE
Added / Removed files are backwards in Danger

### ISSUE THREAD

**Issue by daniel-beard** [danger/danger#262]
- I'm using a custom CI, but setting the right shell variables so that Danger thinks it's jenkins (GIT_URL & ghprbPullId)
- I also have to manually checkout the source and destination branches because the CI I'm using always builds in a detached HEAD state.
- I notice that the added files and removed files are the opposite of what they actually should be (flipped).
- Is there anything I can do to narrow down this problem and workaround?
- I'm using Danger v0.7.4  and GithubEnterprise 2.5.4

**Comment by orta** [comment]
Could be that the `danger_base` and `danger_head` are set to the opposite branches e.g. for [this PR](https://github.com/danger/danger/pull/261/commits) it goes from `768998f...b55cae2 ` instead of `b55cae2...768998f`?

**Comment by daniel-beard** [comment]
That one looks ok. 
My source branch and base branches look ok:

```
Source Branch: dbeard_add_warning_on_provisioning_profile_change
Base Branch: master
From github.groupondev.com:mobile-consumer/mobile-iphone-consumer
 * [new ref]         refs/pull/16342/merge -> danger_head
```

But the danger output shows both commits as merge commits, although they aren't:

``` 
Base Commit    | commit f5c476326ec83bdf5f1b8dfee810ceef585a3ec2                                                                                                                                                                                                                                  |
|                | Merge: 98d9740 94ba464                                                                                                                                                                                                                                                           |

<snip>                                                                                                                                                                                                           

|
| Head Commit    | commit 24fb2b9b5c03182b44a2385b1fffac0f52bd364c                                                                                                                                                                                                                                  |
|                | Merge: f5c4763 59d79da                                                                                                                                                                                                                                                           |

< snip >                                                                                                                                                                                                                                                                       

|
|                |     Merge 59d79da5ccf2ff08655daf876ee732bb7156749f into f5c476326ec83bdf5f1b8dfee810ceef585a3ec2    
```

**Comment by daniel-beard** [comment]
Looks like I'm also running into this: https://github.com/danger/danger/issues/160 my changed files list shows the last merge commit (although I have more than one commit in my open PR)

**Comment by orta** [comment]
Any chance you can give this a try on the Danger 3.x releases, there have been changes around determining which commits to use as reference points for riffing - it might have helped out here

**Comment by daniel-beard** [comment]
Started testing this again yesterday. So far it looks good, I think you can close this issue and I'll reopen if I see it again. Thanks, danger is awesome!

**Comment by orta** [comment]
👍
