### ISSUE TITLE
Update GitHub PR status does not work

### ISSUE THREAD

**Issue by valeriomazzeo** [danger/danger#264]
This method always fails because `latest_pr_commit_ref` has never been set.
Also, the generated error is absolutely misleading :(

```
def submit_pull_request_status!(warnings: nil, errors: nil, details_url: nil)
        status = (errors.count == 0 ? 'success' : 'failure')
        message = generate_github_description(warnings: warnings, errors: errors)
        client.create_status(ci_source.repo_slug, latest_pr_commit_ref, status, {
          description: message,
          context: "danger/danger",
          target_url: details_url
        })
      rescue
        # This usually means the user has no commit access to this repo
        # That's always the case for open source projects where you can only
        # use a read-only GitHub account
        if errors.count > 0
          # We need to fail the actual build here
          abort("\nDanger has failed this build. \nFound #{'error'.danger_pluralize(errors.count)} and I don't have write access to the PR set a PR status.")
        else
          puts message
        end
      end
```

I think this is very critical as it's a major loss in functionality. How come no one noticed before? : O

@orta, @KrauseFx, @segiddins

**Comment by orta** [comment]
> I think this is very critical as it's a major loss in functionality. How come no one noticed before?

Could be fallout from https://github.com/danger/danger/pull/221 ?

However this build has been out for a few hours, so please use a less accusatory tone in issues. I'm afraid I don't have time to take a look ATM, but you ( or others ) are welcome to take a quick look at fixing it.  ( And ideally adding a unit test or two so we don't regress again 👍 )

**Comment by valeriomazzeo** [comment]
Easy... I wasn't accusing anyone, just trying to help troubleshooting and pointing you guys to (possibly) the right direction.

>... How come no one noticed before?

It was more intended as: "is this not working only for me?"

I have reason to believe it wasn't working before either..

Unfortunately, I have no way to check where `latest_pr_commit_ref` was previously set without fiddling in the project history. I am not asking anyone to fix it right now, just an heads up...

**Comment by orta** [comment]
> It was more intended as: "is this not working only for me?"

Sorry, I should be assuming [more positive intent](https://github.com/CocoaPods/CocoaPods/wiki/Communication-&-Design-Rules). 

We don't realize that it was broke because most of the projects using Danger are OSS, and we cannot give build access rights to the bot. Doing so would give anyone too much access to make changes via the access token :-/ - a limitation on the access rights for OAuth on GitHub alas.

**Comment by marcelofabri** [comment]
Also, at least on my current setup, the CI provider (Jenkins) already fails the build and sets the PR status, so I wouldn't notice either 😬

**Comment by justMaku** [comment]
I'm on it. Will try to get it fixed ~soon~.

**Comment by justMaku** [comment]
It looks like it not related to #221, but #53. PR incoming.

**Comment by valeriomazzeo** [comment]
Right I see, it makes sense.

If putting danger in the script phase then it fails the build as travis (context) for example.

I was using it in the after_script so I was expecting to see travis succeeding (because of the build compiling), but then danger failing the build because of the custom rules showing the danger/danger context.

Also, I am using private repo in this case. Mistery resolved, was driving me mad 🎉

**Comment by rbuussyghin** [comment]
Similar issue #266

**Comment by justMaku** [comment]
@rbuussyghin I don't think those two are connected.

**Comment by justMaku** [comment]
Resolved in #267

**Comment by orta** [comment]
Looks like this works even when you don't give it rights to the repo 🎉 

![screen shot 2016-06-10 at 9 31 09 am](https://cloud.githubusercontent.com/assets/49038/15965822/2436fd20-2eee-11e6-9b0b-8c644d78fcfe.png)

**Comment by justMaku** [comment]
Doesn't it use the same GitHub token as the one for posting the comment?

**Comment by orta** [comment]
Yes, but when you only give it access of `public_repo`

![screen shot 2016-06-10 at 9 40 07 am](https://cloud.githubusercontent.com/assets/49038/15966060/5891faa6-2eef-11e6-97a3-c1ff8ab28882.png)

I wouldn't have expected that to have access to set the the build status
