### ISSUE TITLE
Drop support for the inherited root DSL plugins

### ISSUE THREAD

**Issue by orta** [danger/danger#273]
```
modified_files -> files.modified
added_files -> files.added
deleted_files -> files.deleted
pr_title ->  github.pr.deleted
pr_body -> github.pr.body
pr_author -> github.pr.autor
pr_label -> github.pr.label
```

Reasoning: the logical scoping means that we can expand the DSLs without introducing more special cases. This should feel better about multi-response-hosts too because BitBucket calls pull requests merge requests. So they can be added as `bitbucket.mr.body` instead of the mis-named `pr_body`. 

If it can be done without breaking support for all Dangerfile that'd be great, if it can't, I can live with that.

**Comment by orta** [comment]
Happy for discussion on whether it should be `github.pr` or just straight `pr` for example

**Comment by DanToml** [comment]
@orta I think pr would allow people to be more platform agnostic and easier to understand, but then we run the risk of still having special cases :/

**Comment by orta** [comment]
So far I've migrated them to be `git.modified_files` and `github.pr_json` etc, but still kept support for backwards compatibility, will probably pull the tfor 1.0

I think the trade off for domain specific terms is worth it, `files.commits` doesn't make sense in an SVN, or perforce environment. I think it may mean writing a bit more tests, and a bit more duplicated code maybe but for the clarity it brings in the readability, it's probably worth the tradeoff

**Comment by orta** [comment]
https://github.com/danger/danger/blob/master/dsl_docs.md has examples using the prefixing

**Comment by DanToml** [comment]
@orta Good point. 👍 for dropping.
