### ISSUE TITLE
Update README to add commits in DSL table

### ISSUE THREAD

**Issue by jamtur01** [danger/danger#280]
It'd be nice to have a DSL entry for the number of commits in a PR.

**Comment by marcelofabri** [comment]
We have a `commits` entry:
https://github.com/CocoaPods/CocoaPods/blob/master/Dangerfile#L13

It was added on https://github.com/danger/danger/pull/179 and https://github.com/danger/danger/pull/196.

We should update the README with this option.

**Comment by orta** [comment]
Ideally the README should be auto-generated from the DSL plugin, so that everything is always up to date. Similar to how gh_inspector does it https://github.com/orta/gh_inspector/blob/master/Rakefile#L18

**Comment by marcelofabri** [comment]
I'll close this since it's now in http://danger.systems/reference.html
