### ISSUE TITLE
Add a diff function for a file to the git plugin

### ISSUE THREAD

**Issue by orta** [danger/danger#282]
E.g. Allow syntax like this:

```ruby
ff files_modified.include? "Thing.xcodeproj"
  diff = git.file_diff "Thing.xcodeproj"
  fail "don't change team ID" if diff.include? "TEAM_ID"
end
```

I guess a file diff could have: 
* `before` all text that was changed
* `after` all text that was changed
* `include?` all of the text, for before and after

And then maybe expose the individual hunks if that's easily accessible?

**Comment by marcelofabri** [comment]
Implemented in #385
