### ISSUE TITLE
Runtime error: Could not find a valid pull request within the known CI sources

### ISSUE THREAD

**Issue by yimingtang** [danger/danger#290]
I'm running danger 0.8.3 in Jenkins 2.11. It works well with GitHub pull request. However, an error occurred when the CI server build regular branches (not a PR). The error log:

```
Could not find a valid pull request within the known CI sources (RuntimeError)
16:40:07 	/Users/username/.rvm/gems/ruby-2.3.1/gems/danger-0.8.3/lib/danger/danger_core/environment_manager.rb:21:in `initialize
```

After a little investigation, I found commit 2be9006647edea78ed32e6d1808b4ce71841b03b failed CISource validation early. The environment variable `ghprbPullId` doesn't exist if the build is not a PR.

My current workaround is to check if `ghprbPullId` exists before running danger, so that it won't fail the build if I put danger at the end of my building script.

**Comment by orta** [comment]
This is a not really a bug from my perspective, Danger cannot run without a PR so she calls raises an error. The idea of supporting a `--no-fail` flag has come up before - https://github.com/danger/danger/issues/117#issuecomment-194869733 and so that could be done here?

**Comment by yimingtang** [comment]
Will danger always return `passed` if I add a `--no-fail` flag? If so, it's not the behavior that I expect. My requirement is that if it's not a PR or there aren't enough environment variables, danger skips running instead of crashing the script.

Here is the result of `bundle exec danger --verbose` command run in travis-ci and that's what I want. https://travis-ci.org/danger/danger/jobs/141102875#L590

```
bundle exec danger --verbose
Not a Pull Request - skipping `danger` run
```

However, in Jenkins-CI if there are not enough environment variables (e.g. `ghprbPullId`), danger crashes before telling `Not a Pull Request - skipping `danger` run`. Because an `EnvironmentManager` object can't be initialized at the beginning of the method `run`. It raises an exception because of lack of environment variables.

Code is here:
https://github.com/danger/danger/blob/254b78975417fd3d2a03e87d956c1e20e7d61a7f/lib/danger/commands/runner.rb#L42

**Comment by orta** [comment]
`--no-fail` doesn't exist, you could build it, and it could support ^ 👍

**Comment by orta** [comment]
Correlates with #337  - which also has a potential solution

**Comment by orta** [comment]
Might be fixed as of https://github.com/danger/danger/pull/380

**Comment by yimingtang** [comment]
👍
