### ISSUE TITLE
BuildKite integration not working with latest BuildKite version when not building for pull request.

### ISSUE THREAD

**Issue by bentrengrove** [danger/danger#309]
I have just been trying to setup Danger on an iOS project that builds on BuildKite. I am not sure if this has changed recently but BuildKite seems to be setting an environment variable with BUILDKITE_PULL_REQUEST=false when the build is not the result of a pull request.

This causes Danger to try the url GET https://api.github.com/repos/.../pulls/false which results in a 404.

I am not sure if BuildKite changed recently but this occurs with the latest version of the BuildKite agent running on OSX.

**Comment by bentrengrove** [comment]
It looks as if when the build is not the result of a pull request the environment variables are as follows.

BUILDKITE_PULL_REQUEST_REPO=
BUILDKITE_PULL_REQUEST=false

When it is a pull request they are

BUILDKITE_PULL_REQUEST_REPO=git://github.com/....git
BUILDKITE_PULL_REQUEST=1

Can probably check if BUILDKITE_PULL_REQUEST_REPO is nil before proceeding.

**Comment by orta** [comment]
> Can probably check if BUILDKITE_PULL_REQUEST_REPO is nil before proceeding.

Sounds like a good idea, wanna give it a shot?

**Comment by bentrengrove** [comment]
I have given it a go!
