### ISSUE TITLE
Investigate what's going on with Danger's CHANGELOG notice

### ISSUE THREAD

**Issue by orta** [danger/danger#314]
![screen shot 2016-07-06 at 9 47 21 am](https://cloud.githubusercontent.com/assets/49038/16619994/b22fa404-435e-11e6-91be-f96fe7e94a93.png)

Could it be different build envs are returning different commit ranges?

**Comment by dzlobin** [comment]
> Could it be different build envs are returning different commit ranges?

This sounds like what I might be seeing where Danger is showing this when running on our CI, but not locally:

![](https://s3.amazonaws.com/f.cl.ly/items/01063T2q3C313e2d1R1I/Image%202016-07-06%20at%2010.09.48%20AM.png?v=718aea2a)

but the PR is only ~50 lines


![](https://s3.amazonaws.com/f.cl.ly/items/1o2b3I0X0F3u2w1P3i0j/Image%202016-07-06%20at%2010.09.39%20AM.png)

**Comment by orta** [comment]
I'd recommend running with  `--verbose` to see if anything feels out of alignment, it should echo all of Danger's internal values for this stuff 👍 

It's how I was thinking of debugging this one anyway

**Comment by dzlobin** [comment]
If only Fastlane's danger plugin respected the --verbose flag when you pass it in ^-^

**Comment by orta** [comment]
Hah - Make it do that 👯

**Comment by dzlobin** [comment]
That's the plan when I have some time in the next few days.

**Comment by marcelofabri** [comment]
@dzlobin Unless I'm misunderstanding something, it does respect: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/danger.rb#L10

**Comment by dzlobin** [comment]
@marcelofabri I actually just fixed that, complete PEBKAC error.

**Comment by dzlobin** [comment]
Also worth noting my problem above was related to #305

**Comment by orta** [comment]
I don't think this is happening anymore, at least we're not seeing on artsy or danger
