### ISSUE TITLE
Bitbucket integration

### ISSUE THREAD

**Issue by josete89** [danger/danger#315]
It's possible a bitbucket integration or is it in your roadmap?

Thanks

**Comment by justMaku** [comment]
Yes, this is definitely something we would like to have! Not many CI sources support BitBucket though, so let me know how does your setup look like :)

**Comment by orta** [comment]
There's been work on splitting out our GitHub specific code into a generic framework in #299 / #59 - you should be able to build on top of that to add bitbucket support

**Comment by k0nserv** [comment]
#299 is now in. Should be possible to use that as a template for the work that needs to be done to add support for Bitbucket

**Comment by schayes04** [comment]
It would also be great to add support for BitBucket Server for enterprise teams as well. Not sure if that would require anything additional compared to regular BitBucket

**Comment by HeEAaD** [comment]
@schayes04 I already started with Bitbucket Server / Stash support some days ago (https://github.com/HeEAaD/danger/commits/bitbucker_server). A PR will follow in the next days.

**Comment by schayes04** [comment]
Awesome. Let me know if you need help testing anything

**Comment by HeEAaD** [comment]
https://github.com/danger/danger/pull/481

**Comment by JuanitoFatas** [comment]
Now we supports [bitbucket cloud](https://github.com/danger/danger/blob/aaca6b432a0f594329382c10641a3620b0d1e317/lib/danger/request_sources/bitbucket_cloud.rb) (and [API](https://github.com/danger/danger/blob/aaca6b432a0f594329382c10641a3620b0d1e317/lib/danger/request_sources/bitbucket_cloud_api.rb)), [bitbucket server](https://github.com/danger/danger/blob/aaca6b432a0f594329382c10641a3620b0d1e317/lib/danger/request_sources/bitbucket_server.rb) (and [API](https://github.com/danger/danger/blob/aaca6b432a0f594329382c10641a3620b0d1e317/lib/danger/request_sources/bitbucket_server_api.rb)) 🎉 , close this issue ☺️ .

**Comment by fabb** [comment]
Is there documentation on how to integrate it?

**Comment by fabb** [comment]
ok found it, it's all here:
http://danger.systems/guides/getting_started.html
http://danger.systems/reference.html
