### ISSUE TITLE
@mentions in PR

### ISSUE THREAD

**Issue by jamtur01** [danger/danger#317]
I have a rule that triggers an @mention of a group:

<img width="684" alt="screenshot 2016-07-08 21 08 55" src="https://cloud.githubusercontent.com/assets/4365/16705181/8a219c58-4550-11e6-94a1-318c898a6189.png">

Note that the group is not bolded or link'ed. It does not appear to be triggering a notification. 

The `Dangerfile` code is:

```Ruby
frontend_changes = !modified_files.grep(/(frontend|app\/assets\/javascripts)/).empty?
  
if frontend_changes
  message("The frontend has been changed ... ping @kickstarter/frontend")
end
```

Am I doing something wrong here?

**Comment by orta** [comment]
Interesting - I wonder if this is based on our usage of HTML in there tableview, can you please test it with `markdown("The frontend has been changed ... ping @kickstarter/frontend")`?

**Comment by jamtur01** [comment]
@orta That works.

**Comment by orta** [comment]
OK, I think this might be worth documenting, don't _think_ this is annoying enough to warrant going back to markdown tables ( they're ugly in comparison ) so it'll need documentating somewhere

**Comment by jamtur01** [comment]
So if I want to notify folks I use `markdown('msg')` and then fail/warn etc for anything else? That seems like an okay workaround albeit a bit ... exception-y. :)
