### ISSUE TITLE
Ensure that all comments are downloaded 

### ISSUE THREAD

**Issue by orta** [danger/danger#32]
I wonder if in [this PR](https://github.com/artsy/eigen/pull/1023) Danger has paged off at 5 comments, and now continues to re-post

**Comment by KrauseFx** [comment]
Could you clarify what you mean?

**Comment by orta** [comment]
Sure, I don't know if [this line](https://github.com/KrauseFx/danger/blob/2ccaeb064a728d7874b78e6f21b6ba6502569924/lib/danger/request_sources/github.rb#L53) which grabs the comments does it via paging or not. If it does use paging, then it might only download 5 at a time for example. Then the logic about deletion / editing etc is based off bad data.

**Comment by marcelofabri** [comment]
This was fixed by #39, right?

**Comment by orta** [comment]
Yes!
