### ISSUE TITLE
\n does not work in HTML tables

### ISSUE THREAD

**Issue by DanToml** [danger/danger#321]
We should probably replace '\n' in warn/fail with `<br />` or similar?

<img width="711" alt="screen shot 2016-07-09 at 14 38 11" src="https://cloud.githubusercontent.com/assets/1330683/16709575/d563c7b2-45e2-11e6-8393-b1d252dba108.png">

https://github.com/CocoaPods/CocoaPods/pull/5607#issuecomment-231547745

**Comment by orta** [comment]
Agreed 👍 - it should

**Comment by samdmarshall** [comment]
I ran into this yesterday and was thinking shouldn't the ruby string be covered over to HTML, so it doesn't require the users to insert markdown that doesn't really represent the formatting of the string?

**Comment by orta** [comment]
Hrm, I _thought_ we did that, it's a good point.

**Comment by orta** [comment]
We don't, I wanted this and instead got this

<img width="793" alt="screen shot 2016-07-16 at 18 59 10" src="https://cloud.githubusercontent.com/assets/49038/16897709/7788a3b0-4b87-11e6-9aa0-11c1a427fd89.png">

**Comment by orta** [comment]
Or not, we have specs for this:

```
      it "some warnings with markdown, no errors" do
        warnings = violations(["a markdown [link to danger](https://github.com/danger/danger)", "second **warning**"])
        result = @g.generate_comment(warnings: warnings, errors: [], messages: [])
        # rubocop:disable Metrics/LineLength
        expect(result.gsub(/\s+/, "")).to eq(
          '<table><thead><tr><thwidth="50"></th><thwidth="100%"data-kind="Warning">2Warnings</th></tr></thead><tbody><tr><td>:warning:</td><tddata-sticky="false">amarkdown<ahref="https://github.com/danger/danger">linktodanger</a></td></tr><tr><td>:warning:</td><tddata-sticky="false">second<strong>warning</strong></td></tr></tbody></table><palign="right"data-meta="generated_by_danger">Generatedby:no_entry_sign:<ahref="http://danger.systems/">danger</a></p>'
        )
        # rubocop:enable Metrics/LineLength
      End
```

**Comment by orta** [comment]
@DanToml - I spotted that CP uses the wrong ruby string to make newlines, newlines: 

```
  fail('Please include a CHANGELOG entry to credit yourself! \nYou can find it at [CHANGELOG.md](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md).', :sticky => false)

```

**Comment by orta** [comment]
We'd have to do our own parsing here

**Comment by DanToml** [comment]
@orta Good spot! 👍
