### ISSUE TITLE
Danger doesn't fit to console

### ISSUE THREAD

**Issue by samdmarshall** [danger/danger#322]
When running `danger local` the resulting table that gets printed doesn't get fit to the current console:

<img width="906" alt="screen shot 2016-07-11 at 11 28 36" src="https://cloud.githubusercontent.com/assets/1087718/16736366/a2025a40-475a-11e6-9fda-b09b94c93696.png">

I think that danger should map to the current console width if it is in an interactive session, otherwise display at default width.

**Comment by KrauseFx** [comment]
Agreed, this would be really nice, and also something I'd like to implement in fastlane. I briefly talked with @neonichu about implementing this, maybe @neonichu might want to jump in on this? 👍

**Comment by orta** [comment]
Cork has Cork::TextWrapper - https://github.com/CocoaPods/Cork/blob/master/lib/cork/text_wrapper.rb

**Comment by KrauseFx** [comment]
@orta Yeah, but we're using `terminal-table` for printing out those big tables, so it will probably have to be a patch for the `terminal-table` library
