### ISSUE TITLE
GNU utilities are being unnecessarily used

### ISSUE THREAD

**Issue by henriwatson** [danger/danger#331]
As it stands, Danger uses the GNU utilities (mostly touch, grep, and head) in a handful of places. This makes it a bit tricky to use Danger on platforms lacking the GNU utilities (such as Windows) without resorting to messy UNIX-emulation solutions.

I don't see any reason why these calls couldn't be replaced with native Ruby methods (touch with File.open, etc) and have begun to work on this in a local fork.

@KrauseFx suggested I open an issue on this to encourage people to comment on this change, should there be any objections.

**Comment by orta** [comment]
Yeah, using `FileUtils` is cool with me 👍  - is there a good/free CI service that can run window images so we can run the test suites on it?

**Comment by segiddins** [comment]
@orta appveyor.com
I'm also happy to help move us over to ruby stuff instead of backticks

**Comment by orta** [comment]
Nice one @segiddins - I've set us up with Appveyor - https://ci.appveyor.com/project/orta/danger-47jiu

Might affect upcoming PRs so will figure that one as we come to it

**Comment by orta** [comment]
https://www.appveyor.com/docs/lang/ruby - docs on ruby

I assume we need something like:

```yaml
# appveyor.yml
install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install

build: off

test_script:
  - bundle exec rake spec
```

**Comment by orta** [comment]
Alright, that's both it working on Windows, and it staying that way via CI in #333 👍
