### ISSUE TITLE
Support Question: Should danger only be run when the build is for a pull request?

### ISSUE THREAD

**Issue by bentrengrove** [danger/danger#337]
Hey all, 

Danger is running great for us except for that now when our build server (Buildkite) runs something that is not a pull request the danger step fails.

`Could not find a valid pull request within the known CI sources`

Is this the expected behaviour? Are we only meant to run danger if we are building for a pull request?

Thanks for the help, 
Ben

**Comment by orta** [comment]
Yep, only on PRs, though ideally Buildkite would pass with a different message, depends on what CI ENV vars are available. It should say "This is not a PR, skipping".

**Comment by bentrengrove** [comment]
I think my change might have stopped it from recognising Buildkite when its not in a PR. What should I return when I can see its Buildkite but not a PR?

**Comment by orta** [comment]
Ah yeah, #310 undoes the usual behaviour of `validates` which says "this is definitely on buildkite" then `init` which determines if it is a PR. 

I wonder if it makes more sense to have two functions for all of the request sources, so instead of this:

``` ruby
      def self.validates?(env)
        return false unless env["BUILDKITE"]
        return false unless env["BUILDKITE_PULL_REQUEST_REPO"] && !env["BUILDKITE_PULL_REQUEST_REPO"].empty?
        return false unless env["BUILDKITE_PULL_REQUEST"]

        return true
      end
```

We split it into `validates_ci` and `validates_pr`:

```ruby
      def self.validates_ci?(env)
        return false unless env["BUILDKITE"]
        return true
      End

      def self.validates_pr?(env)
        return false unless env["BUILDKITE_PULL_REQUEST_REPO"] && !env["BUILDKITE_PULL_REQUEST_REPO"].empty?
        return false unless env["BUILDKITE_PULL_REQUEST"]
        return true
      End



```

**Comment by bentrengrove** [comment]
This sounds like a good idea to me, beyond my skills though. I can contribute a fix for buildkite in the meantime though if that helps?

**Comment by orta** [comment]
Both @bentrengrove  and myself put in some fixes for this which are now shipped 👍
