### ISSUE TITLE
Add support to log which commits caused which messages from danger

### ISSUE THREAD

**Issue by samdmarshall** [danger/danger#347]
I would like it if a third column could be added to the table that gets posted by danger to a PR. This third column would include the commit hash (and link to the commit diff) that caused particular messages to be written or changed in the output table. I think this information is crucial to understanding the history and evolution of the PR as time goes on. Tracking the changes and seeing what must be done to satisfy the requirements set forward by the Dangerfile should be explicitly communicated to the PR author. This may also want to have tie-ins to #346 to direct the PR author to what the line or change raised the issue up than try to stumble through the PR fixes.

What highlighted this as necessary for me was one of my PRs started without any warnings and by the time I had satisfied all the requirements I had set forth to merge it got tagged with a "Big PR" warning based on the Dangerfile. Knowing at what point this was introduced would be critical to know so I can pull in other reviewers to assist. Additionally, I have code coverage metrics and lint/formatting results get linked to in the PR message from danger. It would be nice to have these tagged with which specific commit they were done for without having to dig into the CI interface and find that association.

**Comment by orta** [comment]
Aye, works for me 👍 - would like to see it as the last column
