### ISSUE TITLE
Danger should de-duplicate identical messages/warns

### ISSUE THREAD

**Issue by dbgrandi** [danger/danger#350]
I've been using Danger to lint Localization changes in our app with something like this...

``` ruby
modified_files.grep(/Localizable.strings$/).each do |file|
  message("Localization has changed. You may need to do a translation job.")
  fail("#{file} failed to lint with plutil") unless system("plutil -lint #{file}")
end
```

This ended up creating a message for each Localization file.

We should de-duplicate messages and warnings that are exactly the same, possibly adding a number to signify it happened more than once.

e.g. "Localization has changed. You may need to do a translation job. **(4)**"

**Comment by orta** [comment]
I started agreeing, but I'm not 100% on it yet.

I think a better way to handle this is to consider the system thing something to filter out successful plist items. You could expose what files have changed here  e.g.

``` ruby
unlinted_plists = modified_files.grep(/Localizable.strings$/).reject { |file| system("plutil -lint #{file}") }
fail("#{unlinted_plists.join(", ")} failed to lint with plutil") if unlinted_plists.count > 0
```

In most de-dupe cases,  I think you're going to want to actually show some kind of value of what failed as the build is external to you - and usually hard to access.

**Comment by orta** [comment]
Pretty sure https://github.com/danger/danger/pull/941 fixed this
