### ISSUE TITLE
Add a GitHub html_link function

### ISSUE THREAD

**Issue by orta** [danger/danger#351]
Look at this example from #350 :

```ruby
unlinted_plists = modified_files.grep(/Localizable.strings$/).reject { |file| system("plutil -lint #{file}") }
fail("#{unlinted_plists.join(", ")} failed to lint with plutil") if unlinted_plists.count > 0
```

Ideally, we want to have richer fail metadata specifically around linking to files. In most of my plugins I end up [writing](https://github.com/dbgrandi/danger-prose/blob/master/lib/danger_plugin.rb#L73) something like: 

``` ruby
github_loc = "/#{current_slug}/tree/#{github.branch_for_head}/#{path}"
message << "#### [#{path}](#{github_loc})\n\n"
```

Wherein what I really want to have happen is that my path string gets replaced by a clickable URL. This makes it easier to do more with Danger.

I'd propose a new method on Danger that takes either a `to_s`, or an array of `to_s`. If it's a string it converts it straight away, if it's an array it loops through them all converting them and adds an `&` at the end.

```ruby
thing = "file.json
github.html_link thing   # -> <a href='https://github.com/danger/danger/blob/my_pr/file.json'>file.json</a>


things = ["file.json", "other.txt", "sure.md"]
github.html_link things   # -> [<a href='https://github.com/danger/danger/blob/my_pr/file.json'>file.json</a>,
<a href='https://github.com/danger/danger/blob/my_pr/other.txt'> other.txt </a> &
<a href='https://github.com/danger/danger/blob/my_pr/sure.md'> sure.md </a>]
```

Then instead I would have wrote:

```ruby
unlinted_plists = modified_files.grep(/Localizable.strings$/).reject { |file| system("plutil -lint #{file}") }
fail("#{github.html_link unlinted_plists} failed to lint with plutil") if unlinted_plists.count > 0
```

Happy to change the name, was also considering `link_to` as I think that's what Rails does?

**Comment by marcelofabri** [comment]
I've used this code before:

```ruby
def url_for_path(path)
  commit = github.head_commit
  repo = env.request_source.pr_json[:head][:repo][:html_url]
  path = "/#{path}" unless path.start_with? '/'
  url = "#{repo}/blob/#{commit}#{path}"
end
```

The nice thing is that it supports PRs from a fork as well.
