### ISSUE TITLE
[needs verification] validate the contents of a repo before using it as an organization-level Dangerfile

### ISSUE THREAD

**Issue by samdmarshall** [danger/danger#366]
Scenario: I am a user of **Danger** and have a Dangerfile in my repo `samdmarshall/pyconfig`. I want to contribute a change back to **Danger** so I fork the `danger/danger` repo to `samdmarshall/danger`. There should be some verification that this new repo `samdmarshall/danger` doesn't get consumed by **Danger** under the assumption that it is a repo I created to house an organization-level Dangerfile that should be run. 

Note: I wasn't able to create a repro case for this because I already have an organization-level Dangerfile repo created. Since I only have the one org (myself) there should be some testing done on this behavior to ensure it works correctly.

**Comment by orta** [comment]
One way to check, would be for us to do a check to se if `danger.gemspec` exists in that repo first, otherwise you're going to run our Dangerfile

**Comment by samdmarshall** [comment]
Also the case of what happens if you have multiple repos that match the name pattern of an org-level Dangerfile repo.

**Comment by orta** [comment]
You can only have one repo called `Danger` to my knowledge, I think we only specifically work with that one

**Comment by samdmarshall** [comment]
ah, you are right, for some reason i remember the guide saying that you could name the repo `danger`/`Danger`/`dangerfile`/`Dangerfile` but that isn't the case.

**Comment by ashfurrow** [comment]
I had this issue as well, where my fork of `danger/danger` to `ashfurrow/danger` was being interpreted on a personal repo to be an org-wide Dangerfile repo. Deleting my fork fixed things.
