### ISSUE TITLE
Use 100% width tables for messages 

### ISSUE THREAD

**Issue by orta** [danger/danger#37]
As of the latest build messages look like:

```  
    &nbsp; | 3 Errors
    ------------- | -----------------------------------------------------------------------------------------------------
        :no_entry_sign: | fdescribe left in tests
        :no_entry_sign: | fit left in tests
        :no_entry_sign: | Developer Specific file shouldn't be changed
 ```

    &nbsp; | 3 Errors
    ------------- | -----------------------------------------------------------------------------------------------------
        :no_entry_sign: | fdescribe left in tests
        :no_entry_sign: | fit left in tests
        :no_entry_sign: | Developer Specific file shouldn't be changed
    

This leads to ugly jagged edges on when there's errors/fails/messages. However, with some sneaky HTML skills, we can do this:

<table>
  <thead>
    <tr>
      <th width="50">&nbsp;</th>
      <th width="900">3 Errors</th>
     </tr>
  </thead>
  <tbody>
    <tr >
      <td>:no_entry_sign:</td>
      <td>fdescribe left in tests</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td>fit left in tests</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td>Developer Specific file shouldn't be changed</td>
    </tr>
  </tbody>
</table>

```
<table>
  <thead>
    <tr>
      <th width="50">&nbsp;</th>
      <th width="900">3 Errors</th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td>fdescribe left in tests</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td>fit left in tests</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td>Developer Specific file shouldn't be changed</td>
    </tr>
  </tbody>
</table>
```

The numbers, once larger than the width of the parent become relative sizes, so if github change the size of their pages, then this will handle it.

**Comment by KrauseFx** [comment]
Interesting, I like this :+1:

**Comment by orta** [comment]
Doing this removes the ability to use markdown in message https://github.com/artsy/eigen/pull/1142
