### ISSUE TITLE
run danger local against an open PR

### ISSUE THREAD

**Issue by champo** [danger/danger#370]
For development, `danger local` should be able to run against an open PR (instead of only closed). This would be really useful for testing some features, like the behaviour of sticky comments.

See https://github.com/danger/danger/pull/357#issuecomment-234779657

**Comment by orta** [comment]
Overlaps a bit with https://github.com/danger/danger/issues/368 too 👍

**Comment by JuanitoFatas** [comment]
[Shipped v3.5.1](https://github.com/danger/danger/blob/master/CHANGELOG.md#351) with `danger pr` command that can run against an open PR, please give it a try 🎉 Thanks!
