### ISSUE TITLE
Changing tags does not run CI

### ISSUE THREAD

**Issue by jankeesvw** [danger/danger#379]
On the danger site I see some examples that use labels and PR title's of a Pull Request to change the Danger status. On our project the build (Buildkite) only runs on code changes, and I can't find a way to change this.

How are you doing this? I don't see a way to make Danger run when a label is changed for instance.

**Comment by marcelofabri** [comment]
I think *most* CI providers only run when the code changes, as you said. What I do on my project is triggering a rebuild manually if needed.

**Comment by jankeesvw** [comment]
For our project a build takes about 20 minutes, so that's quite a long time. I think i'm going to put Danger in a separate build on the CI server. Thanks for the info!

**Comment by marcelofabri** [comment]
You can also have multiple instances of Danger running: http://danger.systems/guides/faq.html#multiple-dangers

That's useful if you want a quick feedback on simpler validations (PR title, etc) but still uses the output of the build to perform other validations (code with warnings, lint result, etc).
