### ISSUE TITLE
Undefined method `modified_files` error thrown running a plugin

### ISSUE THREAD

**Issue by nakiostudio** [danger/danger#398]
I've just updated **Danger** from `0.8.2` to `2.0~2.1.0` and the plugin [xcov](https://github.com/nakiostudio/danger-xcov) has started throwing the following error message:

```
[!] The exception involves the following plugins:
 -  danger-xcov
/Users/travis/build/nakiostudio/EasyPeasy/vendor/bundle/ruby/2.0.0/gems/danger-2.0.0/lib/danger/danger_core/dangerfile.rb:60:in `method_missing':  (Danger::DSLError)
[!] Invalid `Dangerfile` file: undefined method `modified_files' for #<Danger::Dangerfile:0x007feae9c56828>. Updating the Danger gem might fix the issue.
```

I get the error with both Danger `2.0.0` and `2.1.0`. Everything is fine with previous versions.

Here is the complete TravisCI log: https://travis-ci.org/nakiostudio/EasyPeasy/builds/148695232

**Comment by nakiostudio** [comment]
I will answer myself. I need to update the plugin using the `git` object instead of calling the method straight away.

**Comment by nakiostudio** [comment]
Just released danger-xcov 0.1.3 fixing this problem: https://github.com/nakiostudio/danger-xcov/pull/7

**Comment by nakiostudio** [comment]
Actually... the problem persists:

```
/Users/travis/build/nakiostudio/EasyPeasy/vendor/bundle/ruby/2.0.0/gems/danger-2.0.1/lib/danger/danger_core/dangerfile.rb:60:in `method_missing':  (Danger::DSLError)
[!] Invalid `temporary_danger.rb` file: undefined local variable or method `modified_files' for #<Danger::Dangerfile:0x007ff669c6a7c0>. Updating the Danger gem might fix the issue.
 #  from /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/d20160731-3136-1yblktt/temporary_danger.rb:4
 #  -------------------------------------------
 #  
 >  has_app_changes = !modified_files.grep(/lib/).empty?
 #  has_test_changes = !modified_files.grep(/spec/).empty?
 #  -------------------------------------------
```

https://travis-ci.org/nakiostudio/EasyPeasy/builds/148698030

**Comment by orta** [comment]
You're getting hit by https://github.com/danger/danger/issues/366 - for now, delete your Danger fork 👍

**Comment by nakiostudio** [comment]
I wouldn't never ever guess this one, thanks 👍

**Comment by orta** [comment]
Yeah, working on a fix for Danger now - I agree, I checked your dangerfile, and was like "this feels wrong"
