### ISSUE TITLE
Danger is trying to run on master

### ISSUE THREAD

**Issue by rynbyjn** [danger/danger#408]
This seems to have been introduced with v `2.1.x`. Our setup also includes having a `Dangerfile` for our organization, which is where this seems to be blowing up when trying to access `github.pr_json` or more specifically `github.pr_json[:base][:repo][:full_name]` in order to make commands through `octokit` that require a repo. It seems like the check that once printed out "Not a Pull Request - skipping `danger` run" might not be working as expected in the new versions. 

This can be temporarily fixed by locking down danger to `2.0.1`.

**Comment by orta** [comment]
What type of CI server are you using?

**Comment by rynbyjn** [comment]
Circle CI...

**Comment by orta** [comment]
Should be better in the next release due to #413
