### ISSUE TITLE
Improve Circle CI ENV Validation

### ISSUE THREAD

**Issue by DanToml** [danger/danger#410]
Currently, there are many issues caused by bad/missing data from Circle CI ENV Vars. 
For example:
- https://circleci.com/gh/samdmarshall/pyconfig/238 (rebuild success: https://circleci.com/gh/samdmarshall/pyconfig/239)
- https://github.com/danger/danger/issues/408

To at least raise better errors, we should also validate the presence of:
- `CIRCLE_PROJECT_USERNAME`
- `CIRCLE_PROJECT_REPONAME`
- `CIRCLE_CI_API_TOKEN`

We could do this in `validates_as_ci?`, `validates_as_pr?` or an extra, whole environment validation check.
I think a whole environment step would allow us to give a more detailed error (I.e 'This is a problem with the provider', vs 'This is not a pull request/not running on CI')

\c @orta

**Comment by samdmarshall** [comment]
This is still happening for me on non-PR builds and causes CI to fail consistently.

**Comment by orta** [comment]
I've not shipped a release - as  I figured we had three big PRs coming in

**Comment by samdmarshall** [comment]
Gotcha. Sorry, I should have clarified i was trying to give more information as this was previously happening on a PR branch and telling Circle to rebuild resolved it, but now it happens on primary my branch and PR branches and rebuilding doesn't resolve the issue has it previously had. I wanted to make sure those data-points were captured in this issue.

**Comment by orta** [comment]
Just shipped 2.1.2 - wanna see if that fixes it?

**Comment by samdmarshall** [comment]
After updating to 2.1.2, i stopped getting failures on my PR branches, but I am still getting failures on my primary branch: https://circleci.com/gh/samdmarshall/pyconfig/267

**Comment by rpowelll** [comment]
I can confirm I'm also still seeing failures on non-PR branches. I can't link the build output because it's from a private repo, but the `bundle exec danger` step gives the following output:

```
bundler: failed to load command: danger (/usr/local/bin/danger)
Octokit::InvalidRepository: Invalid Repository. Use user/repo format.
  /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/repository.rb:87:in `raise_invalid_repository!'
  /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/repository.rb:31:in `initialize'
  /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/repository.rb:55:in `new'
  /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/repository.rb:55:in `path'
  /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/client/pull_requests.rb:31:in `pull_request'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-2.1.2/lib/danger/request_source/github.rb:55:in `fetch_details'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-2.1.2/lib/danger/danger_core/environment_manager.rb:39:in `fill_environment_vars'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-2.1.2/lib/danger/danger_core/executor.rb:31:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-2.1.2/lib/danger/commands/runner.rb:56:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-2.1.2/bin/danger:5:in `<top (required)>'
  /usr/local/bin/danger:22:in `load'
  /usr/local/bin/danger:22:in `<top (required)>'

bundle exec danger returned exit code 1
```

**Comment by orta** [comment]
Yeah, I saw this today on #418

**Comment by orta** [comment]
There's been a lot of work on this in the 2.1.x releases

**Comment by JuanitoFatas** [comment]
Hello friends, could you try danger v3.3.1?

**Comment by rzane** [comment]
Our builds are failing on master every single time.

```
/usr/local/bundle/gems/danger-4.0.3/lib/danger/ci_source/circle.rb:82:in `initialize': Danger::Circle.rb considers this a PR, but did not get enough information to get a repo slugand PR id. (RuntimeError)

PR path: ''
Keys: ["PATH", "HOSTNAME", "TERM", "CIRCLE_BUILD_NUM", "CI", "POSTGRES_HOST", "RAILS_ENV", "CI_PULL_REQUESTS", "CIRCLE_BUILD_URL", "CI_REPORTS", "CIRCLE_SHA1", "CIRCLE_PREVIOUS_BUILD_NUM", "CIRCLECI", "CIRCLE_PROJECT_USERNAME", "CIRCLE_BUILD_IMAGE", "CIRCLE_COMPARE_URL", "CIRCLE_USERNAME", "CI_PULL_REQUEST", "CIRCLE_PROJECT_REPONAME", "CIRCLE_BRANCH", "CIRCLE_NODE_INDEX", "CIRCLE_ARTIFACTS", "DANGER_GITHUB_API_TOKEN", "CIRCLE_TEST_REPORTS", "CIRCLE_REPOSITORY_URL", "CODECLIMATE_REPO_TOKEN", "CIRCLE_NODE_TOTAL", "RUBY_MAJOR", "RUBY_VERSION", "RUBY_DOWNLOAD_SHA256", "RUBYGEMS_VERSION", "BUNDLER_VERSION", "GEM_HOME", "BUNDLE_PATH", "BUNDLE_BIN", "BUNDLE_SILENCE_ROOT_WARNING", "BUNDLE_APP_CONFIG", "NODE_VERSION", "HOME", "BUNDLE_GEMFILE", "BUNDLER_ORIG_PATH", "GEM_PATH", "BUNDLE_BIN_PATH", "RUBYOPT", "RUBYLIB", "MANPATH"]
```

**Comment by DanToml** [comment]
We recently fixed this in CircleCI, and PR associations are significantly more reliable.

**Comment by orta** [comment]
<3 33333
