### ISSUE TITLE
Proposal: Replace implicit dangerfile

### ISSUE THREAD

**Issue by orta** [danger/danger#415]
The work being discussed in #384 would mean that the implicit Dangerfile support would need to look for every type of `Dangerfile` - which isn't optimal. I propose removing that, and maybe adding another root DSL attribute:

```ruby
run_dangerfile "repo/name"
```

Would implicitly run a Dangerfile:

```ruby
run_dangerfile "repo/name", file: "Dangerfile.js"
```

Would let you define the file, if it's not a ruby one.

This is a breaking change, and requires a version bump.

**Comment by champo** [comment]
Would this need to be a breaking change? The original behaviour could be kept, only for ruby files. I'm inclined to the breaking change though, the limited behaviour would be unintuitive.

**Comment by orta** [comment]
Yeah, I think so, I know there are people using this feature in production. Plus, I'd rather be on the side of more major versions than less, realistically. 

I don't want to try and split code-paths for JS/Ruby any more than is current, making it easy to add another language option in the something I'd like to do. I was debating having the JS danger files class as a major release anyway, so the two can be "released" at the same time, even if it comes out in a patch release before, as it doesn't break things

**Comment by orta** [comment]
Alright, this is happening in #418
