### ISSUE TITLE
Invalid Repository Error

### ISSUE THREAD

**Issue by bentrengrove** [danger/danger#426]
Getting a invalid repository error (for a private repo so I can't share all the details unfortunately) when trying to run danger against a new project. Any pointers at working out what is causing this?

    /Users/StripySock/.rvm/gems/ruby-2.3.0/gems/octokit-4.3.0/lib/octokit/repository.rb:87:in `raise_invalid_repository!': Invalid Repository. Use user/repo format. (Octokit::InvalidRepository)
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/gems/octokit-4.3.0/lib/octokit/repository.rb:31:in `initialize'
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/gems/octokit-4.3.0/lib/octokit/repository.rb:55:in `new'
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/gems/octokit-4.3.0/lib/octokit/repository.rb:55:in `path'
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/gems/octokit-4.3.0/lib/octokit/client/pull_requests.rb:31:in `pull_request'
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/gems/danger-2.1.2/lib/danger/request_source/github.rb:55:in `fetch_details'
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/gems/danger-2.1.2/lib/danger/danger_core/environment_manager.rb:39:in `fill_environment_vars'
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/gems/danger-2.1.2/lib/danger/danger_core/executor.rb:31:in `run'
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/gems/danger-2.1.2/lib/danger/commands/runner.rb:56:in `run'
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/gems/danger-2.1.2/bin/danger:5:in `<top (required)>'
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/bin/danger:23:in `load'
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/bin/danger:23:in `<main>'
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/StripySock/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

The project is built on Buildkite and here is the relevant (I believe) env var.
`BUILDKITE_REPO="git@github.com:stripysock/projectname_android.git"`

**Comment by orta** [comment]
Could it be that Danger has no access to a private repo via the github token? The lookup for the repo seems fine, from the [regex](https://github.com/danger/danger/blob/master/lib/danger/ci_source/buildkite.rb#L33)

```
[3] pry(main)> a="git@github.com:stripysock/projectname_android.git"
=> "git@github.com:stripysock/projectname_android.git"
[4] pry(main)> a.match(%r{([\/:])([^\/]+\/[^\/.]+)(?:.git)?$})
=> #<MatchData ":stripysock/projectname_android.git" 1:":" 2:"stripysock/projectname_android">
[5] pry(main)> a.match(%r{([\/:])([^\/]+\/[^\/.]+)(?:.git)?$})[2]
=> "stripysock/projectname_android"
```

**Comment by cysp** [comment]
I see that kind of backtrace when Danger runs as a result of a push, not in the context of a PR.
In that scenario, `BUILDKITE_REPO` is set but `BUILDKITE_PULL_REQUEST_REPO` is the empty string.
Should `.repo_url` use the former variable? (Or perhaps fall back to it, if the latter is not useful?)
It appears that that used to be the case but was changed [here](https://github.com/danger/danger/pull/310/files#diff-f826784263ae81b08597b7bd75a090e3L16).

**Comment by orta** [comment]
ah, so the check that it is a PR [looks for](https://github.com/danger/danger/blob/master/lib/danger/ci_source/buildkite.rb#L26) the existence of `BUILDKITE_PULL_REQUEST_REPO` - it should look that it is not an empty string, wanna try fix it? Should be easy to write tests for 👍

**Comment by orta** [comment]
Done
