### ISSUE TITLE
Danger local should be able to work with remotes not named "origin"

### ISSUE THREAD

**Issue by mtitolo** [danger/danger#445]
For _reasons_, I normally don't have a remote named `origin` on my machine for a particular repository. It would be really nice to be able to pass in the name of the remote I'd like to use Danger with. This also adds the ability to run `local` against forks, without changing any git configurations.

**Comment by orta** [comment]
Local won't need this once #382 is in 👍

**Comment by JuanitoFatas** [comment]
Hello @mtitolo, could you please try the `danger pr` command [introduced in v3.5.1](https://github.com/danger/danger/blob/master/CHANGELOG.md#351)? Thanks ❤️
