### ISSUE TITLE
Introduce mr_diff for GitLab plugin

### ISSUE THREAD

**Issue by k0nserv** [danger/danger#460]
The GitHub plugin has a `pr_diff`, but for GitLab `mr_diff` isn't yet implemented. The problem we ran into with `mr_diff` is that while [GitLab's API](http://docs.gitlab.com/ce/api/merge_requests.html#get-single-mr-changes) does return the diff of an MR I am not sure it can be converted to Uniform Diff format nicely. I don't know enough about Uniformed Diff to understand if one could construct a proper diff from the output of `changes`.

Another option is to just use `data[:changes].map { |change| change[:diff] }.join("\n")` which produce a similar text blob to the Uniform Diff of GitHub.

cc @connorshea

**Comment by champo** [comment]
as far as I can see from the API example, the changes property is in an
unified diff format. Doing the join as you propose should produce a valid
unified diff!

**Comment by k0nserv** [comment]
The difference I noticed between the GitHub and GitLab formats is that the GitHub format includes lines such as

```
diff --git a/Artsy.xcodeproj/project.pbxproj b/Artsy.xcodeproj/project.pbxproj
````

Which aren't present in the GitLab responses.  I am not sure if those are required for Unified Diff format, but that was my concern

**Comment by champo** [comment]
https://en.m.wikipedia.org/wiki/Diff_utility doesn't show any of those
lines. I guess it's an extension, but not required. It can easily be added
by code if you want them to be exactly the same.

**Comment by k0nserv** [comment]
Hmm okay I am happy to do it this way then, @orta what's your take?

**Comment by orta** [comment]
Works for me, you can see if the same tests for the github one runs against the gitlab one 👍
