### ISSUE TITLE
danger local: "NoMethodError: undefined method `danger_repo?' for #<Danger"

### ISSUE THREAD

**Issue by fcy** [danger/danger#461]
I just updated to version 3.0.1 and when I tried to run `danger local` I got the following error:

>bundler: failed to load command: danger (/Users/felipe/.gem/bin/danger)
NoMethodError: undefined method `danger_repo?' for #<Danger::RequestSources::GitHub:0x007fec92bdd6d0>
  /Users/felipe/.gem/gems/danger-3.0.1/lib/danger/commands/local.rb:120:in `check_and_run_org_dangerfile'
  /Users/felipe/.gem/gems/danger-3.0.1/lib/danger/commands/local.rb:110:in `run'
  /Users/felipe/.gem/bundler/gems/CLAide-61071679fc96/lib/claide/command.rb:334:in `run'
  /Users/felipe/.gem/gems/danger-3.0.1/bin/danger:5:in `<top (required)>'
  /Users/felipe/.gem/bin/danger:23:in `load'
  /Users/felipe/.gem/bin/danger:23:in `<top (required)>'

Searching the repo for `danger_repo` there is only one place with it: [danger/local.rb:120](https://github.com/danger/danger/blob/dca99d6bed249da4ffcf359e2e34fdd61eda3a97/lib/danger/commands/local.rb#L120). Reading the CHANGELOG I noticed a breaking change on a feature that seems related to this method, is it just a forgotten call to an old feature?

**Comment by orta** [comment]
Yes! It is, looks like I missed it
