### ISSUE TITLE
Jenkins doesn't recognize PRs with Github PR builder plugin

### ISSUE THREAD

**Issue by vittoriom** [danger/danger#466]
It's my first run with `danger` so I may do something wrong, but I tried to follow the steps in the guide and ended up with `danger` skipping the build because it didn't find any PR. 
Peeking into the code I found [this](https://github.com/danger/danger/blob/57c3f78fa3560cef5df931f91230aaee50d01f5f/lib/danger/ci_source/jenkins.rb#L53) where the key should probably rather be `ghprbPullId` and not `ghprPullId` (as of [plugin doc](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin))

Can someone confirm this?

**Comment by orta** [comment]
Confirmed, when this was first created it had the `b` - https://github.com/danger/danger/commit/b873e5ddd26f69f120b5bf14758d5e93d3b27829#diff-cf6602946c8994ac9291f5e00b4d7ffbR20

**Comment by vittoriom** [comment]
Would you like me to change it back or is it something that may turn out faster for you to do?

**Comment by orta** [comment]
You can change it back, I can make a gem release, deal? I'm still in bed 👯

**Comment by vittoriom** [comment]
Deal ;) 
Here it is: #467

**Comment by k0nserv** [comment]
Thanks for resolving this, sorry about that bug

**Comment by vittoriom** [comment]
No problem, it took half an hour from issue creation to merge, and a few more minutes for the new release. Can't really complain 😄
