### ISSUE TITLE
Undefined Local Variable or method 'ci_klass'

### ISSUE THREAD

**Issue by phillfarrugia** [danger/danger#472]
I'm having issues getting danger up and running on some build machines at work. I'll attach the output I'm seeing when I run `bundle exec danger`. Apologies if this is the wrong place.|

```Moby-Dick:danger-playground bilue$ bundle exec danger
bundler: failed to load command: danger (/Users/bilue/.gem/bin/danger)
NameError: undefined local variable or method `ci_klass' for #<Danger::Executor:0x007ffd8c342538>
  /Users/bilue/.gem/gems/danger-3.0.3/lib/danger/danger_core/executor.rb:16:in `run'
  /Users/bilue/.gem/gems/danger-3.0.3/lib/danger/commands/runner.rb:56:in `run'
  /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
  /Users/bilue/.gem/gems/danger-3.0.3/bin/danger:5:in `<top (required)>'
  /Users/bilue/.gem/bin/danger:22:in `load'
  /Users/bilue/.gem/bin/danger:22:in `<top (required)>'```

Has anyone seen something similar or have I missed something obvious with my ruby setup?

Gemfile looks like this:

```
source 'https://rubygems.org'

gem 'fastlane'
gem 'danger'
```

And if it helps I'm running danger through fastlane just by simply adding the stock danger lane.

**Comment by phillfarrugia** [comment]
Oh okay, I did some investigating and I think the specific error message shown above is because happened to be running bundle exec danger manually in terminal - BUILDKITE_PULL_REQUEST wasn't set and Danger failed to handle this properly.

I think https://github.com/danger/danger/blob/5993c6e5ee987be3deb1d5bd033ef34faa4af2cf/lib/danger/danger_core/executor.rb#L16 might need improvement. I'm not very proficient in ruby, so potential not the best person to help unfortunately.

**Comment by pepibumur** [comment]
It happens to me as well when I locally without the `local` flag.
