### ISSUE TITLE
Buildkite Github Repo - 404 Not Found

### ISSUE THREAD

**Issue by phillfarrugia** [danger/danger#473]
Having another issue that is seperate to #472.

When I try and run Danger on a Pull Request from a forked Repo into the master repo, with Buildkite as a CI Source I'm getting a 404 Not found for the pull request.

![screen shot 2016-08-26 at 9 26 18 am](https://cloud.githubusercontent.com/assets/4746329/17989229/2b1b874c-6b6f-11e6-8f79-fd7bb7ec57de.png)

`GET https://api.github.com/repos/phillfarrugia/danger-playground/pulls/1`

Note that /phillfarrugia is my fork repo, not the main /bilue repo. So it seems like Danger is looking for the pull request on the fork.

I can see that https://github.com/danger/danger/blob/master/lib/danger/ci_source/buildkite.rb#L38 is using the BUILDKITE_PULL_REQUEST_REPO env variable to compile the URL to access the pull request. Which is actually the slug for the fork repo not the main repo.

Also Danger could probably handle this 404 situation a lot better. I spent a while thinking Danger was not installed/configured properly before I realised that it was actually just a Github/Buildkite setup issue.

Bare with me and I'll see if I can submit a PR that fixes the URL slug behaviour.

**Comment by phillfarrugia** [comment]
Ah I've just noticed that #310 is the reason this environment variable changed from "BUILDKITE_REPO" to "BUILDKITE_PULL_REQUEST_REPO".

I'm a bit confused by this change, as far as I can see Danger will always 404 on PRs as its trying to build the api.github.com url with the PR slug not the main repo slug. 

As opposed to just creating a PR that changes it back, I'll leave it open for discussion.

**Comment by orta** [comment]
@phillfarrugia - you're a domain expert here ( I don't use BuildKite ) if our setup for build kite repos is wrong, I'd love to get that fixed. I try to look up docs if a PR changes the ENV settings, but I'm not perfect here.
