### ISSUE TITLE
Jenkins GIT_URL environment variable is not always available

### ISSUE THREAD

**Issue by jk** [danger/danger#474]
If one configures Jenkins GitLab-plugin according to their [documentation](https://github.com/jenkinsci/gitlab-plugin/blob/master/README.md#jenkins-job-configuration) you end up with two git repositories which were merged before anything is executed in that job. One consequence of the configuration is that you do have `GIT_URL_n` (in this case `GIT_URL_1` and `GIT_URL2`) environment variables instead of just `GIT_URL`.

Problem is https://github.com/danger/danger/blob/master/lib/danger/ci_source/jenkins.rb#L45 only checks for `GIT_URL`. This should handle those `GIT_URL_n` variables as well, but I don't know which `GIT_URL_n` var is to be chosen in case there are many of them.

**Comment by jk** [comment]
I investigated some more:

* `GIT_URL_1` is same as `GIT_URL` in jenkins build job with only one git repo
* `GIT_URL_2` in case the merge request came from a fork, this is the forked repo URL

Since the gitlab-plugin documentation instructs one to add the *Merge Before Build* additional behavior it's safe to assume `GIT_URL = GIT_URL_1` (just tested that and made sure git log shows the commits from the forked repo).

So I'm doing the following workaround at the moment:
```bash
export GIT_URL=$GIT_URL_1
```

**Comment by orta** [comment]
Awesome, sounds like we could improve the [Jenkins CI](https://github.com/danger/danger/blob/master/lib/danger/ci_source/jenkins.rb#L44) url capture - wanna try give it a shot? The area is [well tested](https://github.com/danger/danger/blob/master/spec/lib/danger/ci_sources/jenkins_spec.rb) so you shouldn't be able to break anything
