### ISSUE TITLE
Allow posting comments regardless of ability to change PR status

### ISSUE THREAD

**Issue by orta** [danger/danger#48]
Currently it won't write a message. You can see it in #47

**Comment by marcelofabri** [comment]
Shouldn't be this working, since `submit_pull_request_status!` is only called as the last thing in `update_pull_request!`?

**Comment by orta** [comment]
Yeah, it is actually, turns out all of the github accounts I've been trying to use get flagged as bots. So they're actually posting messages to our threads, but GH has banned us from seeing them

**Comment by orta** [comment]
![screen shot 2016-02-13 at 08 14 12](https://cloud.githubusercontent.com/assets/49038/13026712/d24fd764-d229-11e5-8a33-8b7ced16bdb2.png)
