### ISSUE TITLE
Circle CI can sometimes create a commit build for pull requests

### ISSUE THREAD

**Issue by orta** [danger/danger#49]
This CI build https://circleci.com/gh/artsy/eigen/1501 - is attached to this PR: https://github.com/artsy/eigen/pull/1130 

![screen shot 2016-02-10 at 09 50 20](https://cloud.githubusercontent.com/assets/49038/12943819/b82f6638-cfdb-11e5-97d0-439404ae007f.png)

it shows that at the top, but the ENV vars don't reflect that that:

``` sh
Setting build environment variables
  CIRCLE_ARTIFACTS=/tmp/circle-artifacts.gyNRoD5
  CIRCLE_BRANCH=orta-dm_pilot
  CIRCLE_BUILD_NUM=1501
  CIRCLE_COMPARE_URL=https://github.com/artsy/eigen/commit/1b064fe71ac7
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_PREVIOUS_BUILD_NUM=1500
  CIRCLE_PROJECT_REPONAME=eigen
  CIRCLE_PROJECT_USERNAME=artsy
  CIRCLE_SHA1=1b064fe71ac7ec073223221889d96dcecb292000
  CIRCLE_TEST_REPORTS=/tmp/circle-junit.X2xv4ph
  CIRCLE_USERNAME=orta
```

our validation: 
``` ruby
def self.validates?(env)
  return !env["CIRCLE_BUILD_NUM"].nil? && !env["CI_PULL_REQUEST"].nil?
end
```

**Comment by marcelofabri** [comment]
We can workaround this by using Circle CI's API: https://circleci.com/api/v1/project/artsy/eigen/1501

It does return the PR:

```json
pull_request_urls":["https://github.com/artsy/eigen/pull/1130"]
```

**Comment by orta** [comment]
great investigation work :dancers:
