### ISSUE TITLE
git.modified_files also includes "renaming indicators"

### ISSUE THREAD

**Issue by daniel-beard** [danger/danger#498]
# Report
## What did you do?

Have a rule that checks for spaces in filenames:

```
# Warn on spaces in file names
####################################
files_with_spaces = git.modified_files.select { |file| (file =~ /\s/) != nil }
spaces_warning_text = ""
if files_with_spaces.length > 0 then
  spaces_warning_text += ""
  warn("Found filenames containing spaces, files should not contain spaces. See below for a list of files.", sticky: false)

  # Markdown below the list of failures
  markdown("##### Files with spaces")
  files_with_spaces.each { |file| markdown("- #{file}") }
end
```
## What did you expect to happen?

Should warn only when a file is added or modified with a space in the filename.
## What happened instead?
- Works well most of the time, I get correct warnings, but on a rename to fix the warning, modified files also includes the rename:

```
{Sub-projects/Source files => Modules/src}/UtilsTests/NSStringTemplateMakeTests.m
```
- Is there a way to only get the final filenames of modified files (without the renaming indication)?
## Your Environment

Jenkins, danger 3.1.0

**Comment by orta** [comment]
Hrm, I think we should probably do some work in Danger to convert those to be usable file paths of the after in `git.modified_files`

**Comment by orta** [comment]
https://github.com/danger/danger/pull/566 should fix this 👍

**Comment by barakwei** [comment]
I hit this problem today. Danger 4.0.4.

**Comment by daniel-beard** [comment]
thanks @barakwei, I recently ran into this issue again on version 4.2.2. @orta should there be a similar approach within Danger for `git.modified_files` ?

**Comment by orta** [comment]
I think that makes sense, please do some tests to make sure that doesn't accidentally create a breaking change for most people also :D

**Comment by barakwei** [comment]
Since the last comment i've upgraded it:
```ruby
modified_files = git.modified_files.map { |path| path.gsub(/{(.*) => (.*)}/, '\2') }
changed_files = (git.added_files + modified_files - git.deleted_files).uniq
```
Then I use `changd_files` with my plugins.

**Comment by orta** [comment]
This got updated in 5.0.0

**Comment by daniel-beard** [comment]
Thanks @orta I can confirm that this works great for me, thanks!
