### ISSUE TITLE
Confusing error when token not present

### ISSUE THREAD

**Issue by dblock** [danger/danger#519]
https://travis-ci.org/ruby-grape/grape-active_model_serializers/jobs/157378909

```
/home/travis/.rvm/gems/ruby-2.3.1/gems/danger-3.2.0/lib/danger/danger_core/environment_manager.rb:31:in `initialize': Could not find a Request Source for Danger::Travis (RuntimeError)
```

<img width="1305" alt="screen shot 2016-09-03 at 7 54 28 pm" src="https://cloud.githubusercontent.com/assets/542335/18228200/49a335e6-7210-11e6-9b4a-d2efa656973b.png">

**Comment by JuanitoFatas** [comment]
How did you know this is token not present 😅 , when token is absent, we currently [raises an error](https://github.com/danger/danger/blob/5db6ef3013d54f5cb438c3adbcffaa5e0e29518f/lib/danger/request_sources/github.rb#L45):

```ruby
raise "No API token given, please provide one using `DANGER_GITHUB_API_TOKEN`" if !@token && !support_tokenless_auth
```

**Comment by dblock** [comment]
I was moving like 100 projects to use Danger at the same time, I am sure this was the problem here ;) Check whether that check happens before the imports or something like that?

**Comment by JuanitoFatas** [comment]
Implemented in https://github.com/danger/danger/pull/579.

**Comment by JuanitoFatas** [comment]
v3.4.0 should help!
