### ISSUE TITLE
Add a table of supported Danger features

### ISSUE THREAD

**Issue by connorshea** [danger/danger#523]
Something like:

SCM             | Basic Support | Inline Comments | API Access |
------------ | -------------- | ----------------- | ----------- |
GitHub | ✅ | ✅ | ✅ 
GitHub Enterprise | ✅ | ✅ | ✅ 
GitLab.com | ✅ | 🚫 | ✅ 
GitLab CE | ✅ | 🚫 | ✅ 
GitLab EE | ✅ | 🚫 | ✅ 
Bitbucket.org | 🚫 | 🚫 | 🚫
Bitbucket Server | ✅ | 🚫 | 🚫

For a few reasons:

- So we (GitLab) know if there are missing features in the API that we should add support for.
- So users know what they can/can't do.
- So developers know what might be good things to contribute as additions.

**Comment by orta** [comment]
Agree, this is a great idea

**Comment by JuanitoFatas** [comment]
So this is actually not an issue, how about we put it in Wiki (@orta, seems disabled?) / a document in the repository? :)

**Comment by k0nserv** [comment]
Personally I dislike wikis. Putting straight into the README.md is my preference keep information in on place. Should probably also be on the website

**Comment by JuanitoFatas** [comment]
@k0nserv cool, opened an issue for the site.

@connorshea wanna add to README? :)

**Comment by connorshea** [comment]
@juanitofatas the README here or in the other project? :)

**Comment by JuanitoFatas** [comment]
Here, the other issue is to work on the http://danger.systems website 🙇

**Comment by orta** [comment]
Yeah, definitely nah to the wiki, those get out of date so easily  - I think this is fine on just the site - which I've shipped - https://github.com/danger/danger.systems/pull/111 👍
