### ISSUE TITLE
BitBucket still use branch_for_merge instead of branch_for_base

### ISSUE THREAD

**Issue by jk** [danger/danger#532]
From the `CHANGELOG.md`:

> 3.2.1:
> Deprecated branch_for_merge for GitLab. Use branch_for_base instead. - K0nserv
> …
> 3.2.0:
> bitbucket_server.branch_for_merge # The branch to which the PR is going to be merged into

For consistency we should rename `bitbucket_server.branch_for_merge` to `bitbucket_server.branch_for_base`, too.

**Comment by k0nserv** [comment]
Agreed, I didn't know it had the same mistake, of course I did advise @HeEAaD to copy the GitLab request source so it is probably on em

**Comment by JuanitoFatas** [comment]
It now named correctly:

- [dangerfile_bitbucket_cloud_plugin.rb#L106]( https://github.com/danger/danger/blob/52a51a46c5d76830c8ffcd849fe08312f9d8c617/lib/danger/danger_core/plugins/dangerfile_bitbucket_cloud_plugin.rb#L106)

- [dangerfile_bitbucket_server_plugin.rb#L106](https://github.com/danger/danger/blob/52a51a46c5d76830c8ffcd849fe08312f9d8c617/lib/danger/danger_core/plugins/dangerfile_bitbucket_server_plugin.rb#L106)
