### ISSUE TITLE
Keep GitHub releases up to date

### ISSUE THREAD

**Issue by suchow** [danger/danger#533]
# Report

## What did you do?

I went to the [GitHub releases tab](https://github.com/danger/danger/releases) for Danger.

## What did you expect to happen?

I expected to see an up-to-date list of releases.

## What happened instead?

I saw a partial and outdated list of releases:

https://www.dropbox.com/s/zh6dcsphx9hhd5s/Screenshot%202016-09-05%2014.39.47.jpg?dl=0

## Your Environment

I am using the web interface for GitHub.

## Suggested fix

I recently came across a Ruby gem, [`chandler`](https://github.com/mattbrictson/chandler), that can parse a change log & git tags and automatically populate GitHub releases. I tried it out, and it works well.

**Comment by orta** [comment]
Afraid I'd rather keep people using the CHANGELOG rather than separating that out, I thought those drafts were only available to admins - I'll remove those.

**Comment by suchow** [comment]
Okay, whatever you just did has fixed the draft display issue, so now all new releases are visible on the release page. Hurray.

(As a side note, I don't think using Chandler would change anyone's workflows or incentives. Developers would continue to update CHANGELOG.md, which is the only place to register a human-readable description of changes. When a PR is merged into master, `chandler` is run on Travis, which then updates the GitHub release page to mirror the same notes already included in the change log.)

**Comment by orta** [comment]
Interesting, yeah, that's a useful one -

**Comment by orta** [comment]
I left some notes in https://github.com/mattbrictson/chandler/issues/14 on how this could work

**Comment by orta** [comment]
Handled by #620 👍
