### ISSUE TITLE
Manage danger by GitHub Projects

### ISSUE THREAD

**Issue by JuanitoFatas** [danger/danger#548]
> Projects
> Projects utilize boards, a popular format among project management tools that supports long-term planning and easy prioritization.

> Cards
> Every Issue and Pull Request in a Project can be referenced as a card, a drag-and-droppable snapshot of the work your teams do in your repository

[<img width="1065" alt="screenshot 2016-09-15 12 52 01" src="https://cloud.githubusercontent.com/assets/1000669/18538686/3546fc86-7b43-11e6-839b-c235adc37866.png">](https://github.com/universe-2016)

[GitHub Projects](https://help.github.com/articles/about-projects/) is a new feature released yesterday, we can [create new project](https://help.github.com/articles/creating-a-project/), then [add issue / PR as boards](https://help.github.com/articles/adding-issues-and-pull-requests-to-a-project/) to the project.

**Comment by orta** [comment]
I threw some of the sort of things I'd put in a 'Proposal' issue

**Comment by orta** [comment]
But I'm not really a Kanban kind of person, best I [get is this](https://trello.com/b/J3mP1ZCV/orta-s-artsy-todo) for my work stuff.

**Comment by JuanitoFatas** [comment]
> Sure, I'm not sure what we'd manage in there yet though 👍

I'll try to create one project that I would like to tackle.

> I threw some of the sort of things I'd put in a 'Proposal' issue

Cool.

> But I'm not really a Kanban kind of person, best I get is this for my work stuff.

Your Kanban looks amazing!

--

Can use projects, close this issue.
