### ISSUE TITLE
Should `bundle exec danger` be done in every job of the build matrix?

### ISSUE THREAD

**Issue by MP0w** [danger/danger#581]
> Not an issue

Hi, I followed the documentation and added `bundle exec danger` to the script section in `travis.yml`.
However my build has 4 different jobs so danger will be executed in every job. Is this the intended behavior? Should I just run danger in one job (like I do for the code coverage report?)

Changes: https://github.com/devlucky/Kakapo/pull/120
Build example: https://travis-ci.org/devlucky/Kakapo/builds/162291803

**Comment by orta** [comment]
This is covered [in the FAQ](http://danger.systems/guides/faq.html#i-use-a-build-matrix-on-travis-can-i-run-danger-once) about build matrices 👍
