### ISSUE TITLE
Backward incompatible API in EnvironmentManager

### ISSUE THREAD

**Issue by dblock** [danger/danger#585]
Before:

```ruby
def testing_dangerfile
  env = Danger::EnvironmentManager.new(testing_env)
  Danger::Dangerfile.new(env, testing_ui)
end
```

Now:

```ruby
def testing_dangerfile
  env = Danger::EnvironmentManager.new(testing_env, testing_ui)
  Danger::Dangerfile.new(env)
end
```

Maybe make them backward compatible or document this change?

**Comment by hanneskaeufler** [comment]
Yeah that breaks testing setup for plugins ;) [Example Failed Build](https://travis-ci.org/hanneskaeufler/danger-todoist/jobs/164095489)

**Comment by orta** [comment]
Aye, will think I'll need to get around to supporting multiple inits - which is why I've left this open 👍
