### ISSUE TITLE
danger_plugin/rspec or danger_plugin-rspec?

### ISSUE THREAD

**Issue by dblock** [danger/danger#586]
How do you feel about a danger-plugin-rspec gem or about adding shared code here and having something like `require 'danger_plugin/rspec'` that would introduce a shared context for RSpec?

**Comment by dblock** [comment]
Currently having to write:

```
require 'danger_plugin'

def testing_ui
  Cork::Board.new(silent: true)
end

def testing_env
  {
    'HAS_JOSH_K_SEAL_OF_APPROVAL' => 'true',
    'TRAVIS_PULL_REQUEST' => '800',
    'TRAVIS_REPO_SLUG' => 'dblock/danger-changelog',
    'TRAVIS_COMMIT_RANGE' => '759adcbd0d8f...13c4dc8bb61d',
    'DANGER_GITHUB_API_TOKEN' => '123sbdq54erfsd3422gdfio'
  }
end

# A stubbed out Dangerfile for use in tests
def testing_dangerfile
  env = Danger::EnvironmentManager.new(testing_env, testing_ui)
  Danger::Dangerfile.new(env)
end
```

Will be:

```ruby
require 'danger_plugin/rspec'
```

**Comment by orta** [comment]
Yeah, I think that makes sense 👍

**Comment by orta** [comment]
Nah, I've thought about this more, and I'm against this, I think it complicates matters more for people writing plugins, a key part of their testing infrastructure is now hidden in another gem. 

As a part of building the tempting system I also documented every file that's included, now "this file" isn't included, and instead is hidden away.

**Comment by dblock** [comment]
Ok, global functions *are* an anti-pattern though.

**Comment by dblock** [comment]
There's also stuff like #585.

**Comment by orta** [comment]
Might make sense to add a factory method on the Dangerfile class then for creating a version that is just for tests, I was just continuing the pattern we using in cocoapods

**Comment by dblock** [comment]
That's another anti-pattern, shipping automatically required test code in non-test environments.

I think at the very least this code should be transformed into a shared context in the plugin generator, https://github.com/danger/danger-plugin-template/blob/master/spec/spec_helper.rb, I've opened https://github.com/danger/danger-plugin-template/issues/9 for that.
