### ISSUE TITLE
`danger local` ignores most arguments

### ISSUE THREAD

**Issue by hanneskaeufler** [danger/danger#593]
# Report

## What did you do?

Run `danger local --danger_id=HELLO --base=WHOPPA --head=nope`

## What did you expect to happen?

I expected to be able to change `danger local`s behaviour by passing these arguments.

## What happened instead?

The arguments appear to be ignored. I get the exact same result as when running `danger local` with no args.

## Your Environment

* Ruby 2.2.3, Danger 3.3.2

**Comment by hanneskaeufler** [comment]
Options are merged with `Runner` options [here](https://github.com/danger/danger/blob/master/lib/danger/commands/local.rb#L47), so shown in help output `danger local --help` but I don't think they are used further.

**Comment by JuanitoFatas** [comment]
> Options are merged with Runner options here, so shown in help output danger local --help but I don't think they are used further.

Sorry for the trobules there 😅 , this optons doesn't apply to `danger local`, please upgrade to v3.4.0 🙇
