### ISSUE TITLE
PR commit race condition

### ISSUE THREAD

**Issue by fwal** [danger/danger#609]
# Report
## What did you do?
Run `bundle exec danger --dangerfile=PreBuild.dangerfile --danger_id=prebuild` 
Run build scripts
Run `bundle exec danger --dangerfile=PostBuild.dangerfile --danger_id=postbuild`  

## What did you expect to happen?
Run Danger twice, one before builds scripts and one after, without problems.

## What happened instead?
The second danger crashed.
```
fatal: Not a valid branch point: '<hash>'.
fatal: ambiguous argument 'danger_head': unknown revision or path not in the working tree.
```

The `<hash>` in the error message points to a commit that was sent to the PR branch _after_ the build started and as such doesn't exist in the current build git repo when danger runs.

The following build (that's executed on the `<hash>` commit) will succeed without problem.

## Your Environment
* GitHub
* Jenkins 2.7.2
* Danger 3.3.2

**Comment by orta** [comment]
Weird, Danger [should be fetching commits](https://github.com/danger/danger/blob/master/lib/danger/request_sources/github.rb#L64) when GitHub is saying use a commit which doesn't exist in the current git repo, could that be failing somehow?

**Comment by fwal** [comment]
When trying to run the git commands locally I get:
`git rev-parse --quiet --verify <hash>` returns the hash ✅ 
`git branch test_head <hash>` gives me `fatal: Not a valid branch point:` 💀 
So that's probably what happens.

**Comment by fwal** [comment]
`git fetch` solves it

**Comment by orta** [comment]
o.0 - hrm, interesting, if you ( or anyone else who is) in  this position again, can you please try see if `-git -no-pager show <hash>` and see if that returns an empty value

We just switched from that to `rev-parse`

**Comment by fwal** [comment]
Alright, will see if I can reproduce 👍

**Comment by fwal** [comment]
`git --no-pager show <hash>` gives me `fatal: bad object` on commit that hasn't been fetched yet and the content of the commit if it has.

**Comment by fwal** [comment]
Ah now I get it. It should actually be `git rev-parse --verify --quiet "<hash>^{commit}"` otherwise it just verifies that it's a valid sha1 😆

**Comment by fwal** [comment]
So now I'm wondering; why does danger need the latest commit instead of just using the current commit?

**Comment by fwal** [comment]
Made a PR to fix this but I'm still curious about the reasoning for doing this at all :)

**Comment by orta** [comment]
> So now I'm wondering; why does danger need the latest commit instead of just using the current commit?

This is a complex problem with keeping github metadata and user metadata state in order, in the end we opted to just always rely on github metadata here - as we can have some guarantees there across all CI implmentations

**Comment by fwal** [comment]
Confirmed that the crash doesn't happen anymore with v3.4.2 🎉 
However this makes Danger report status on a **future** commit on github.

**Comment by orta** [comment]
that is probably for the better, GitHub hides comments on older commits right?

**Comment by fwal** [comment]
Don't think so but the main problem is that the status gets set on the next commit.

**Comment by orta** [comment]
That's based on the PR diff that GitHub offers via their API, [example](https://github.com/danger/danger/blob/master/spec/fixtures/github_api/inline_comments_pr_diff.diff) if that's saying that the change is related to a specific commit that's all we can work with I'm afraid

**Comment by fwal** [comment]
So user makes commit A -> build A starts
User makes commit B -> build B starts
Build A reports success -> commit B looks successfull

Not sure if this can be fixed easily and it's not really problem if the repo have other branch requirements set (which they should).

**Comment by fwal** [comment]
@orta Yeah I guessed that it was like that... I'll keep an eye out for any solutions in the future but I think that this original issue is fixed 👍
