### ISSUE TITLE
Proposal: Argument to make Danger post new comments instead of editing it's first one

### ISSUE THREAD

**Issue by bruno-rocha-movile** [danger/danger#618]
I personally don't like how multiple builds of Danger makes it edit it's first comment instead of posting new ones, because it makes the comment chain rather confusing. It's specially worse to my team since we use 'Test it!' to trigger it, so usually the comments section consist of the same guy posting 'Test it!' a few times, with a single Danger comment on the top of the chain. Visually, it doesn't look nice.. It would be really cool if it had an option to post new comments instead of editing the first one.

**Comment by orta** [comment]
That does sound like a useful option 👍

**Comment by connorshea** [comment]
@orta --immutable-comment, --static-comment, --no-modify-comments?

**Comment by orta** [comment]
`--replace-comment`?

**Comment by bruno-rocha-movile** [comment]
Since this would be a result of multiple runs of danger, perhaps `--new-comment` ?

**Comment by orta** [comment]
Hrm, if this will result in a new comment _every_ time, then we should re-use existing infrastructure - we already support a `    --danger_id=<id>                    The identifier of this Danger instance` option, so this should be `--unique-danger-id` which would create a timestamp based id, which means it will create a new comment each time

**Comment by bruno-rocha-movile** [comment]
That worked @orta ! Awesome!

I do believe this functionality needs an argument with a more obvious name though, so I'll definitely take a shot at this :)

**Comment by JuanitoFatas** [comment]
Implemented in #632.
