### ISSUE TITLE
Use a real table for showing the verbose information

### ISSUE THREAD

**Issue by orta** [danger/danger#62]
Mine is really not a good one. [Recommendations have been](https://github.com/danger/danger/pull/40#discussion-diff-52153987) the `terminal-table` gem. I'm interested in also getting Cork up and running, so we can test it outside of CP.

**Comment by marcelofabri** [comment]
Cork doesn't support tables yet, right?

**Comment by orta** [comment]
It does, `labeled` is effectively [that](https://github.com/CocoaPods/Cork/blob/master/lib/cork/board.rb#L137). But really we can't use cork until CocoaPods is using it, so I'm also happy to use terminal-table too
