### ISSUE TITLE
Convert danger pr to use arguments instead of options for the PR address

### ISSUE THREAD

**Issue by orta** [danger/danger#622]
# Report

## What did you do?

Ran `bundle exec danger pr https://github.com/artsy/eigen/pull/1899`

## What did you expect to happen?

It would run my PR. This is a breaking change, but IMO, this too new to be worth a 4.0 for ;)

## What happened instead?

![screen shot 2016-10-07 at 17 32 30](https://cloud.githubusercontent.com/assets/49038/19197889/33bc1fae-8cb4-11e6-8bbb-7636f53bbcbe.png)

## Your Environment

Just local, on 3.5.1

--- 

I also need to look into the encoding issue too, I guess maybe there's emoji in the PR or something.

**Comment by JuanitoFatas** [comment]
> I also need to look into the encoding issue too, I guess maybe there's emoji in the PR or something.

https://github.com/danger/danger/issues/409 we probably need to `force_encoding("UTF-8")` for the incoming information.
