### ISSUE TITLE
GitHub html_link doesn't allow custom text/title

### ISSUE THREAD

**Issue by notjosh** [danger/danger#633]
Hiya! I'm not sure if I'm not ~thinking with portals~ in Danger yet, or if this is actually a valid desire.

I'm working on a plugin containing a rule to verify that version numbers in a `package.json` are specified without wildcards. That part is going well!

Currently `github.html_link()` [generates the text based only on the link supplied](https://github.com/danger/danger/blob/52a51a46c5d76830c8ffcd849fe08312f9d8c617/lib/danger/danger_core/plugins/dangerfile_github_plugin.rb#L200).  Such a link might look like:

```
<a href='https://github.com/[snip]/package.json#L25'>package.json#L25</a> doesn't specify fixed version: 1.0.x.
```

I think it'd be A+ good to be able to pass in a title, so that the link looks something like:

```
<a href='https://github.com/[snip]/package.json#L25'>some-package-name</a> doesn't specify fixed version: 1.0.x.
```

Happy to do up the PR for it if it makes sense. Thoughts?

**Comment by orta** [comment]
You could post [directly on that line](https://github.com/danger/danger/blob/52a51a46c5d76830c8ffcd849fe08312f9d8c617/lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb#L42-L44) instead?

**Comment by orta** [comment]
That also leaves danger to handle it between github/gitlab etc etc

**Comment by notjosh** [comment]
Ah, duh. Great point. Thanks!
