### ISSUE TITLE
danger pr should support --dangerfile

### ISSUE THREAD

**Issue by marcelofabri** [danger/danger#637]
# Report

## What did you do?

`danger pr <PR LINK> --dangerfile SomeDangerfile`

## What did you expect to happen?

Validating against that PR with the provided Dangerfile

## What happened instead?

```
[!] Unknown option: `--dangerfile`
Did you mean: --pry?

Usage:

    $ danger pr

      Run the Dangerfile against Pull Requests (works with forks, too).

Options:

    --clear-http-cache   Clear the local http cache before running Danger locally.
    --pry                Drop into a Pry shell after evaluating the Dangerfile.
```

## Your Environment

* Which CI are you running on? My own machine
* Are you running the latest version of Danger? Yep, 3.5.3

**Comment by JuanitoFatas** [comment]
Released in [3.5.4](https://github.com/danger/danger/blob/master/CHANGELOG.md#354). :D
