### ISSUE TITLE
Idea: Move from ruby-git to rugged

### ISSUE THREAD

**Issue by JuanitoFatas** [danger/danger#639]
Replace our git-related stuff to [rugged](https://github.com/libgit2/rugged). It will be more reliable and we got full control thanks to [libgit2](https://libgit2.github.com). But it is gonna be a lot of work 😱 and some time to study how to use rugged

**Comment by marcelofabri** [comment]
I think we already been there: https://github.com/danger/danger/pull/77

**Comment by JuanitoFatas** [comment]
> I think we already been there: #77

Ahhhh thanks for the tip! So from the [history](https://github.com/danger/danger/commits/master/danger.gemspec?after=p8LI4xMXp7HbcSxQxqWV2vBxc6MrMzQ%3D), already from [Git](https://github.com/danger/danger/commit/9f07d239996c5bbf3fa7909285a381bf9460e148) -> [Rugged](https://github.com/danger/danger/commit/8cbf5038705e292c8cf7c45772dfca05d1708297) -> [Grit](https://github.com/danger/danger/commit/ec106673d3d287daa3ac63547708ee705f574131) -> [Git again](https://github.com/danger/danger/commit/c9bcc4e807596a3a917b6acf6becf4d2cff6d099).

**Comment by orta** [comment]
👯‍♂️ 👯

**Comment by orta** [comment]
I'm not _adverse to it_ BTW - we have a _lot_ more testing infrastructure in place now, so the transition is possible, think there was problems installing rugged on CIs though as it required native modules

**Comment by KrauseFx** [comment]
@orta What about 💃?

**Comment by orta** [comment]
I'm experimenting with more emojis ☠️
