### ISSUE TITLE
GitLab request source lacks new_comment parameter in update_pull_request

### ISSUE THREAD

**Issue by nikolaykasyanov** [danger/danger#648]
# Report

## What did you do?

I'm trying to setup danger to work with GitLab EE installation. However, I'm getting a crash due to lack of `new_comment` argument in [`update_pull_request`](https://github.com/danger/danger/blob/8b695e7c66de788fb020ade9206d6d4807984934/lib/danger/request_sources/gitlab.rb#L100) method of GitLab request source. Here's the [call site](https://github.com/danger/danger/blob/8b695e7c66de788fb020ade9206d6d4807984934/lib/danger/danger_core/dangerfile.rb#L247).

I'm using Fastlane to run danger and I'm faking CI environment with Fastlane. Basically my lane is just fakes environment & calls `danger(verbose: true)`.

## What did you expect to happen?

I expected comments to be posted to my MR on GitLab.

## What happened instead?

```
[!] Exit status of command 'bundle exec danger --verbose' was 1 instead of 0.
bundler: failed to load command: danger (/Users/nkasyanov/.rbenv/versions/2.3.1/bin/danger)
ArgumentError: unknown keyword: new_comment
  /Users/nkasyanov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-3.5.5/lib/danger/request_sources/gitlab.rb:100:in `update_pull_request!'
  /Users/nkasyanov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-3.5.5/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
  /Users/nkasyanov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-3.5.5/lib/danger/danger_core/dangerfile.rb:277:in `run'
  /Users/nkasyanov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-3.5.5/lib/danger/danger_core/executor.rb:27:in `run'
  /Users/nkasyanov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-3.5.5/lib/danger/commands/runner.rb:66:in `run'
  /Users/nkasyanov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /Users/nkasyanov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-3.5.5/bin/danger:5:in `<top (required)>'
  /Users/nkasyanov/.rbenv/versions/2.3.1/bin/danger:23:in `load'
  /Users/nkasyanov/.rbenv/versions/2.3.1/bin/danger:23:in `<top (required)>'
```

## Your Environment

* Which CI are you running on? — locally, faking Jenkins environment, though
* Are you running the latest version of Danger? — Yes, 3.5.5

**Comment by orta** [comment]
Looks right, you want to send us a PR adding that arg? to the gitlab provider?

**Comment by nikolaykasyanov** [comment]
@orta I'll try to make one!

**Comment by orta** [comment]
Rockin' we got instructions to [get started here](https://github.com/danger/danger#im-here-to-help-out)

**Comment by bruno-rocha-movile** [comment]
Hmmm I didn't expected that to happen, thank you!
