### ISSUE TITLE
Danger table layout 'broken' on GitHub

### ISSUE THREAD

**Issue by epologee** [danger/danger#666]
# Report

## What did you do?

I have Danger set up through Circle-CI for a couple of months now, and reporting on our private GitHub project has been great all this time. The server runs a simple `bundle exec danger`.

## What did you expect to happen?

I have a number of rules set up that check labels on the GitHub PR. They usually report merrily with the table syntax:

> ![501523374596](https://cloud.githubusercontent.com/assets/218289/20530986/83a41626-b0d5-11e6-983e-b19a9a624245.png)

## What happened instead?

Yet recently (since about a week), the markup of the report has been wonky:

> ![501523186980](https://cloud.githubusercontent.com/assets/218289/20530858/1551033c-b0d5-11e6-94f6-34a0130e8356.png)

Any ideas?

## Your Environment

* circleci.com
* Danger gem version 3.0.3
* Dangerfile:

```ruby
skips_changelog = github.pr_labels.include? "skips changelog"
has_app_changes = !git.modified_files.grep(/App/).empty?
has_app_changes ||= !git.modified_files.grep(/JediKit/).empty?
has_modified_changelog = git.modified_files.include?("CHANGELOG.md")

# Changelog entries are required for changes to main targets' files.
if has_app_changes && !skips_changelog && !has_modified_changelog
  fail("Changes to App or JediKit require a changelog-entry (unless labeled `skips changelog`)")
end

if github.pr_labels.empty?
  warn("PR lacks status labels (e.g. `work in progress: do not merge!`)")
else
  review_label_applied = github.pr_labels.include?("ready for review")
  review_label_applied ||= github.pr_labels.include?("please review me!")
  warn("PR is not yet labeled as `please review me!` or `ready for review`") if !review_label_applied
  fail("Sub-branch; rebase after parent is merged and remove label `sub-branch: rebase required!`") if github.pr_labels.include?("sub-branch: rebase required!")
end

# Don't let testing shortcuts get into master by accident
%w[App AppUITests JediKit].each do |dir|
  fail("Focused `describe`-closure detected within a spec of directory `#{dir}`") if `grep -r --include \\*.spec.swift fdescribe #{dir}/ `.length > 1
  fail("Focused `it`-closure detected within a spec of directory `#{dir}`") if `grep -r --include \\*.spec.swift fit #{dir}/ `.length > 1
  fail("`TODO` detected in directory `#{dir}`, create Jira stories instead") if `grep -r --include \\*.swift TODO #{dir}/ `.length > 1
  fail("`FIXME` detected in directory `#{dir}`, create Jira stories instead") if `grep -r --include \\*.swift TODO #{dir}/ `.length > 1
end
```

_P.S. Hope you guys aren't offended by this being PR #666_

**Comment by marcelofabri** [comment]
@epologee Please try 4.0.1. It should be fixed - see https://github.com/danger/danger/issues/663 for more info.

**Comment by epologee** [comment]
_Note to self: next time also check the closed issues!_
At least I got to submit issue #666. Thanks @marcelofabri!
