### ISSUE TITLE
Old BitBucket Server version (4.8.4) doesn't support Danger Emojis

### ISSUE THREAD

**Issue by Buju77** [danger/danger#668]
# Report

## What did you do?

Integrating Danger into our Jenkins and BitBucket Server (v4.8.4) CI environment. After successful configuration of Jenkins and BitBucket, DANGER could successful be triggered using a new Button on the PR page or when a new PR was created on BitBucket. Jenkins build job console printed that danger has been successful run.

## What did you expect to happen?

See Danger comments in the PR.

## What happened instead?

But we didn't see any comments from Danger in the PR. Adding `--verbose` when invoking Danger didn't help either. According to console output everything should be fine, but it wasn't.

So after some quick & dirty hacking & old school debugging (adding `puts` statements to `bitbucket_server_api.rb`) we finally discovered the cause.

Actually Danger wasn't printing out any errors when posting to BitBucket. We quickly added some and finally saw that we received a HTTP 500 internal server error (#669). As it turns out the Danger emojis (from #496 ) aren't supported either on older BitBucket Server versions. We had to change these emojis ([comments_helper.rb#L154](https://github.com/danger/danger/blob/master/lib/danger/helpers/comments_helper.rb#L154) and the [template emoji](https://github.com/danger/danger/blob/master/lib/danger/comment_generators/bitbucket_server.md.erb#L20)) to normal strings for our setup to work.

It seems latest BitBucket Server version 4.11.1 works fine with emojis. Atlassian seems to have fixed this issue between 4.8.4 and 4.11.

So the question is how should I approach this issue in my pull request? Should I pass in the BitBucket Server version from Jenkins into Danger using environment variable just like `DANGER_BITBUCKETSERVER_HOST`? Something like `DANGER_BITBUCKETSERVER_VERSION`? And then check if the version is below 4.11.1 and then use simple strings instead of emojis?

## Your Environment

* Which CI are you running on?
  * Jenkins v1.602
  * BitBucket Server 4.8.4
  * [Pull Request Notifier for BitBucket Plugin](https://marketplace.atlassian.com/plugins/se.bjurr.prnfs.pull-request-notifier-for-stash/server/overview) v2.34
* Are you running the latest version of Danger?
  * v4.0.1
* What is your Dangerfile?

  ```ruby
  message("Hello from Danger, pls work!!!111oneoneeleven")
  ```

**Comment by JuanitoFatas** [comment]
Please try v4.0.3, thanks!
