### ISSUE TITLE
Add label with Danger

### ISSUE THREAD

**Issue by m1guelpf** [danger/danger#673]
Is there any way to add a label using Danger.
Thank you!

**Comment by orta** [comment]
Yeah, you can use `github.api` to do anything you want, assuming the bot has access to do those things. It's an instance of client from https://github.com/octokit/octokit.rb - you could use this http://www.rubydoc.info/gems/octokit/Octokit/Client/Labels#add_labels_to_an_issue-instance_method if you wanted too swapping `Octokit` for `github.api`

**Comment by m1guelpf** [comment]
@orta I want to give a badge if there weren't errors, and another if there were.
How can I get the errors to another ruby script out of Danger?

**Comment by orta** [comment]
Hrm, I think inside the Dangerfile you could ask the `messaging` objects for it's warnings or errors, probably worth doing [this](http://danger.systems/guides/troubleshooting.html#i-want-to-be-a-danger-wizard) then looking around using the repl

**Comment by wongzigii** [comment]
Will danger plan to add such api into internal library? @orta

**Comment by orta** [comment]
Hrm, probably not - no. 

We expose the `github.api` object so people can do their own work with the GiHub API, Danger provides a read-only version of all that data in the DSL.
