### ISSUE TITLE
Danger does not have write access to the PR to set a PR status.

### ISSUE THREAD

**Issue by tbaranes** [danger/danger#675]
# Report

## What did you do?

Trying to setup Danger for IBAnimatable doing the [getting set up](https://danger.systems/guides/getting_started.html): `bundle exec danger init`

Then making a PR (https://github.com/IBAnimatable/IBAnimatable/pull/366) to see the result.

## What did you expect to happen?

A Danger report in the github PR telling me all good.. or not.

## What happened instead?

An error log in travis telling me that Danger can't make the report:

> Danger does not have write access to the PR to set a PR status.

## Your Environment

* Which CI are you running on? Travis
* Are you running the latest version of Danger? Yes
* What is your Dangerfile? [Dangerfile](https://github.com/IBAnimatable/IBAnimatable/blob/feature/danger/Dangerfile)

Pretty sure that I'm doing a stupid error, but can't find out what 😢

**Comment by orta** [comment]
This sounds like the token for the github account that should be posting messages is not working, especially if you're not seeing a comments - it's [probably this](http://danger.systems/guides/faq.html#danger-is-not-posting-to-github-prs-but-everything-looks-fine)

**Comment by tbaranes** [comment]
Doesn't seem to be that, I just logged in the bot account, there's no extra comments in the PR. 
Is there any manipulation / tests I can do?

**Comment by JuanitoFatas** [comment]
Did you set `DANGER_GITHUB_API_TOKEN` on Travis?

Then you can try if your token works with following:

```ruby
# Install Octokit gem (ruby library)
$ gem install octokit

# To enter the Ruby REPL
$ irb

# In the REPL
> require "octokit"
> client = Octokit::Client.new(access_token: "your 40-char token")
> client.create_status(
  "IBAnimatable/IBAnimatable", 
  "280cbb3d8fd10a902b5b408277633dd9e48961fc",
  "success",
  description: "Welcome to danger",
  context: "danger",
  target_url: "https://danger.systems"
)
```

If then token works, then it will set https://github.com/IBAnimatable/IBAnimatable/pull/366 status to success with a description says Welcome to danger, the details link will link to https://danger.systems. :)

**Comment by tbaranes** [comment]
> Did you set DANGER_GITHUB_API_TOKEN on Travis?

Yeah, I checked a few times and even generate a new one before posting here 🤓

When I used your code in the REPL, I got a 404, but when trying to paste in the navigator it's has an json as output. Does that mean the issue is from the token? 🤔

```
Octokit::NotFound: POST https://api.github.com/repos/IBAnimatable/IBAnimatable/statuses/280cbb3d8fd10a902b5b408277633dd9e48961fc: 404 - Not Found // See: https://developer.github.com/v3
	from /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete'
	from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/response.rb:9:in `block in call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/response.rb:61:in `on_complete'
	from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/response.rb:8:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/connection.rb:377:in `run_request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.10.0/lib/faraday/connection.rb:177:in `post'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/connection.rb:28:in `post'
	from /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/client/statuses.rb:43:in `create_status'
	from (irb):17
	from /usr/local/bin/irb:11:in `<main>'
```

**Comment by JuanitoFatas** [comment]
Did you give the token public_repo access? 🤔 

https://github.com/settings/tokens/new 

<img width="558" alt="screen shot 2016-12-08 at 00 02 36" src="https://cloud.githubusercontent.com/assets/1000669/20972870/a77d46a2-bcd9-11e6-88cb-22cbdd40e9c8.png">

How about you consult `support@github.com` to see if anything goes wrong? Thank you so much!

**Comment by tbaranes** [comment]
Thanks for your quick answers 🎉

Yeah, I have even tried to give it more access, but nothing changed... Consulting github is a good idea, I will keep you in touch!

**Comment by tbaranes** [comment]
> The reason why that POST request is failing is that the user for which you created the token (IBAnimatableBot) doesn't have write permissions to the repository in question (IBAnimatable/IBAnimatable). The user needs to have write permissions in order to create statuses. You're able to fetch statuses because fetching them requires read permissions only, and since it's a public repository -- everyone has read permissions.

Here the intestering part of their answer! I didn't test it yet (will do tomorrow), but I think I read in the danger FAQ / setup that we shouldn't add the bot the repository (when the repository is public), does that seems normal to you?

**Comment by tbaranes** [comment]
Good news! Giving write access to `IBAnimatableBot` by adding it to the repository works (using REPL). I'm letting that issue open for one more question, is that the normal?

**Comment by orta** [comment]
Looking at the PR, it looks like you never set the Dangerfile to say anything? So you never tested the important part which is communicating on the issue.

Well, generally speaking setting the status is unimportant ( it only adds an indicator at the bottom of a PR ) which is why we don't fail when that request fails. It's a nicety we do if we can.

IMO you should remove the bot from your org, and revoke that token, for OSS projects - anyone could use it to make any changes to all projects in that org now. 

Test that Danger works by making her say something 👍 

Perhaps we should add something in the FAQ about that, something like 

> ### Why am I seeing "set Status Failed" on my GitHub OSS project

> Because we recommend not adding your bot to your OSS project, Danger will not be able to post status updates on a PR. A status update is the green/red/yellow dots at the end of your PR page. This does not affect Danger's ability to comment, and fail your CI build, so you are fine to ignore the message.

**Comment by tbaranes** [comment]
I see, I didn't get the difference between posting the comment and posting the statuses. Also, I was thinking that Danger will always trigger something even if everything there's no error (don't know why I suppose that).

I try it again following your comments, and everything is now working as expected! The bot is not a member anymore, CI failed, and Danger give me a warning 🎉
So, there's was no issue from the beginning, just a misunderstanding of the expected behaviour.

Add that to the FAQ is definitely worth it, pretty sure that will help anyone who is started 😬

@orta @JuanitoFatas Thanks a lot for the explanations and help! I have now a better understanding of Danger (and github API).

💯

**Comment by orta** [comment]
rock

**Comment by JakeLin** [comment]
You guys rock, thank you very much for your help and super quick response 👍👍👍

**Comment by orta** [comment]
I added the note to troubleshooting too, on the website - thanks for bringing it to us so that others will be unblocked

**Comment by hamzazaidi99** [comment]
I am getting the following message when running the danger ci command
```
Request failed [401]: https://api.github.com/repos/test/web-angular/pulls/4
Response: {
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
```
