### ISSUE TITLE
https://danger.systems/: Cert date invalid

### ISSUE THREAD

**Issue by ge-fa** [danger/danger#677]
Hi,

Not sure if you're aware of this already, but thought it's better to leave a short note here: The cert used on your website is out of date.

All the best,
Georg

**Comment by orta** [comment]
thanks, dupe of https://gitlab.com/danger-systems/danger.systems/issues/108

**Comment by JLLeitschuh** [comment]
Still be broke.
http://danger.systems works fine though.
Consider changing the link on the repo title bar till this is fixed?

**Comment by JuanitoFatas** [comment]
> Still be broke.
> http://danger.systems works fine though.
> Consider changing the link on the repo title bar till this is fixed?

Changed, thank you! <3
