### ISSUE TITLE
Check number of commits?

### ISSUE THREAD

**Issue by m1guelpf** [danger/danger#679]
I want to alert the user if he hasn't squashed all the commits, but I can't find a way to check the number of commits.
Help?

**Comment by orta** [comment]
Did you look into `git.commits`?

**Comment by m1guelpf** [comment]
@orta Git.commits returns commit data, not the number.
Can you help processing that?

**Comment by JuanitoFatas** [comment]
Is this what you want?

```ruby
if git.commits.size == 1
  warn("Please squash all commits")
end
```

Also GitHub recently released a feature: [squash and merge](https://github.com/blog/2141-squash-your-commits) can also help with this.

Hope this helps.

**Comment by m1guelpf** [comment]
@JuanitoFatas That code triggers when there is only one commit or where there is more that one?

**Comment by JuanitoFatas** [comment]
> @JuanitoFatas That code triggers when there is only one commit or where there is more that one

Sorry I mean `if git.commits.size >= 1`.
