### ISSUE TITLE
Danger's diff strategy is confusing compared to the GH visual web diff

### ISSUE THREAD

**Issue by orta** [danger/danger#68]
Say I had three commits. 

* I wrote some app code
* I `git pull origin master`
* I wrote some more app code

but I never added a changelog entry.

If the `pull` contained a changelog entry, it would show up as a file in Danger, but not in the GH UI.

**Comment by marcelofabri** [comment]
Maybe the same problem as https://github.com/schacon/ruby-git/issues/23?

**Comment by orta** [comment]
We should move to https://github.com/libgit2/rugged - ruby-git was deprecated for https://github.com/mojombo/grit which was deprecated for rugged

**Comment by orta** [comment]
I think #88 better covers the problem now. Given that we use grit - which seems to give us enough power to fix this.
