### ISSUE TITLE
import_plugin should be smarter

### ISSUE THREAD

**Issue by rzane** [danger/danger#682]
# Report

## What did you do?

I have two files:

+ `a_plugin.rb`
+ `b_plugin.rb`
+ `abstract_plugin.rb`

`a_plugin.rb` and `b_plugin.rb` require and inherit from `abstract_plugin.rb`.

In my Dangerfile, I call `danger.import_plugin 'a_plugin.rb'`.

## What did you expect to happen?

I certainly did not expect it to try and understand Ruby's inheritance using a regular expression 😄 

## What happened instead?

Danger tries to check if the file is defining a plugin using a regular expression. The regular expression checks for `< Plugin`. This seems naive to me, especially in a language that encourages OO such as Ruby.

If the file doesn't contain `< Plugin`, Danger throws an error.

## Proposal

Danger should not try to parse Ruby using a regular expression.

```ruby
Dir.glob(path).inject(Danger::Plugin.length) do |plugin_count, file|
  require path
  raise "Expected to find a plugin at #{path}" if plugin_count == Danger::Plugin.length
  plugin_count + 1
end
```

I also don't think Danger should be requiring that plugins inherit from Danger::Plugin. Duck typing is a key component of Ruby. If it quacks like a Danger plugin, why should Danger about inheritance?

**Comment by JuanitoFatas** [comment]
The proposal looks good, would you like to submit a PR? 😊

**Comment by rzane** [comment]
Sure no problem!
