### ISSUE TITLE
Support for BuddyBuild CI

### ISSUE THREAD

**Issue by timbroder** [danger/danger#695]
[BuddyBuild](https://www.buddybuild.com/ "BuddyBuild") (so far) "just works" even though there isn't a [ci_source](https://github.com/danger/danger/tree/master/lib/danger/ci_source "ci_source") for it

I can take a stab at adding proper support for it if no one else has taken it. 

BB looks like it [exposes](http://docs.buddybuild.com/v6/docs/custom-prebuild-and-postbuild-steps "exposes") ```BUDDYBUILD_BUILD_NUMBER``` which can be used to ```validates_as_ci``` and ```BUDDYBUILD_TRIGGERED_BY``` which can be inspected to ```validates_as_pr```

Can I take this?

Thanks!

**Comment by orta** [comment]
Awesome, yeah, seems totally 👍

**Comment by timbroder** [comment]
Great, and to confirm that this would be part of danger, not a plugin correct? Because the documentation looks in [this](https://gitlab.com/danger-systems/danger.systems/blob/master/static/source/guides/getting_started.html.slim#L171 "this") directory?

Also, what is the best way to test this on the CI itself without publishing a gem for it to install? I can mimic the env variables locally, but for a final test

**Comment by orta** [comment]
Nah, you just want to copy one of these: https://github.com/danger/danger/tree/master/lib/danger/ci_source

And the same for it's tests, and change the ENV vars etc. Think that should be it  👍

**Comment by pabloelizalde** [comment]
Hi guys, I have been taking a look to integrate Danger with buddybuild CI. As you said, there is no ci_source for it. I have created a my own [buddybuild.rb](https://gist.github.com/pabloelizalde/c5fa9938a9e2980be8888016e19945af) based on the other examples. My first problem is that I am missing some environment vars like "BUDDYBUILD_PULL_REQUEST_ID". Should I add this ENV var in the [buddybuild_postclose.sh](http://docs.buddybuild.com/v6/docs/custom-prebuild-and-postbuild-steps#section-post-clone)?
If this buddybuild.rb is correct, I can do a PR, but how can I test this before getting merged? 
Thanks

**Comment by orta** [comment]
You'll need to make sure the ENV VARs are available, you may need to request that from Buddy Build, Danger won't be able to figure out where to look for the code without them.

Once those are set up, you can verify it by using a Gemfile on a buddy build project to refer to your fork of Danger in your project. 👍

**Comment by pabloelizalde** [comment]
Thanks for the quick reply.
We were in contact with buddybuild, and looks like they have an early version of automatic Danger support. So there is no need to create ENV VARs anymore, and no need to include a script to run the commands `bundle install` and `bundle exec danger`.

**Comment by orta** [comment]
Great!

**Comment by timbroder** [comment]
@pabloelizalde thanks for hopping on this ticket! I haven't had time to properly turn attention to it yet

If you want another set of eyes on it or another buddybuild instance to test on let me know!

**Comment by timbroder** [comment]
@pabloelizalde I have some time tomorrow and Monday I can dedicate to working on this. Checking in to see if your work is viable or if I should start fresh? Thanks!

**Comment by pabloelizalde** [comment]
@timbroder I would say contact buddybuild first. They were able to build our projects with Danger support directly. So I didn't have to include any ENV var or modify any script. Good luck!

**Comment by garnett** [comment]
@timbroder please share your findings if you contact Buddybuild as @pabloelizalde suggests.

**Comment by timbroder** [comment]
@pabloelizalde @garnett have reached out. Will do!

**Comment by timbroder** [comment]
From BuddyBuild:

> Hi there!
> Yes buddybuild supports Danger natively. As long as your repository contains a Dangerfile and a Gemfile, then buddybuild will run your Danger step automatically after the build.
> Richard

@orta where is the best place to mention this in the documentation? It [looks](https://gitlab.com/danger-systems/danger.systems/blob/master/static/source/guides/getting_started.html.slim#L171 "looks") like the site pulls from ci_source. Should I add a skeleton one for BuddyBuild or something else?

**Comment by orta** [comment]
This was added in #761 👍

**Comment by milind-mevada-stl** [comment]
I've setup buddyBuild as ci for my Github OSS project.
As per @pabloelizalde comments. We do not need to add `.sh` file commands.
For me I've added Gemfile and Danger file to my repo itself. But somehow it doesn't invokes. 
Danger is working correct locally.
Can anyone help? What is mistake in my flow. And also please let me know which are  ENV varibles. I'll require to add to BuddyBuild. 
I've added my DANGER_GITHUB_API_TOKEN to BuddyBuild.
