### ISSUE TITLE
Make 'Get started tutorial' easier to understand

### ISSUE THREAD

**Issue by RishabhTayal** [danger/danger#696]
Trying to follow the first time tutorial on [get started](https://danger.systems/guides/getting_started.html). The instructions are clear until [Creating a bot account](https://danger.systems/guides/getting_started.html#creating-a-bot-account-for-danger-to-use). I have a individual account on GitHub. How do I create a bot account? Do I need to create a new account for bot with a new email address or is there a setting in my individual account to create a bot user?

**Comment by orta** [comment]
Hi, I don't think we should take you through step by step on how to create an account on GitHub/GitLab or BitBucket - that is generally pretty obvious and when we do it, it will be out of date very quickly. 

I also don't want to be updating these guides whenever one of these providers update their login screens. 

Do you feel like 

>  This is a regular GitHub account

Didn't give across the idea that it was a non-org account? There are not GitHub bot accounts, only organizations and users.

**Comment by RishabhTayal** [comment]
I do think that "This is a regular Github account" is misleading. Also, it doesn't make it clear that we need to make a new account as a "bot". How does the bot account connects with the individual account repo?

Regards,
Rishabh Tayal
rtayal11@gmail.com

**Comment by orta** [comment]
There is no such thing as a bot account, you're creating an account to use as the bot, it is the individual account

**Comment by orta** [comment]
I don't think this need more improvement unless we can find specific instances of where this can be misleading, closing for now.
