### ISSUE TITLE
Reduce horizontal size of github.review docs

### ISSUE THREAD

**Issue by orta** [danger/danger#706]
## What did you do?

Read the web page: http://danger.systems/reference.html

## What did you expect to happen?

Looked 👌 

## What happened instead?

This is the worst case:

![screen shot 2017-01-26 at 11 24 21 am](https://cloud.githubusercontent.com/assets/49038/22340057/21b2a096-e3ba-11e6-97a9-dace094673b2.png)

## Fix

Need to think of a shorter way of describing the functions, maybe just do "message" instead of real world cases.

**Comment by Antondomashnev** [comment]
@orta to my mind "message placeholder" would be enough.
