### ISSUE TITLE
Capitalize Danger in Comment Generator

### ISSUE THREAD

**Issue by stefanp312** [danger/danger#709]
# Report
```
<p align="right" data-meta="generated_by_<%= @danger_id %>">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>
```

Link to file:
https://github.com/danger/danger/blob/0c299358ac6ae4b2abe5444a4ddd87accf0827f4/lib/danger/comment_generators/github.md.erb

The current code doesn't capitalize **Danger** instead it is danger.

**Comment by hanneskaeufler** [comment]
Fixed in #710
