### ISSUE TITLE
Danger does not have write access to the PR to set a PR status

### ISSUE THREAD

**Issue by onmyway133** [danger/danger#720]
I'm trying to add Danger to my repo https://travis-ci.org/onmyway133/Omnia. It seems to work fine https://github.com/onmyway133/Omnia/pull/2

But on Travis, it says "Danger does not have write access to the PR to set a PR status."
Trivial question, but how can I enable the PR access?

**Comment by orta** [comment]
http://danger.systems/guides/faq.html#why-am-i-seeing-quot-set-status-failed-quot-on-my-github-oss-project 👍
