### ISSUE TITLE
Linked files

### ISSUE THREAD

**Issue by KrauseFx** [danger/danger#73]
```ruby
dependency(changed: "**/*.gemspec", requires: "./lib/danger/version.rb")
```

**Comment by orta** [comment]
I think this should return a bool, but I'm open to a closure too:

``` ruby 
if dependency(changed: "**/*.gemspec", requires: "./lib/danger/version.rb")
  fail "Change the version, if you're changing the gem spec" 
end
```

or

``` ruby
dependency(changed: "**/*.gemspec", requires: "./lib/danger/version.rb") {
  fail "Change the version, if you're changing the gem spec" 
}

```

**Comment by jeroenvisser101** [comment]
> if dependency(changed: "**/*.gemspec", requires: "./lib/danger/version.rb")
>   fail "Change the version, if you're changing the gem spec" 
> end

That seems to match the style of the rest of the DSL the most

**Comment by orta** [comment]
:+1: lets do that then

**Comment by orta** [comment]
We have this as a plugin for Danger, I'm pretty happy with this as not being in core, I've barely used it - closing.
