### ISSUE TITLE
Support for only show message in diff

### ISSUE THREAD

**Issue by leonhartX** [danger/danger#742]
Hi  there, currently the `inline comment` will try to set message directly to the line in diff, when it's out of the diff's range, goes back to a comment.
But sometimes I just want to let them show in diff, when out of range, it means we don't care them in this pull request.(something like `swiftlint`).

I'm trying to work on this, add an option like `strict_inline` to the message plugin. 
Any ideas about this?

**Comment by orta** [comment]
I think the API specifically does not allow this, which is why we have to do such a weird dance around putting it in the main message

**Comment by leonhartX** [comment]
yes, so can we have an option to ignore those out-of-diff messages when they are out-of-my-concern too, like i don't want the whole file's lint violations result but only in my changes?

**Comment by orta** [comment]
oh, I see, interesting. 

I can see a case when you still have a lot of ignored warnings that could be outside of that range. Sure, I think that makes sense as an option on messaging, perhaps `messaging.dismiss_out_of_range_violations = true` ? yeah, it's verbose, but it makes it very obvious

**Comment by manicmaniac** [comment]
Fixed in https://github.com/danger/danger/pull/747
