### ISSUE TITLE
How to secure DANGER_GITHUB_API_TOKEN?

### ISSUE THREAD

**Issue by php-coder** [danger/danger#754]
Quote from http://danger.systems/guides/getting_started.html:
>Token Setup
> You need to add the DANGER_GITHUB_API_TOKEN environment variable, to do this, go to your repo's settings, which should look like: https://travis-ci.org/[user]/[repo]/settings.
> If you have an open source project, you should ensure "Display value in build log" enabled, so that PRs from forks work.

As far I understand it's totally insecure because my token will be visible to all and they can use it to publish messages from behalf of me.

Questions:
1) why do we have this restriction? Could we remove it somehow?
2) what is the alternative approach to now expose this token? If it exists I'd like to have it documented.

**Comment by orta** [comment]
You need to provide a GitHub API token somehow to Danger. ENV vars are the only real option. The guide talks about the trade-offs. 

[Peril](https://github.com/danger/peril) doesn't have this issue, but isn't ready for usage from people not willing to be involved in the codebase.

**Comment by php-coder** [comment]
And we can't use secure environment variables? Is it because they aren't available for pull requests?

**Comment by orta** [comment]
As the docs say, it's so that PRs from external forks work. So you can make same repo PRs and Danger will be able to see the ENV var, but not for forks.
