### ISSUE TITLE
Unable to post comments back to PR

### ISSUE THREAD

**Issue by samdmarshall** [danger/danger#756]
# Report

## What did you do?

Ran `bundle exec danger --verbose`
 
## What did you expect to happen?
Post results back to PR.

## What happened instead?

```
Octokit::UnprocessableEntity: POST https://github.mlbam.net/api/v3/repos/mobile-jenkins/iOS-Build/issues/17/comments: 422 - Validation Failed
Error summary:
  resource: IssueComment
  code: custom
  field: body
  message: body is too long (maximum is 65536 characters) // See: https://developer.github.com/enterprise/2.7/v3/issues/comments/#create-a-comment
  /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete'
  /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
  /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
  /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
  /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
  /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
  /usr/local/lib/ruby/gems/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
  /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/connection.rb:28:in `post'
  /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/client/issues.rb:279:in `add_comment'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.3.0/lib/danger/request_sources/github/github.rb:177:in `update_pull_request!'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.3.0/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.3.0/lib/danger/danger_core/dangerfile.rb:277:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.3.0/lib/danger/danger_core/executor.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.3.0/lib/danger/commands/runner.rb:66:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.3.0/bin/danger:5:in `<top (required)>'
  /usr/local/bin/danger:22:in `load'
  /usr/local/bin/danger:22:in `<top (required)>'bundler: failed to load command: danger (/usr/local/bin/danger)
```

## Your Environment

* Which CI are you running on?
  * jenkins
* Are you running the latest version of Danger?
  * Yes? `4.3.0`
* What is your Dangerfile?

  ```ruby
  rubocop.lint Dir.glob("**/*.rb")
  ```

## Additional Info
This seems to be related to #424, but rubocop posts back in markdown which seems to be the root cause of the problem here, the table getting posted back is too large to fit into the comment.

**Comment by orta** [comment]
ah, this makes sense

**Comment by samdmarshall** [comment]
Is there anything I can do to help move this along? I would like to close out some internal tracking related to this issue. If someone can point me at the relevant code I can put up a PR for it myself (i think).

**Comment by orta** [comment]
The text cap for an issue happens in here for a table: https://github.com/danger/danger/blob/master/lib/danger/helpers/find_max_num_violations.rb

But I think for this, you'll need to cap the entire comment - which is [generated here](https://github.com/danger/danger/blob/master/lib/danger/helpers/comments_helper.rb#L79-L92) - perhaps reduce the max_num_violations to 55_000 and cap the template completely at 65k?

**Comment by samdmarshall** [comment]
Ace, thanks @orta.

**Comment by samdmarshall** [comment]
Ok I had some time to look at this over the weekend and i'm wondering if this is the correct approach. I feel danger should buffer and manage output of the results automatically against the GitHub API. I can foresee a fix for this particular issue going in but still not correctly handling the case of what happens with joint output of Markdown and messages/warnings/errors where the total goes over the character limit?

Patching in multiple places doesn't seem ideal or a long-term solution here.

**Comment by orta** [comment]
I guess the problem is twofold from my perspective, 

- 1: you don't want to have to chop the table mid-way through something resulting in malford html/commonmark
- 2: there is a  max char limit on a github comment

I think we currently do 1, but we don't do 2 and that's really where the problem lays

**Comment by samdmarshall** [comment]
yeah, which is why i'm thinking that every time you submit something to the `markdown` api call, it gets separately packaged up, similarly to how `message` or `warn` or `fail` works (except without the formatting). This way it would be on the plugin writers to provide a safe and correct way to enclose their output in the case it needs to be truncated due to the API limit.

**Comment by orta** [comment]
It leaves for the question of "my one markdown is longer than a GH comment" but most cases it'll be better, I imagine, also anything that long should probably be moving into the `file: line:` api ideally.

**Comment by samdmarshall** [comment]
yeah, it would also encourage people to not create massive blocks of markdown, but smaller and more actionable results (which generally should be translatable to the `file: line: ` api as you mentioned). that seems like a better way to approach this in my mind, as it seems like danger intentionally gives you small actionable items to address ("don't worry, everything is fixable").
