### ISSUE TITLE
Why danger is cloning my repo?

### ISSUE THREAD

**Issue by php-coder** [danger/danger#760]
I see the following in my TravisCI report:

```
remote: Counting objects: 29182, done.
remote: Compressing objects: 100% (7529/7529), done.
remote: Total 29182 (delta 16227), reused 28969 (delta 16016), pack-reused 0
Receiving objects: 100% (29182/29182), 15.27 MiB | 15.72 MiB/s, done.
Resolving deltas: 100% (16227/16227), completed with 162 local objects.
From https://github.com/php-coder/mystamps
 * [new tag]         0.1        -> 0.1
 * [new tag]         0.1.1      -> 0.1.1
 * [new tag]         0.1.2      -> 0.1.2
 * [new tag]         0.1.3      -> 0.1.3
 * [new tag]         0.2        -> 0.2
 * [new tag]         0.3        -> 0.3
Danger has failed this build. 
Found 19 errors.
```
Is it possible that danger clones my repository? For what?

**Comment by orta** [comment]
If Danger cannot find the start and the beginning of the PR in your commit history, she'll fill it out by fetching the rest.

**Comment by php-coder** [comment]
But why it fetches all my tags? Is it really necessary?

**Comment by orta** [comment]
I think it's just a fetch, a tag is basically a single reference to a SHA, it probably just comes along for the ride.

**Comment by php-coder** [comment]
Could you improve this message by printing what/why she is doing? Maybe only in verbose mode. Also it's better to hide this git output by default.

**Comment by php-coder** [comment]
> Danger has failed this build. 
> Found 19 errors.

Behavior behind this message is a bit weird: https://github.com/danger/danger/blob/76ee6308a8920530460e93ffa038eaf748ff1331/lib/danger/request_sources/github/github.rb#L200-L222

When danger fails to update status, she doesn't mention about this fact at all if there are some errors.

**Comment by orta** [comment]
PRs are welcome 👍
