### ISSUE TITLE
When Dangerfile eval fails comment on the issue with the stack + error

### ISSUE THREAD

**Issue by orta** [danger/danger#767]
Ruby version of https://github.com/danger/danger-js/issues/185

**Comment by sleekybadger** [comment]
Hi @orta. Thank you for such great project. Here [PR](https://github.com/danger/danger/pull/809) to close this.

**Comment by orta** [comment]
Thanks a lot for doing this @sleekybadger - it will definitely help people getting started and evolving their Dangerfiles. 👍 

Shipped in 5.2.0
