### ISSUE TITLE
Danger fails to run locally when multiple origins are defined

### ISSUE THREAD

**Issue by samdmarshall** [danger/danger#769]
# Report

## What did you do?
`danger local --verbose`

## What did you expect to happen?
report on issues with my local copy in relation to remote

## What happened instead?
```
Running your Dangerfile against this PR - https://github.com/samdmarshall/micro/pull/601

Local repository was not found on GitHub. If you're trying to test a private repository please provide a valid API token through DANGER_GITHUB_API_TOKEN environment variable.
```

## Your Environment

Danger Version: `4.3.2`
Ruby Version: `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]`

  ```ruby
yaml.lint_yaml_files("runtime/syntax/*")
  ```

Git Remotes:
```
$ git remote show
master
origin
$ git remote get-url master
git@github.com:zyedidia/micro.git
$ git remote get-url origin
git@github.com:samdmarshall/micro.git
```

When working on forked repos I checkout my repo and also add the remote repo as an origin point so i can easily pull down and merge upstream changes into my local copy. Danger doesn't seem to correctly handle this case as it composes a URL too my fork but uses the original repo's PRs numbers.

https://github.com/samdmarshall/micro <= zero PRs
https://github.com/zyedidia/micro <= last merged PR was 601

**Comment by orta** [comment]
I'd recommend trying `danger pr https://github.com/zyedidia/micro/pull/607` to get the behaviour you're after 👍 

I wonder if we should add a notice in local that `pr` is probably going to work better for them.

**Comment by samdmarshall** [comment]
won't that behavior post back to the PR? in this case i would just like to run it locally.

**Comment by orta** [comment]
Nah it's basically danger local with less magic 👍

**Comment by samdmarshall** [comment]
hmmm, feels like i am misunderstanding something -- why isn't the `pr` command not a flag on `local` then?

**Comment by orta** [comment]
I wanted danger local to basically do something else eventually, #382 but I decided to make DangerJS + Peril instead

Otherwise that would have made sense yeah
