### ISSUE TITLE
Import Dangerfile from GitHub Enterprise

### ISSUE THREAD

**Issue by hotbott** [danger/danger#770]
We're running a GitHub Enterprise instance and try to put a common `Dangerfile` in a shared repository.
`danger` works great with the environment settings for a custom host (`DANGER_GITHUB_HOST` && `DANGER_GITHUB_API_BASE_URL`).
Unfortunately `import_dangerfile` does not allow to use a custom host 😢

*Possible implementations*
* Add a `:host` parameter to `danger.import_dangerfile()` to overwrite the default path for the (**raw**) content
* Tell  `gitub.rb::file_url` to use the custom GitHub host from `DANGER_GITHUB_HOST` if available. This would be more consistent but may break compatibility 🙈
* Add a `:use_github_host` parameter to `danger.import_dangerfile()` and read the content path from `DANGER_GITHUB_HOST`

I could crate a PR if I get some votes...

**Comment by orta** [comment]
Ah good catch, I don't have an enterprise account - so these things sometimes slip by

I think respecting `DANGER_GITHUB_HOST` is probably the way most people would expect it to work - try give that a shot 👍
