### ISSUE TITLE
How to drop `colored`?

### ISSUE THREAD

**Issue by diogot** [danger/danger#776]
`colored` is deprecated and is not a direct dependency of Danger 👍.
But somehow looks like `cork` 0.2.0 is installing `colored` (you can check this on `Gemfile.lock`) even if is [not a current dependency of it](https://github.com/CocoaPods/Cork/blob/master/cork.gemspec#L17).

Do you have any leads on how can I enforce `colored2` to be used instead of `colored`?

**Comment by orta** [comment]
We moved CocoaPods' entire dep stack off colored to colored2, so CLAide should be fine - cork will probably need the changes and then just changing it in danger too

**Comment by orta** [comment]
Probably just need to make a cork release

**Comment by orta** [comment]
@dantoml - it looks like Cork is in rainforest, so if you see any issues on the next deploy for Cork, can you let me know?

**Comment by diogot** [comment]
Thanks, let me know if there is something that I can do.

**Comment by DanToml** [comment]
@orta Will do :+1:

**Comment by orta** [comment]
Colored is now dropped from the dependency tree. Do a `bundle update cork` and it should remove it.

**Comment by diogot** [comment]
Great, thanks!
