### ISSUE TITLE
Latest changes break executing danger

### ISSUE THREAD

**Issue by mlammers** [danger/danger#790]
# Report

## What did you do?

Run `bundle exec danger`

## What did you expect to happen?

danger should be run

## What happened instead?

bundler: failed to load command: danger (/home/vagrant/.gem/ruby/2.3.3/bin/danger)
NoMethodError: undefined method `include?' for nil:NilClass
  /home/vagrant/.gem/ruby/2.3.3/gems/danger-5.0.2/lib/danger/request_sources/bitbucket_server_api.rb:14:in `initialize'

## Your Environment

Running the very latest Danger version (5.0.2). A couple of hours ago changes were introduced:

https://github.com/danger/danger/blob/master/lib/danger/request_sources/bitbucket_server_api.rb#L14

This will throw an error, when the environment variable "DANGER_BITBUCKETSERVER_HOST" is nil.

**Comment by orta** [comment]
Thanks, I've submitted a PR

**Comment by mlammers** [comment]
@orta Thanks for the quick fix!

**Comment by orta** [comment]
👍

**Comment by orta** [comment]
This is shipped now
