### ISSUE TITLE
enforce links to Trello/JIRA in PR/MR bodies

### ISSUE THREAD

**Issue by RishabhTayal** [danger/danger#795]
# Report

This is more of question than issue. How can we enforce links to Trello/JIRA in PR/MR bodies?

**Comment by orta** [comment]
Your Dangerfile would have something like:

```
has_jira = github.pr_body.include("jira")
```

Then you can fail/warn/message based on `has_jira`.

**Comment by RishabhTayal** [comment]
Looks like this line has wrong syntax. I copied the same line in my `Dangerfile` and got error. Changed it to `has_jira = github.pr_body.include? "jira"` and it worked.

**Comment by orta** [comment]
Ah, yeah, I've been doing too much JavaScript
