### ISSUE TITLE
Few examples to show how to create rules

### ISSUE THREAD

**Issue by RishabhTayal** [danger/danger#801]
# Report

I know there are some example `Dangerfile` [here](https://danger.systems), but I think it would be nice to have more examples showing some specific rules like the ones which are show cased in the [keynote presentation](https://github.com/danger/design/blob/master/keynote/cocoaheads-danger-15.key). 

This will be a nice way to show other users what they can do with `danger` and how they can do it.

Willing to help with this if you think we should do this.

**Comment by orta** [comment]
That kind of documentation should be on the website, do you feel that it's
not covered well there?

 I did wonder about showing random oss dangerfiles on it now that there's
800 of them

**Comment by RishabhTayal** [comment]
The examples on the website are really nice to start with but I think there is much more someone can do with `danger`. We need to show off that somewhere with examples. For e,.g in the above mentioned presentation file there is a mention of `Spell Check Markdown` and `highlight undocumented methods`. It would be nice to show an example of how to achieve that rule.

**Comment by orta** [comment]
Those are plugins, the examples for them are inside the docs for those plugins - Danger provides the ability to make those work but we can't make examples for everything because there are an infinite amount of possible rules.

**Comment by RishabhTayal** [comment]
That's fine. I will close the issue now. Thanks.
