### ISSUE TITLE
Run Shell Command from Dangerfile

### ISSUE THREAD

**Issue by RishabhTayal** [danger/danger#805]
# Report

Is there a way to run shell terminal commands inside `Dangerfile`? For e.g. `sh("cd test")`.

**Comment by mihai8804858** [comment]
@RishabhTayal Have you tried `system("cd test")`? I'm using it in Dangerfile to run a gem.

**Comment by RishabhTayal** [comment]
It's not giving any error while running `danger` now but I don't think command is actually working. 

I tried 

```
system("cd test")
system("pwd")
```

It doesn't print anything in the console. It should print the current folder path.

**Comment by mihai8804858** [comment]
Ok. I tried running this in my `Dangerfile`:
```
system("echo HERE!!!")
system("cd Documentation")
system("pwd")
```
and it printed
```
HERE!!!
/Users/mseremet/Desktop/
```
It printed the message and current directory path, but looks like it didn't change the path to `Documentation` folder.

**Comment by RishabhTayal** [comment]
Same here. It works for `system("echo HERE!")` and `system("pwd")` but not for `system("cd Documentation")`.

**Comment by JuanitoFatas** [comment]
I think CI providers handle each system command in subshell, so one `cd` doesn't effect the next one. You could give `system("cd Documentation && pwd")` a try.

**Comment by RishabhTayal** [comment]
Wow! That works! 👍 

Does that mean when we do `system("cd Documentation")` only it's not switching to the `Documentation` folder or does that mean that it's switching to `Documentation` folder but the subsequent `system("pwd")` doesn't work because of the subshell thing?

**Comment by RishabhTayal** [comment]
Closing this issue now.
