### ISSUE TITLE
GitHub pull request general question

### ISSUE THREAD

**Issue by ReadmeCritic** [danger/danger#816]
Sorry this is a dumb question, trying to understand how the the library works in regard to posting a comment on a pull request after a commit..

Does the commit have information about a pull request it belongs to?

**Comment by orta** [comment]
It runs on CIs, and the [CIs have ENV vars](https://github.com/danger/danger/blob/master/lib/danger/ci_source/travis.rb#L29) that correlate to the PRs.

**Comment by ReadmeCritic** [comment]
thx
