### ISSUE TITLE
FBSnapshot tests?

### ISSUE THREAD

**Issue by kirakik** [danger/danger#818]
Does anyone know of a plugin that is able to run FBSnapshot tests and post their result through Danger?

Thank you

**Comment by orta** [comment]
You need to upload the images somewhere, we use [second_curtain](https://github.com/ashfurrow/second_curtain) then search through the build logs [for it's output](https://github.com/artsy/eigen/blob/master/Dangerfile.circle.rb#L15-L19) in our Dangerfile.

**Comment by orta** [comment]
Closing as this isn't really actionable from our side, it should be a plugin.
