### ISSUE TITLE
Import Dangerfile from private repo

### ISSUE THREAD

**Issue by mihai8804858** [danger/danger#819]
When import Dangerfile (using `import_dangerfile(<repo>, <branch>, <path>)`) from a private repo, Danger returns `404 - Not found` as Dangerfile content. I guess that's because it doesn't have access to file content. Maybe it should use `DANGER_GITHUB_API_TOKEN` token for downloading the file?

**Comment by orta** [comment]
That makes sense, yep - want to take a look into it?

**Comment by mihai8804858** [comment]
@orta Yes, I'll take a took over this.

**Comment by mihai8804858** [comment]
Investigated this a bit. Looks like danger uses `DANGER_GITHUB_API_TOKEN` when downloading `Dangerfile` from private repo. I got `404 - Not found` because token's user didn't had access to the repo. After opening access I'm able to download `Dangerfile` from private repo.

**Comment by orta** [comment]
👍
