### ISSUE TITLE
Support file globbing

### ISSUE THREAD

**Issue by orta** [danger/danger#82]
Look at https://github.com/artsy/elan/pull/5

```ruby
WATCHED_FILES = [
  '/components/lib/variables/colors.json',
  '/components/lib/variables/typography.json',
  '/components/lib/variables/widths.json'
]

message("@orta something changed in elan!") if (modified_files & WATCHED_FILES).any?
```

It would be much nicer to do either:

```ruby
message("@orta something changed in elan!") if modified_files["/components/lib/variables/*"]
```
or
```ruby
message("@orta something changed in elan!") if modified_files.include? "/components/lib/variables/*"
```

E.g. we could use a special array subclass that has a different `include?` here.

**Comment by orta** [comment]
OK, I think I want `file_modified`, `file_added`, `file_removed` to all act like arrays, but to support globbing in the include function. So in my mind, this one won:

``` ruby
message("@orta something changed in elan!") if files_modified.include? "/components/lib/variables/*"
```

**Comment by KrauseFx** [comment]
Updated ticket to use `modified_files` instead of `files_modified`

**Comment by orta** [comment]
@marcelofabri brought up that some of the array transform methods like `map` would also need functions replacing
