### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by macklinu** [danger/danger#821]
# Report

## What did you do?

* `cd` into a local [GitHub pages repo](https://help.github.com/articles/user-organization-and-project-pages/) (`username.github.io`)
* Add `gem "danger"` to Gemfile
* Run `bundle install`
* Run `bundle exec danger init`
* `danger init` crashes after step 4

## What did you expect to happen?

`danger init` completes without crashing.

## What happened instead?

`danger init` logs an error after step 4 and crashes.

```
Step 4: Add Danger for your CI

Add - bundle exec danger as a new step in the script section of your .travis.yml file.
You shouldn't use after_success, after_failure, after_script as they cannot fail your builds.

OK, I'll give you a moment to do this...


Final step: exposing the GitHub token as an environment build variable.

As you have an Open Source repo, this token should be considered public, otherwise you cannot
run Danger on pull requests from forks, limiting its use.
In order to add an environment variable, go to:
bundler: failed to load command: danger (/Users/macklinu/.rbenv/versions/2.4.0/bin/danger)
NoMethodError: undefined method `[]' for nil:NilClass
  /Users/macklinu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/danger-5.2.2/lib/danger/commands/init.rb:148:in `current_repo_slug'
  /Users/macklinu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/danger-5.2.2/lib/danger/commands/init.rb:219:in `travis_token'
  /Users/macklinu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/danger-5.2.2/lib/danger/commands/init.rb:169:in `setup_danger_ci'
  /Users/macklinu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/danger-5.2.2/lib/danger/commands/init.rb:38:in `run'
  /Users/macklinu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /Users/macklinu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/danger-5.2.2/bin/danger:5:in `<top (required)>'
  /Users/macklinu/.rbenv/versions/2.4.0/bin/danger:22:in `load'
  /Users/macklinu/.rbenv/versions/2.4.0/bin/danger:22:in `<top (required)>'
```

I tracked down [the line that caused the crash](https://github.com/danger/danger/blob/v5.2.2/lib/danger/commands/init.rb#L148). It looks like the previous line failed to match my git remote, `https://github.com/macklinu/macklinu.github.io`. I tested out the regular expression match in [`init.rb:147`](https://github.com/danger/danger/blob/v5.2.2/lib/danger/commands/init.rb#L147) a REPL to verify this (those extra dots in the repo name throw things off :boom:): 

```rb
'https://github.com/macklinu/macklinu.github.io.git'.match(%r{([\/:])([^\/]+\/[^\/.]+)(?:.git)?$})
// => nil
```

## Your Environment

* Which CI are you running on? Travis CI
* Are you running the latest version of Danger? 5.2.2
* What is your Dangerfile? Haven't gotten that far

**Comment by sleekybadger** [comment]
@macklinu Thank you for reporting this issue 👍 . 
@orta here [PR](https://github.com/danger/danger/pull/822) to fix this.
