### ISSUE TITLE
Swiftlint plugin not run

### ISSUE THREAD

**Issue by netbe** [danger/danger#827]
# Report

## What did you do?

`bundle exec danger`

## What did you expect to happen?

Run swiflint.

## What happened instead?

Swiftlint did not run or did not produce any violations, running swiftlint directly does produce errors

## Your Environment

* Which CI are you running on? jenkins
* Are you running the latest version of Danger? 5.2.2
* What is your Dangerfile? 

```ruby
message("Start code review")

swiftlint.lint_files
# If you want the lint result shows in diff instead of comment, you can use inline_mode option.
# Violations that out of the diff will show in danger's fail or warn section.
swiftlint.lint_files inline_mode: true

the_coding_love.random


message("End code review")
```

* Gemfile:

 ```ruby
# frozen_string_literal: true
source "https://rubygems.org"

gem 'fastlane'

# Since we use other actions from build-tools
# we need its dependencies
gem 'aws-sdk'
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)

gem 'xcode-install'

# comments on Pull Request
gem 'danger', github: 'sleekybadger/danger',
                         branch: 'hotfix/invalid-encoding',
                         ref: 'e8b25040f98cca260a5a49a2504baed5898caf85'
gem 'danger-swiftlint'
gem 'danger-the_coding_love'

# Dependencies of developer.rb

gem 'xcodeproj'
gem 'inifile'
```

Note that plugin like `the_coding_love`  was successfully run and that `danger plugins` does not list `swiftlint`.

**Comment by orta** [comment]
If Swiftlint is not set up correctly at CocoaPods-level then I'd expect `swiftlint.lint_files` to fail and cause an exception as you can't send messages to nil in Ruby. I'd recommend investigating this from the swift format side.

**Comment by netbe** [comment]
@orta not sure what you mean by that:

>  investigating this from the swift format side.

As stated I do get violations via swiftlint directly.

**Comment by netbe** [comment]
Ok got it, the violations were not part of the git diff hence no comments on the PR.
