### ISSUE TITLE
Danger doesn't post to PRs

### ISSUE THREAD

**Issue by tamasprezi** [danger/danger#828]
# Report

## What did you do?
I have a **private repo** whose PRs I want to run danger for. I'm using RVM with a 2.2.x Ruby + Bundler with `danger` and `danger-swiftlint` in the Gemfile. I've set up a GitHub user with an access token (all repo permissions) and this user is invited with write access to collaborate on the private repo. I'm running danger as follows:

```
$ DANGER_GITHUB_API_TOKEN="<token>" rvm ruby-2.2.1 do bundle exec danger pr https://github.com/myorg/myrepo/pull/<pull_id>
```

## What did you expect to happen?

I expected danger to perform the steps in the Dangerfile, then post the result in a comment to the PR.

## What happened instead?

Danger executes, finds the PR, properly logs the metadata and all issues to the console, then it exits with error code 0 WITHOUT posting anything to the PR. No errors are printed.

## Your Environment

CI: Jenkins (but the issue can also be reproduced from the development machine)
Danger version: 5.2.2

  ```ruby
# Warn when there is a big PR
warn("Big PR") if git.lines_of_code > 1000

# run swiftlint
swiftlint.config_file = '.swiftlint.yml'
swiftlint.lint_files  
  ```

**Comment by orta** [comment]
Danger PR is not meant for writing on the issue, its a development tool. You could just use `danger`.

I wonder if we should add a large warning if `ENV["CI"]` is set when someone uses `danger pr` as this is the second time it's come up.

**Comment by tamasprezi** [comment]
Hmm I see, so what exactly should be set in the environment for danger to recognize a PR? I'm getting `Not a Pull Request - skipping ``danger`` run` messages on Jenkins, even though the build was triggered by a GitHub PR webhook.

**Comment by orta** [comment]
I don't use Jenkins, but I thought it was set up by default for the pull request extension - it looks for these vars: https://github.com/danger/danger/blob/master/lib/danger/ci_source/jenkins.rb#L74

**Comment by tamasprezi** [comment]
Awesome, thanks for pointing it out, for some reason the `ghprbPullId` was missing from the env vars, added it and now it works like a charm!

**Comment by orta** [comment]
👍

**Comment by orta** [comment]
I've updated the docs a bit in https://github.com/danger/danger/pull/829

**Comment by RishabhTayal** [comment]
Rishabh Tayal liked your email
Spark by Readdle
