### ISSUE TITLE
Make `danger init` a wizard

### ISSUE THREAD

**Issue by orta** [danger/danger#83]
![Giphy](http://media4.giphy.com/media/IN8gg3Gci335S/giphy.gif)

README should recommend:

* Making Gemfile
```
    gem 'danger'
```
* Doing a `bundle install`
* Starting the Wizard via `bundle exec danger init`

Then the steps will guide you through the process of

1. make new account for the repo
2. Talking you through the access settings and what it means 
3. setting up a new access token for repo  ( Note, differentiate between OSS / Closed Source )
5. creating a default `Dangerfile`
6. Offering some ideas for further expansion
6. Talk about how to add Danger to your CI

**Comment by orta** [comment]
fixed by #86

**Comment by KrauseFx** [comment]
Ready to be closed, right?
