### ISSUE TITLE
Add ability to set dismiss_out_of_range_messages per each message kinds

### ISSUE THREAD

**Issue by giginet** [danger/danger#831]
# Feature request

If we set `dismiss_out_of_range_messages`, all kind of inline comments are dismissed.

However, I want to dismiss specific kind message only.
(For example, warnings out of ranges should be dismissed. errors should be commented.)

I'd like to set `dismiss_out_of_range_messages` per each kinds.

```ruby
dismiss_out_of_range_messages = {
  warning: true,
  error: false,
  message: true,
  markdown: true,
}
```

Could you tell me your opinion?
I think `dismiss_out_of_range_messages` should accept boolean or `[Symbol: boolean]`.

If it is OK, I'll send PR.

**Comment by sleekybadger** [comment]
@giginet hi, can we close this?

**Comment by orta** [comment]
Yes, this got shipped - unsure if it's in production yet though
