### ISSUE TITLE
Obtaining GITHUB_PULL_REQUEST_ID for TeamCity – impossible?

### ISSUE THREAD

**Issue by sgwilym** [danger/danger#834]
Hello! Danger supposedly supports TeamCity, but we can't for the life of us figure out one critical part, which is how to get the corresponding PR number for a build. We've tried using an API to query GitHub with, but a major pain point has been that branches have a one-to-many relationship with pull requests.

Is anybody else using TeamCity with Danger, and if so, how are you obtaining the `GITHUB_PULL_REQUEST_ID` variable?

**Comment by orta** [comment]
Good Q, I assume that @rbsgn was using something like https://github.com/lawliet89/pr_demon or the script at the end of this https://youtrack.jetbrains.com/issue/TW-43759

**Comment by atelic** [comment]
I just went through setting up Danger with TeamCity and was able to do the following for pull requests:
```
branch="%teamcity.build.branch%"
GITHUB_PULL_REQUEST_ID=(${branch//\// })
```

**Comment by orta** [comment]
@atelic is there some way we can grab that ID from inside Danger?

**Comment by atelic** [comment]
@orta You might be able to ask users to add the following to their Simple Command Runner:
```bash
export TEAMCITY_BRANCH="%teamcity.build.branch%"
```

then in Danger

```ruby
branch_name = ENV["TEAMCITY_BRANCH"]
GITHUB_PULL_REQUEST_ID = branch.split('/')[0]
```


I don't believe that `%teamcity.build.branch%` is available in `ENV` without exporting it though

**Comment by rbsgn** [comment]
Yep, I've configured this manually the same way

**Comment by orta** [comment]
Alright - we've got improved docs in master now, so this can be closed - thanks

**Comment by nsaud01** [comment]
I'm confused. %teamcity.build.branch% only has the branch name (in my case refs/heads/tc-pr-test). Where, when or how does that include the PR number? Any help would be very much appreciated. I feel like I've been at this forever...

**Comment by Xorima** [comment]
Hey, will issue a PR for the docs but incase anyone else comes here to find this, the best way to do this nowdays is using the Pull Request feature in TeamCity which gives you the following variable `teamcity.pullRequest.number` you simply set the env var to this in the parameters and done.
