### ISSUE TITLE
Danger's inline comment duplicated in github

### ISSUE THREAD

**Issue by litmon** [danger/danger#835]
# Report

https://github.com/litmon/danger-sample/pull/1

seems like above sample PR.
When the danger's inline comment have a reply comment, push some commit(move head_ref in this PR), and run `bundle exec danger`, danger commented duplicated line and comment as new conversation.
After this cause, every time I run `bundle exec danger`, danger's commented as new conversation.

<img width="541" alt="2017-06-10 2 50 06" src="https://user-images.githubusercontent.com/6662768/26987769-c56d6aae-4d87-11e7-8000-399aba5f1956.png">

<img width="482" alt="2017-06-10 2 53 14" src="https://user-images.githubusercontent.com/6662768/26987832-fca4e22c-4d87-11e7-9c82-dd3bfc801862.png">

This is dirty, so I want to fix this bug.

## What did you do?

- run the `bundle exec danger`, and you replied some danger's comments
- push some commit, and run `bundle exec danger`

## What did you expect to happen?

Do not duplicated comment.

## What happened instead?

Do duplicated comment as new conversation.

## Your Environment

* Which CI are you running on?

jenkins

* Are you running the latest version of Danger?

latest

* What is your Dangerfile?

```
warn("It is typo", file: "sample.txt", line: 1)
```

**Comment by orta** [comment]
Is this duplicated in the case of it being shown twice on 1 danger run, or it being duplicated per danger-run?

**Comment by litmon** [comment]
Yes, run danger after some commits pushed, duplicated comments happen every time.
it is happend when head_ref changed.

**Comment by litmon** [comment]
I tried a patch like below, the bug fixed.


```
--- a/lib/danger/request_sources/github/github.rb
+++ b/lib/danger/request_sources/github/github.rb
@@ -312,13 +312,14 @@ module Danger
           end
 
           matching_comments = danger_comments.select do |comment_data|
-            if comment_data["path"] == m.file && comment_data["commit_id"] == head_ref && comment_data["position"] == position
+            if comment_data["path"] == m.file && comment_data["position"] == position
               # Parse it to avoid problems with strikethrough
               violation = violations_from_table(comment_data["body"]).first
               if violation
                 messages_are_equivalent(violation, m)
               else
-                comment_data["body"] == body
+                blob_regexp = %r{blob/[0-9a-z]+/}
+                comment_data["body"].sub(blob_regexp, "") == body.sub(blob_regexp, "")
               end
             else
               false
```

**Comment by orta** [comment]
I've moved that code into a PR to test CI @litmon - can you please explain to me your choices about the `blob_regexp`?

**Comment by litmon** [comment]
FIrst, I tried to remove `&& comment_data["commit_id"] == head_ref` because duplicated comment is happened when head_ref is changed.
But it is not succeeded because of comparing `comment_data["body"]` and `body` is failed, why the difference between these is just commit hash in `blob_regexp`.

**Comment by orta** [comment]
Thanks -  Got this green, I'll give this some time in master, then it should be good to go!

**Comment by litmon** [comment]
Thanks! I'm looking forward to next release.
