### ISSUE TITLE
Wrong commits set for MR on Gitlab

### ISSUE THREAD

**Issue by almozavr** [danger/danger#838]
# Report
Wrong set of `git.commits` for MergeRequest on Gitlab.

## What did you do?
Run `bundle exec danger --danger_id=pr_linter --fail-on-errors=true` on `Jenkins` with `gitlab` plugin.

## What did you expect to happen?
Get commits with `git.commits` which are diff for MergeRequest's source and target branches (read `git log gitlabTargetBranch..gitlabSourceBranch`).

## What happened instead?
All commits are wrong and not the same as I can see in MergeRequest's Commits section.

## Your Environment
Jenkins 2.46.3
Jenkins Gitlab Plugin 1.4.5
GitLab Enterprise Edition 9.1.4-ee
Danger Gem 5.0.1

* Which CI are you running on?
Jenkins 
* Are you running the latest version of Danger?
Yes
* What is your Dangerfile?

```ruby
def isCapitalized(string)
  return string.slice(0,1).capitalize + string.slice(1..-1) == string
end

def lintCommit(commit)
  (subject, empty_line, *body) = commit.message.split("\n")
  message = "#{commit.sha} subject is malformed. You can use rebase to fix it\n"

  is_too_short = commit.message.length < 10
  is_too_long = subject.length > 72
  is_not_capitalized = !isCapitalized(subject)
  ends_with_dot = subject.split('').last == '.'

  is_failed = is_too_long || is_not_capitalized || ends_with_dot || is_too_short

  message += is_too_short ? ":warning: Subject is too short\n" : ""
  message += is_too_long ? ":warning: Subject is longer than 72 symbols\n" : ""
  message += is_not_capitalized ? ":warning: Subject is not capitalized\n" : ""
  message += ends_with_dot ? ":warning: Subject ends with dot\n" : ""

  fail(message) if is_failed
end

fail('Labels are not assigned') if gitlab.mr_labels.empty?
fail('Title should start from JIRA ticket id') unless gitlab.mr_title =~ /^[A-Z]+\-[0-9]+\s\w+.*$/ || gitlab.mr_labels.include?('common')
fail('Title is not capitalized') unless isCapitalized(gitlab.mr_title)
fail('Title is longer than 64 symbols (72 including PR number)') unless gitlab.mr_title.length <= 64

for commit in git.commits
  next if commit.message =~ /^Merge (remote-tracking )?branch/
  next if commit.message =~ /^Revert\s/
  lintCommit(commit)
end

%w(gradle/wrapper/gradle-wrapper.properties
  settings.gradle build.gradle app/build.gradle
  Jenkinsfile-check Jenkinsfile-publish
  Dangerfile Gemfile Gemfile.lock
  signing/ debug.keystore
  .gitignore
).each { |file|  warn "#{gitlab.html_link(file)} was edited." if git.modified_files.include?(file) }
  ```

**Comment by orta** [comment]
It's possible that the git commits are based on a previous version of the MR from when it the process started, Danger  uses the API to figure out what the commits were and then builds the commit history form those

**Comment by almozavr** [comment]
@orta I've created the very new MR, so not sure this is the case. What you say is Danger uses Gitlab's API to figure out commits history for particular MR, right? No `git` manipulation?

**Comment by orta** [comment]
I think so, it does look like it uses the [API to pull out the head commit ](https://github.com/danger/danger/blob/master/lib/danger/request_sources/gitlab.rb#L62-L93)

**Comment by almozavr** [comment]
@orta you're right. So I've checked Gitlab API call and found the problem... Since `gitlab api v4` every request is paginated and default per_page is 20 and guess what? The problematic MR has >20 commits (so base_commit is not actually what it is). 
It seems like `auto_paginate` option doesn't work well at gitlab-gem or danger-gem level. 
`auto-paginate` is used here: https://github.com/danger/danger/blob/master/lib/danger/request_sources/gitlab.rb#L99

**Comment by almozavr** [comment]
The interesting thing is: my config is pointing to `gitlab api v3` and despite docs `Gitlab gem` seems to still support it. In terms of Gitlab's `merge_request_commits`api call, v3 and v4 differ with the MR argument (id for v3 and iid for v4). The question is: does Danger provide id or iid for it? It hides beneath `ci_source` argument

**Comment by almozavr** [comment]
OK, so it seems like Danger relies on MR `id` (not `iid`) params: https://github.com/danger/danger/blob/master/lib/danger/ci_source/jenkins.rb#L85

So it means `Gitlab API v3` is the right way to go and commits request page size is not the case anyway. So, the problem is elsewhere

**Comment by orta** [comment]
Interesting, it is possible that there's a singular MR API request which has the head and base shas in it, instead of having to loop through all the commits?

**Comment by sleekybadger** [comment]
No, looks like we can't do this in single request. But I think we can try `#first_page` and `#last_page` [methods](https://github.com/NARKOZ/gitlab/blob/master/lib/gitlab/paginated_response.rb#L61-L75) from `gitlab` gem.

**Comment by sleekybadger** [comment]
@almozavr Hi, can you run your build again using potential fix?

```
gem 'danger', github: 'sleekybadger/danger', 
              branch: 'hotfix/gitlab-wrong-base', 
              ref: 'e9427ddbd309cace9e1ee4bb73c94afe4e516294'
```

**Comment by almozavr** [comment]
@sleekybadger 
```ruby
13:23:04 /opt/rvm/gems/ruby-2.3.1/bundler/gems/danger-e9427ddbd309/lib/danger/request_sources/gitlab.rb:64:in `base_commit': undefined method `last' for nil:NilClass (NoMethodError)
13:23:04 	from /opt/rvm/gems/ruby-2.3.1/bundler/gems/danger-e9427ddbd309/lib/danger/request_sources/gitlab.rb:92:in `setup_danger_branches'
13:23:04 	from /opt/rvm/gems/ruby-2.3.1/bundler/gems/danger-e9427ddbd309/lib/danger/danger_core/environment_manager.rb:57:in `ensure_danger_branches_are_setup'
13:23:04 	from /opt/rvm/gems/ruby-2.3.1/bundler/gems/danger-e9427ddbd309/lib/danger/danger_core/dangerfile.rb:258:in `setup_for_running'
13:23:04 	from /opt/rvm/gems/ruby-2.3.1/bundler/gems/danger-e9427ddbd309/lib/danger/danger_core/dangerfile.rb:269:in `run'
13:23:04 	from /opt/rvm/gems/ruby-2.3.1/bundler/gems/danger-e9427ddbd309/lib/danger/danger_core/executor.rb:27:in `run'
13:23:04 	from /opt/rvm/gems/ruby-2.3.1/bundler/gems/danger-e9427ddbd309/lib/danger/commands/runner.rb:66:in `run'
13:23:04 	from /opt/rvm/gems/ruby-2.3.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
13:23:04 	from /opt/rvm/gems/ruby-2.3.1/bundler/gems/danger-e9427ddbd309/bin/danger:5:in `<top (required)>'
13:23:04 	from /opt/rvm/gems/ruby-2.3.1/bin/danger:23:in `load'
13:23:04 	from /opt/rvm/gems/ruby-2.3.1/bin/danger:23:in `<main>'
13:23:04 	from /opt/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
13:23:04 	from /opt/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by sleekybadger** [comment]
@almozavr sorry, gitlab api dock trick me. It [says](https://gitlab.com/gitlab-org/gitlab-ce/blob/8-16-stable/doc/api/README.md#pagination-link-header) that they are sent back with each
response, but: 
```
curl --header "PRIVATE-TOKEN: token" -I https://gitlab.com/api/v3/projects/id/merge_requests/id/commits

HTTP/1.1 200 OK
Server: nginx
Date: Tue, 13 Jun 2017 11:48:22 GMT
Content-Type: application/json
Content-Length: 23977
Cache-Control: no-cache
Vary: Origin
X-Frame-Options: SAMEORIGIN
X-Request-Id: 5f71bc63-ed14-4158-9741-5f412af5bcfc
X-Runtime: 0.322003
Strict-Transport-Security: max-age=31536000
```

Can you check that all commits are returning from gitlab api? You can do this in such way:
```
 :001 > require 'gitlab'
 => true
 :002 > client = Gitlab.client(endpoint: 'https://gitlab.com/api/v3', private_token: 'token')
 => #<Gitlab::Client:0x007f8c322b6040 @endpoint="https://gitlab.com/api/v3", @private_token="********************", @user_agent="Gitlab Ruby Gem 4.0.0">
 :003 > client.merge_request_commits(project_id, merge_request_id).count
 => 53
```

**Comment by almozavr** [comment]
@sleekybadger yeap, already did -> `v3` api returns all commits at once (seems like no `per_page` is needed). So my bet, there was something wrong with this request and it has failed, so default git.log param was used (which is _master_). If it's so, there is no more such issue but a point of improvement (e.g. to throw exception and not to use default params)

**Comment by sleekybadger** [comment]
@almozavr if commits were totally unrelated to MR, then you are right. If commits were related to MR, but `@git.commits` contained only part of them, then it's related to `@git.log` [count params](https://github.com/schacon/ruby-git/blob/master/lib/git/log.rb#L7) and will be fixed in next release.

**Comment by almozavr** [comment]
@sleekybadger there were commits, which targetBranch has already contained -> so I suppose it was Gitlab API problem. Seems like we can close this issue, as I can't reproduce the problem and don't see possible root cause.. Thanks everyone for assistance, anyway 👍
