### ISSUE TITLE
Creating merge request comment on GitLab.com causes crash

### ISSUE THREAD

**Issue by ffittschen** [danger/danger#843]
# Report

## What did you do?
My CI runner ran  `bundle exec danger` after I created a merge request

## What did you expect to happen?
Running my Dangerfile without it crashing and commenting the results to the merge request

## What happened instead?
Danger crashed, saying it got a 500 return code from the GitLab endpoint.

Since the code crashed in the `gitlab` gem, I ran `gitlab_client.create_merge_request_comment(<REDACTED>, 23, 'This is a test comment')` in `irb`, where it succeeded. So I guess the error has to do with the body generated by Danger?

If so, how could I debug this any further?

<details><summary>Crashlog</summary><p>

```
$ if [ -n "${CI_MERGE_REQUEST_ID}" ]; then bundle exec danger --version && bundle exec danger; fi
5.3.1
bundler: failed to load command: danger (/Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/bin/danger)
Gitlab::Error::InternalServerError: Server responded with code 500, message: 500 Internal Server Error. Request URI: https://gitlab.com/api/v4/projects/<REDACTED>/merge_requests/23/notes
  /Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/gems/gitlab-4.1.0/lib/gitlab/request.rb:80:in `validate'
  /Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/gems/gitlab-4.1.0/lib/gitlab/request.rb:49:in `post'
  /Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/gems/gitlab-4.1.0/lib/gitlab/client/merge_requests.rb:96:in `create_merge_request_comment'
  /Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/gems/danger-5.3.1/lib/danger/request_sources/gitlab.rb:132:in `update_pull_request!'
  /Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/gems/danger-5.3.1/lib/danger/danger_core/dangerfile.rb:319:in `post_exception'
  /Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/gems/danger-5.3.1/lib/danger/danger_core/dangerfile.rb:283:in `rescue in run'
  /Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/gems/danger-5.3.1/lib/danger/danger_core/dangerfile.rb:288:in `run'
  /Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/gems/danger-5.3.1/lib/danger/danger_core/executor.rb:27:in `run'
  /Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/gems/danger-5.3.1/lib/danger/commands/runner.rb:66:in `run'
  /Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/gems/danger-5.3.1/bin/danger:5:in `<top (required)>'
  /Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/bin/danger:22:in `load'
  /Users/ci-user/builds/7e7cfdac/0/demo-app/ios/vendor/ruby/2.4.0/bin/danger:22:in `<top (required)>'
ERROR: Job failed: exit status 1
```
</p></details>

## Your Environment

* Which CI are you running on?
  - GitLab CI (using a workaround)
* Are you running the latest version of Danger?
  - Yes, `5.3.1`

<details><summary>Dangerfile</summary>

```ruby
# Moved files have a pattern that is messing with file reading
modified_files = git.modified_files.select { |path| !path.include? "=>" }

# Sometimes it's a README fix, or something like that - which isn't relevant for running Danger
declared_trivial = (gitlab.mr_title + gitlab.mr_body).include?("#trivial")

# Have any changes happened inside the actual code or test code?
has_app_changes = !modified_files.grep(/App/).empty?
has_no_test_changes = modified_files.grep(/AppTests/).empty? && modified_files.grep(/AppUITests/).empty?

# You've made changes to the app, but didn't write any tests?
if has_app_changes && !has_no_test_changes
  warn("There are app changes, but no changes of the tests. That's OK as long as you're refactoring existing code.", sticky: false)
end

# Warn when there is a big MR
warn("Big MR, try to keep changes smaller if you can") if git.lines_of_code > 500

# Is the MR still work in progress? 
warn("MR is classed as Work in Progress") if gitlab.mr_title.include?("[WIP]")

# Warn when there are merge commits of other feature branches in the diff
source_branch_is_feature_branch = !(gitlab.branch_for_head =~ /^feature/).nil?
contains_merge_commit_from_feature_branch = git.commits.any? { |c| c.message =~ /^Merge branch '?feature/ }

if source_branch_is_feature_branch && contains_merge_commit_from_feature_branch
  warn("It seems like you merged another feature branch into this feature branch. If possible, revert that merge to keep this MR about one feature and open a new MR for the other feature branch.", sticky: false)
end

# Only accept merges to the develop branch
target_branch_is_not_develop = gitlab.branch_for_merge != "develop"

if target_branch_is_not_develop
  fail("Please re-submit this merge request to develop")
end

# Don't let testing shortcuts get into master by accident,
# ensuring that we don't get green builds based on a subset of tests.
(modified_files + git.added_files - %w(Dangerfile)).each do |file|
  next unless File.file?(file)
  contents = File.read(file)
  if file.start_with?('AppTests') || file.start_with?('AppUITests')
    fail("`xit` or `fit` left in tests (#{file})") if contents =~ /^\w*[xf]it/
    fail("`xdescribe` or `fdescribe` left in tests (#{file})") if contents =~ /^\w*[xf]describe/
  end
end

# Warn if 'Gemfile' was modified and 'Gemfile.lock' was not
if modified_files.include?("Gemfile")
  if !modified_files.include?("Gemfile.lock")
    warn("`Gemfile` was modified but `Gemfile.lock` was not")
  else
    message("`Gemfile` modified")
  end
end

# Warn if 'Podfile' was modified and 'Podfile.lock' was not
if modified_files.include?("Podfile")
  if !modified_files.include?("Podfile.lock")
    warn("`Podfile` was modified but `Podfile.lock` was not")
  else
    message("`Podfile` modified")
  end
end

# Are there any swiftlint warnings?
swiftlint.config_file = '.swiftlint.yml'
swiftlint.lint_files
swiftlint.lint_files inline_mode: true
```
</details>

**Comment by sleekybadger** [comment]
Hm, do you have `DANGER_GITLAB_API_BASE_URL` environment variable? Cause, I believe that we are [using](https://github.com/danger/danger/blob/master/lib/danger/request_sources/gitlab.rb#L55) gitlab api v3.

**Comment by ffittschen** [comment]
@sleekybadger Yes, you can see the request URI in the attached crashlog. Using the env variable you mentioned, I set the base url to `https://gitlab.com/api/v4` since with v3 it doesn't work.

For most of the merge requests Danger runs successfully. But sometimes it crashes in the place mentioned in the crashlog.

**Comment by sleekybadger** [comment]
@ffittschen hm, can you provide us generated by danger comment body for one of failed MR?

**Comment by ffittschen** [comment]
I'd like to, thats why I asked how I can debug it ;)

Is there already any way to run `danger local` against GitLab?

**Comment by sleekybadger** [comment]
Oh, I'm afraid that you can't - `danger local` supports only github right now. I modified my fork to print generated comment into `STDOUT`.

You can install it like this: 
```
gem 'danger', github: 'sleekybadger/danger', 
              branch: 'debug_gitlab', 
              ref: 'd246f6246e316d702dd6b47ca10c53562ff496d5'
```

**Comment by ffittschen** [comment]
Generated comment as printed by your fork (I replaced `\n` with newlines):
```
"
## Danger has errored
[!] Invalid `Dangerfile` file: invalid byte sequence in UTF-8
```
 #  from Dangerfile:62
 #  -------------------------------------------
 #  \xB2\x92u\x84#\x88\xB5k\u0004m\x85\xBB\xEE\xE77\x85\xC7IK\x98~\xDAG\x8C\xA3]\u001D\x8D~\xB5\xB2\xEAc\xD9eֲ\u0010d\xB9FlU\xBA\xC2LR\x8D\xB1\u001A\xEF\xA7\xD4\xED\xF9\x90\u0010\xA6\u0001\f\xB7\xB4!e\xAD\t\xA3\x8E\xB8\xAB\xB6
 >  &ⅆ\xFB1\xAF
 #  >e2\x9B\x88\xF9\xA95W\xD9?)\x8B\xBB\u0016\u001C\xF3\x81\xB9\v\u0002\f\xBD]\xF3je>\xEF\xA7A\u0001\u001E/#%5\a6U\xD6A\u00014.\u0016A\x94Ш\xF7\u0018\xE9\xEA
 #  -------------------------------------------
 ```

<p align=\"right\" data-meta=\"generated_by_danger\">
  Generated by :no_entry_sign: <a href=\"https://github.com/danger/danger/\">Danger</a>
  </p>
"
```

Dangerfile line 62 is the following:
`    fail("`xit` or `fit` left in tests (#{file})") if contents =~ /^\w*[xf]it/`

**Comment by sleekybadger** [comment]
Hm, that's really weird. Let's try to remove line 62, just to make sure that this is a problem.

**Comment by ffittschen** [comment]
Removing line 62 resulted in the error being thrown in line 63: https://gist.github.com/ffittschen/4fea64628edee730cddbee734a0c5d4a

Dangerfile line 63 is the following:
`    fail("`xdescribe` or `fdescribe` left in tests (#{file})") if contents =~ /^\w*[xf]describe/`

When I removed that line as well, Danger succeeded.

**Comment by orta** [comment]
Weird, could there be some odd invisible characters in there?

**Comment by ffittschen** [comment]
I just found the issue: In the Dangerfile I linked [above](https://github.com/danger/danger/issues/843#issue-237956668) you can see that I'm reading all modified files and added files and then apply the regex to the contents. But some of these might not be source files but rather images etc.

When I check the extension before reading the file the two lines that caused the problems above run successfully 👍🏻

In case someone stumbles upon the same problem, here is my updated snippet:
```ruby
(modified_files + git.added_files - %w(Dangerfile)).each do |file|
  next unless File.file?(file)
  accepted_formats = [".swift", ".m"]
  if accepted_formats.include? File.extname(file)
    contents = File.read(file)
    fail("`xit` or `fit` left in tests (#{file})") if contents =~ /^\s*[xf]it/
    fail("`xdescribe` or `fdescribe` left in tests (#{file})") if contents =~ /^\s*[xf]describe/
  end
end
```

**Comment by orta** [comment]
Hrm, I think we should add this as an example on the website instead of the current ones

**Comment by nikolaykasyanov** [comment]
Git "knows" if a file is binary, I wonder if there's a way to access that knowledge from Danger.

**Comment by orta** [comment]
Interesting, I wonder if the DSL could adapt that in a non-Dangerfile source breaking change like

```ruby
# instead of just 
git.modified_files

# you could also have
git.text.modified_files
git.binary.modified_files
```
