### ISSUE TITLE
Error on BuddyBuild log: Could not find the type of CI for Danger to run on

### ISSUE THREAD

**Issue by milind-mevada-stl** [danger/danger#849]
# Report

## What did you do?
I've added Gemfile and DangerFile. Set linter rules in danger file. I am using BuddyBuild CI for this. I have also added DANGER_GITHUB_API_TOKEN to BuddyBuild

## What did you expect to happen?
I want to run Danger over BuddyBuild CI.

## What happened instead?
BuddyBuild log has error like:    **Could not find the type of CI for Danger to run on.**

## Your Environment

* Which CI are you running on?
BuddyBuild

* Are you running the latest version of Danger?
Yes

* What is your Dangerfile?
   android_lint.report_file = "app/build/reports/lint-results.xml"
   android_lint.severity = "Error" 
   android_lint.lint
   android_lint.lint(inline_mode: true)

**Comment by orta** [comment]
There's not been any changes to BuddyBuild from Danger's side since it was first added - it's worth asking their support if anything has changed around the environment vars

**Comment by milind-mevada-stl** [comment]
@orta Can you tell me one more thing? 
Is this error comes when BuddyBuild can't find Environment variables ?

**Comment by orta** [comment]
I _think_ so, normally it's about [making sure this function](https://github.com/danger/danger/blob/master/lib/danger/ci_source/buddybuild.rb#L21) returns true, but it never can. So I assume they're using the [Jenkins ENV vars](https://github.com/danger/danger/blob/master/lib/danger/ci_source/jenkins.rb#L46).

Maybe this could be made to match the JS version - https://github.com/danger/danger-js/blob/master/source/ci_source/providers/BuddyBuild.ts#L11

**Comment by milind-mevada-stl** [comment]
It looks like my code is already passing from BuddyBuild.ts file. Because it verifys if it is a Pull Request or Single commit.
And as far as it's pull request it's working further.

**Comment by orta** [comment]
The .ts is from the JS version, that's a different project. Could it be this? http://danger.systems/guides/faq.html#danger-is-not-posting-to-github-prs-but-everything-looks-fine

**Comment by milind-mevada-stl** [comment]
@orta 
Re-integrating app to buddyBuild done my work. :smile: Thanks
