### ISSUE TITLE
Danger should ignore Dangerfile when checking diff (?)

### ISSUE THREAD

**Issue by WiesnerPeti** [danger/danger#850]
# Report

## What did you do? (Simplified)
1. Integrated Danger in GitLab project
2. Added gitlab.fail "You should not use the word Test" if /Test/.match(gitlab.mr_diff)
3. Create MR with this change

## What did you expect to happen?
MR does not have any comment, we are just introducing a new rule

## What happened instead?
MR has a comment, because the Danger rule was applied on the diff in Dangerfile too

## Your Environment
- GitLab
- danger (5.3.0)

  ```ruby
  gitlab.fail "You should not use the word Test" if /Test/.match(gitlab.mr_diff)

  ```

Is this expected? Can/Should we exclude the Dangerfile in this case?

**Comment by sleekybadger** [comment]
Hi @WiesnerPeti . I believe that it is correct behavior, cause you may wanna to protect your `Dangerfile` from unexpected changes. For example:

```
warn('Dangerfile changed') if git.modified_files.grep(/Dangerfile/).any?
```

You can solve your issue, by checking each file in diff and skipping files that you don't wanna check. I believe something like this will work:

```
git.diff.each do |file|
  unless file.path.match(/Dangerfile/)
    gitlab.fail "You should not use the word Test" if /Test/.match(file.patch)
  end
end
```

**Comment by WiesnerPeti** [comment]
@sleekybadger Thank you for the quick answer and the great suggestion! :)
