### ISSUE TITLE
Test won't run when developing a plugin

### ISSUE THREAD

**Issue by blender** [danger/danger#855]
# Report

## What did you do?

```
$ danger plugins create danger-hat_wizzard
$ cd danger-hat_wizzard
$ bundle install
$ bundle exec rake spec
```

## What did you expect to happen?

I expect tests to run

## What happened instead?

```
$ bundle exec rake spec
/usr/local/Cellar/ruby/2.4.1_1/bin/ruby -I/usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/lib:/usr/local/lib/ruby/gems/2.4.0/gems/rspec-support-3.6.0/lib /usr/local/lib/ruby/gems/2.4.0/gems/rspec-core-3.6.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
.
Could not set up API to Code Review site for Danger

For Danger to run on this project, you need to expose a set of following the ENV vars:
 - GitHub: DANGER_GITHUB_API_TOKEN
 - GitLab: DANGER_GITLAB_API_TOKEN
 - BitbucketServer: DANGER_BITBUCKETSERVER_USERNAME, DANGER_BITBUCKETSERVER_PASSWORD, DANGER_BITBUCKETSERVER_HOST
 - BitbucketCloud: DANGER_BITBUCKETCLOUD_USERNAME, DANGER_BITBUCKETCLOUD_PASSWORD


Found these keys in your ENV: HAS_JOSH_K_SEAL_OF_APPROVAL, TRAVIS_PULL_REQUEST, TRAVIS_REPO_SLUG, TRAVIS_COMMIT_RANGE, DANGER_GITHUB_API_TOKEN.

Failing the build, Danger cannot run without API access.
You can see more information at http://danger.systems/guides/getting_started.html


Finished in 0.01846 seconds (files took 0.60051 seconds to load)
```
## Your Environment

* Which CI are you running on? N/A
* Are you running the latest version of Danger? 5.3.3
* What is your Dangerfile? N/A
* Ruby version: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

**Comment by orta** [comment]
Interesting, I think this is because Danger is looking at the local git remotes and it's blank ( so it can't tell if you're on github/gitlab/bitbucket) normally this isn't a problem because it's either a setup from CI via git, or someone's plugin already has a remote

**Comment by orta** [comment]
Yep wghen I added `git remote add origin https://github.com/danger/danger.git` tests pass

**Comment by orta** [comment]
Looks like this is a known bug, gonna fix it: https://github.com/danger/danger-plugin-template/issues/7
