### ISSUE TITLE
[Feature Request] Gathering violations on same line

### ISSUE THREAD

**Issue by giginet** [danger/danger#856]
# Description

When I added the comments to a same line, comments are separated.
I want to report violations in one comment.

## Before

```ruby
warn "a comment", file: "foo.rb", line: 1
warn "another comment", file: "foo.rb", line: 1
```

## After

```ruby
warn ["a comment", "another comment"], file: "foo.rb", line: 1
```

![screen shot 2017-07-05 at 19 55 14](https://user-images.githubusercontent.com/147051/27861471-f7a81b7a-61bb-11e7-955f-b1484019346c.png)

**Comment by orta** [comment]
Interesting, makes sense to me 👍

**Comment by sleekybadger** [comment]
@orta @giginet as I understand we need ability to add multiple violations in same time?

**Comment by sleekybadger** [comment]
@orta here [pr](https://github.com/danger/danger/pull/859) to solve this, if I understood everything right 😆
