### ISSUE TITLE
Could not set up API to Code Review site for Danger - Github Enterprise + Jenkins

### ISSUE THREAD

**Issue by proviral** [danger/danger#858]
# Report

## What did you do?

bundle exec danger

## What did you expect to happen?

 Running your Dangerfile and finding the CI

## What happened instead?

[33m
Could not set up API to Code Review site for Danger
[0m
For your GitHub repo, you need to expose: [33mDANGER_GITHUB_API_TOKEN[0m
You may also need: DANGER_GITHUB_HOST, DANGER_GITHUB_API_BASE_URL

Found these keys in your ENV: JENKINS_HOME, MAIL, LANGUAGE, SSH_CLIENT, USER, RUN_CHANGES_DISPLAY_URL, SHLVL, NODE_LABELS, HUDSON_URL, OLDPWD, HOME, BUILD_URL, HUDSON_COOKIE, JENKINS_SERVER_COOKIE, WORKSPACE, DANGER_GITHUB_API_TOKEN, CHANGE_ID, LOGNAME, NODE_NAME, DANGER_GITHUB_API_BASE_URL, _, CHANGE_TARGET, EXECUTOR_NUMBER, XDG_SESSION_ID, BUILD_DISPLAY_NAME, HUDSON_HOME, JOB_BASE_NAME, PATH, BUILD_ID, XDG_RUNTIME_DIR, DANGER_GITHUB_HOST, BUILD_TAG, JENKINS_URL, ARTIFACTORY_KEY, LANG, JOB_URL, CHANGE_TITLE, BUILD_NUMBER, JENKINS_NODE_COOKIE, SHELL, CHANGE_AUTHOR_DISPLAY_NAME, RUN_DISPLAY_URL, CHANGE_AUTHOR, HUDSON_SERVER_COOKIE, JOB_DISPLAY_URL, JOB_NAME, PWD, SSH_CONNECTION, BRANCH_NAME, CHANGE_URL, RUBYOPT, RUBYLIB, GEM_PATH, GEM_HOME, BUNDLE_BIN_PATH, BUNDLE_GEMFILE, MANPATH.
## Your Environment

* Which CI are you running on? Jenkins
* Are you running the latest version of Danger? Using danger 5.3.3
* What is your Dangerfile?

  ```ruby
rubocop.lint
commit_lint.check
  ```

**Comment by orta** [comment]
Did you discover what was off?

**Comment by NeQuissimus** [comment]
We did something like this in a `Jenkinsfile`:

```
withEnv([
        "DANGER_GITHUB_HOST='https://github.company.com'",
        "DANGER_GITHUB_API_BASE_URL='https://github.company.com/api/v3/'"
      ]) {
        sh "bundle exec danger"
      }
```

If you single-tick the ENV values, things don't work. It needs to look like this instead:

```
withEnv([
        "DANGER_GITHUB_HOST=https://github.company.com",
        "DANGER_GITHUB_API_BASE_URL=https://github.company.com/api/v3/"
      ]) {
        sh "bundle exec danger"
      }
```
