### ISSUE TITLE
Transition to Gitlab's api/v4

### ISSUE THREAD

**Issue by almozavr** [danger/danger#860]
# Report
Currently, `danger-gitlab` uses `api v3` which is deprecated and gonna be dropped:
> API V3 will be removed in GitLab 9.5, to be released on August 22, 2017

## What did you expect to happen?
Transition to `api v4`

Gitlab gem has been already supporting it since 4.0.0

**Comment by sleekybadger** [comment]
Totally agree

**Comment by orta** [comment]
Sure, want to take a look? I'm not sure what's required on our side.

**Comment by almozavr** [comment]
Firstly, use proper ids (iids?) from gitlab for MRs.
Full docs here: https://docs.gitlab.com/ce/api/v3_to_v4.html

**Comment by sleekybadger** [comment]
Here [pr](https://github.com/danger/danger/pull/861) to solve this.
