### ISSUE TITLE
When is the next Danger release?

### ISSUE THREAD

**Issue by Palleas** [danger/danger#863]
Hello! 

We recently published a tutorial about using danger on buddybuild. For now, we're telling people to install the gem from `master` to have the changes from #857 included. 

Any idea when the next release is going to be?

Thanks!

**Comment by orta** [comment]
I wanted to get a release in once #861 is sorted

**Comment by Palleas** [comment]
Terrific, thank you!

**Comment by rpassis** [comment]
Just wanted to bump this to see if there is anyway we (contributors) can also help with gem releases? I just tagged a new release in master but not sure what the process is from there to get a gem released.

**Comment by orta** [comment]
I ship the gems, allowing folks to this [level of access only works](https://github.com/Moya/contributors) when there's a separation of releasing and the codebase - I usually ship a release ever 2-3 PRs which is about twice a week

**Comment by rpassis** [comment]
Makes sense, thanks!
