### ISSUE TITLE
Inconsistent pronouns

### ISSUE THREAD

**Issue by ashfurrow** [danger/danger#872]
When running `bundle exec danger init`, the Danger project is referred to as ["her"](https://github.com/danger/danger/blob/master/lib/danger/commands/init.rb#L83) and also ["it"](https://github.com/danger/danger/blob/master/lib/danger/commands/init.rb#L289). Not a huge deal, just felt weird, happy to fix given direction on it.

**Comment by sleekybadger** [comment]
@ashfurrow sure, this will be awesome

**Comment by ashfurrow** [comment]
Cool cool – @orta any preference? Gotta stay on-brand.

**Comment by orta** [comment]
Let's stick with She everywhere
