### ISSUE TITLE
Support for VSTS

### ISSUE THREAD

**Issue by devandanger** [danger/danger#878]
Our shop is using VSTS for our CI pipeline.  There is mention of support for VSTS assuming its using GitHub as the repo provider.  Is this due to differences in what's available webhook-wise for GitHub and not VSTS?  

Curious if there is more discussion on why its currently not possible?  Our team was interested in looking into but wanted to know where the brick walls were first.

**Comment by orta** [comment]
It's more that no-one has done the work of making a [request source](https://github.com/danger/danger/tree/master/lib/danger/request_sources) for VSTS - so long as there are API calls that correlate to the functions [in here](https://github.com/danger/danger/blob/master/lib/danger/request_sources/request_source.rb) it should be fine to add 👍

**Comment by devandanger** [comment]
Cool thanks for the info.
