### ISSUE TITLE
Filter out merge commits from the files_modified / added / removed etc

### ISSUE THREAD

**Issue by orta** [danger/danger#88]
![screen shot 2016-02-27 at 7 16 12 pm](https://cloud.githubusercontent.com/assets/49038/13376304/ca70ec8c-dd86-11e5-9b2e-7423fba8bb91.png)

vs

![screen shot 2016-02-27 at 7 17 20 pm](https://cloud.githubusercontent.com/assets/49038/13376306/ccef426a-dd86-11e5-9362-ce3f2a542f99.png)

**Comment by KrauseFx** [comment]
Such a beautiful table summary :heart:

**Comment by orta** [comment]
!'ve started trying to write tests for this: https://github.com/danger/danger/tree/merge

**Comment by orta** [comment]
closed by #135
