### ISSUE TITLE
Crashing using bitbucket server over docker

### ISSUE THREAD

**Issue by josete89** [danger/danger#888]
# Report

## What did you do?

My Dockerfile: 
```
########
FROM ruby:2.3.1

RUN gem install danger && \
	    gem install danger-commit_lint && \
	        gem install danger-prose

ENTRYPOINT ["danger"]
#######
```
```
docker run -e DANGER_BITBUCKETSERVER_USERNAME="user" -e DANGER_BITBUCKETSERVER_HOST="https://myhost/bitbucket" -e ghprbPullId="2" -e DANGER_BITBUCKETSERVER_PASSWORD="pwd" -e JENKINS_URL='https://myhost/jenkins' -v project_path:/app danger:5.4.0 --verbose
```

## What did you expect to happen?

running without chasing
## What happened instead?

```
/usr/local/bundle/gems/danger-5.4.0/lib/danger/ci_source/jenkins.rb:70:in `initialize': undefined method `match' for nil:NilClass (NoMethodError)
Did you mean?  catch
	from /usr/local/bundle/gems/danger-5.4.0/lib/danger/danger_core/environment_manager.rb:30:in `new'
	from /usr/local/bundle/gems/danger-5.4.0/lib/danger/danger_core/environment_manager.rb:30:in `initialize'
	from /usr/local/bundle/gems/danger-5.4.0/lib/danger/danger_core/executor.rb:23:in `new'
	from /usr/local/bundle/gems/danger-5.4.0/lib/danger/danger_core/executor.rb:23:in `run'
	from /usr/local/bundle/gems/danger-5.4.0/lib/danger/commands/runner.rb:66:in `run'
	from /usr/local/bundle/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /usr/local/bundle/gems/danger-5.4.0/bin/danger:5:in `<top (required)>'
	from /usr/local/bundle/bin/danger:22:in `load'
	from /usr/local/bundle/bin/danger:22:in `<main>'
```

## Your Environment

* Which CI are you running on? Docker
* Are you running the latest version of Danger? yes
* What is your Dangerfile? 
message("Hello it's working!")
warn("Big PR, try to keep changes smaller if you can") if git.lines_of_code > 500

**Comment by orta** [comment]
The crashing line ([here](https://github.com/danger/danger/blob/6bdf93eb42ceec3a7ef44c36aff899ca6c6e1404/lib/danger/ci_source/jenkins.rb#L70)) seems to be about the repo url, maybe you need to change something around that?

**Comment by josete89** [comment]
Thanks @orta seems I was not in the correct folder in the docker image. Now I'm getting this one 
/usr/local/bundle/gems/danger-5.4.0/lib/danger/request_sources/bitbucket_server_api.rb:51:in `encode': "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)
	from /usr/local/bundle/gems/danger-5.4.0/lib/danger/request_sources/bitbucket_server_api.rb:51:in `to_json'
	from /usr/local/bundle/gems/danger-5.4.0/lib/danger/request_sources/bitbucket_server_api.rb:51:in `post_comment'
	from /usr/local/bundle/gems/danger-5.4.0/lib/danger/request_sources/bitbucket_server.rb:80:in `update_pull_request!'
	from /usr/local/bundle/gems/danger-5.4.0/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
	from /usr/local/bundle/gems/danger-5.4.0/lib/danger/danger_core/dangerfile.rb:277:in `run'
	from /usr/local/bundle/gems/danger-5.4.0/lib/danger/danger_core/executor.rb:27:in `run'
	from /usr/local/bundle/gems/danger-5.4.0/lib/danger/commands/runner.rb:66:in `run'
	from /usr/local/bundle/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /usr/local/bundle/gems/danger-5.4.0/bin/danger:5:in `<top (required)>'
	from /usr/local/bundle/bin/danger:22:in `load'
	from /usr/local/bundle/bin/danger:22:in `<main>'

**Comment by orta** [comment]
Looks like the JSON coming in from BitBucket isn't encoded in a way that Ruby handles by default, it might need converting to UTF8 in the bitbucket request source

**Comment by josete89** [comment]
Just fixed seems in the linux version of the docker image doesn't support en.UTF_8 so I used C.UTF-8 and seems working. Thanks for your guidance 🎉
