### ISSUE TITLE
Consider deprecating `danger local`

### ISSUE THREAD

**Issue by ashfurrow** [danger/danger#898]
# Report

Since `danger local` is equivalent to `danger pr`, but has an ambiguous command name, we should consider deprecating it.

## What did you do?

I ran `bundle exec danger local`.

## What did you expect to happen?

I expected that the Dangerfile would be ran against my locally checked out code.

## What happened instead?

My local Dangerfile was ran against the latest pull request on the project.

## Your Environment

* Which CI are you running on? (n/a)
* Are you running the latest version of Danger? (5.4.1)
* What is your Dangerfile?

```ruby
# Run SwiftLint
swiftlint.lint_files
```

**Comment by thedavidharris** [comment]
Just ran into this today and had the same thought, was pretty confused.

Instead of deprecating it, would it be better for `danger local` to actually run against locally checked out code? Does that functionality exist in Danger already? I would find that to be a useful feature

**Comment by orta** [comment]
Yep - sure, I'd agree, happy to accept PRs doing either of these 👍

**Comment by mrackwitz** [comment]
Isn't this fixed by #932?

**Comment by orta** [comment]
Yeah, and the docs improved here: http://danger.systems/guides/troubleshooting.html
