### ISSUE TITLE
[Question] How do I execute danger locally on my machine

### ISSUE THREAD

**Issue by bhargavms** [danger/danger#927]
My team has danger set up on CI and everything, I don't want to wait for my PR to be run on CI to wait for results from danger, I want the danger report to be generated locally so that when I actually run the PR on CI (which takes a long time since I have to wait for other PRs to finish) it will actually pass it and my PR will get merged

**Comment by orta** [comment]
This doesn't exist ATM, I'd happily accept PRs adding it. A lot of the discussion around it is in https://github.com/danger/danger/issues/382

**Comment by bhargavms** [comment]
Nevermind you can close this issue, I managed to run it locally using `danger pr` command, after generating the coverage report.
