### ISSUE TITLE
Danger in Bitrise: Invalid Repository. Use user/repo format.

### ISSUE THREAD

**Issue by tomasharkema** [danger/danger#928]
# Report

## What did you do?

I've configured Bitrise to invoke Danger via this tutorial: https://blog.bitrise.io/danger-danger-uh-that-is-using-danger-with-bitrise

## What did you expect to happen?

I expect Danger parsing my `GIT_REPOSITORY_URL` (`git@github.com:someorg/some.repo.git`) correctly in bitrise.

## What happened instead?

I get an exception from OctoKit. 
```
Octokit::InvalidRepository: Invalid Repository. Use user/repo format.
  /Users/tomasharkema/.gem/gems/octokit-4.7.0/lib/octokit/repository.rb:90:in `raise_invalid_repository!'
  /Users/tomasharkema/.gem/gems/octokit-4.7.0/lib/octokit/repository.rb:34:in `initialize'
  /Users/tomasharkema/.gem/gems/octokit-4.7.0/lib/octokit/repository.rb:58:in `new'
  /Users/tomasharkema/.gem/gems/octokit-4.7.0/lib/octokit/repository.rb:58:in `path'
  /Users/tomasharkema/.gem/gems/octokit-4.7.0/lib/octokit/client/pull_requests.rb:32:in `pull_request'
  /Users/tomasharkema/.gem/gems/danger-5.5.5/lib/danger/request_sources/github/github.rb:117:in `fetch_details'
  /Users/tomasharkema/.gem/gems/danger-5.5.5/lib/danger/danger_core/environment_manager.rb:51:in `fill_environment_vars'
  /Users/tomasharkema/.gem/gems/danger-5.5.5/lib/danger/danger_core/dangerfile.rb:266:in `run'
  /Users/tomasharkema/.gem/gems/danger-5.5.5/lib/danger/danger_core/executor.rb:27:in `run'
  /Users/tomasharkema/.gem/gems/danger-5.5.5/lib/danger/commands/runner.rb:66:in `run'
  /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/tomasharkema/.gem/gems/danger-5.5.5/bin/danger:5:in `<top (required)>'
  /Users/tomasharkema/.gem/bin/danger:22:in `load'
  /Users/tomasharkema/.gem/bin/danger:22:in `<top (required)>'
```

I've debugged this and I see that the Regex in `ci_source/bitrise.rb` does not work for me. when I `puts self.repo_url, repo_matches, self.repo_slug, repo_matches.nil?`, I get 

```
git@github.com:someorg/some.repo.git


true
```

So, no matches for `repo_matches`.

However, ehen I change the regex to `"([\/:])([^\/]+\/[^\/.]+)(?:.git)?"` (instead of `%r{([\/:])([^\/]+\/[^\/.]+)(?:.git)?$})`) it works. I also see it working here: https://regex101.com/r/D5AqTM/2

Again the puts:
```
git@github.com:someorg/some.repo.git
:someorg/some
someorg/some
false
```

(Also, notice how the part after the period gets cutoff.)

Since I'm no ruby dev, I can't see the impact. So instead of a PR, I've filed an issue. Hopefully we could resolve this issue together!

## Your Environment

* Which CI are you running on?
Bitrise
* Are you running the latest version of Danger?
danger 5.5.5
* What is your Dangerfile?

  ```ruby
  # Make it more obvious that a PR is a work in progress and shouldn't be merged yet
  warn("PR is classed as Work in Progress") if github.pr_title.include? "[WIP]"
  # Warn when there is a big PR
  warn("Big PR") if git.lines_of_code > 500
  upload_url = ENV['$S3_UPLOAD_STEP_URL']
  if upload_url
    # submit message giving the coverage report that was generated by coverage.py
    message('[build artifacts]('+upload_url+')')
  end
  ```

**Comment by orta** [comment]
Yeah, this looks like you're on the right path - you should probably try PR it. It's probably the double `.` on the repo name 👍

**Comment by provTheodoreNewell** [comment]
Would this be an appropriate regex to support one or more `.`s in the repo name:
```
([\/:])([^\/]+\/[^\/.]+.*?)(?:.git)?$
```

**Comment by orta** [comment]
I'm no regexpert, but that looks pretty reasonable to me, it'd be pretty easy to write a test against 👍

**Comment by provTheodoreNewell** [comment]
Cool, preparing tests and a PR for this.

**Comment by provTheodoreNewell** [comment]
Ah, looks similar to #922.

**Comment by orta** [comment]
Yes!
