### ISSUE TITLE
Bitbucket Server support for Bitrise

### ISSUE THREAD

**Issue by copini** [danger/danger#939]
# Report
Currently, it seems Bitrise support is limited to GitHub and GitLab. The error I'm getting is not clear, but I deduce this from `supported_request_sources` in [ci_source/bitrise.rb](https://github.com/danger/danger/blob/master/lib/danger/ci_source/bitrise.rb#L32).
We use Bitrise in combination with a privately hosted Bitbucket Server instance, and would love to use Danger as well. In the past we used a similar setup with buddybuild which worked fine, but [they will stop supporting Android builds from March](https://www.buddybuild.com/blog/buddybuild-is-now-part-of-apple).

Is the solution as simple as adding `Danger::RequestSources::BitbucketServer` to `supported_request_sources` just like in [ci_source/buddybuild.rb](https://github.com/danger/danger/blob/master/lib/danger/ci_source/buddybuild.rb)?
I'd be happy to make a PR in that case, I'm just not sure how to test if it really works.

## What did you do?

Set up Danger in Bitrise, with the required environment variables for Bitbucket Server.

## What did you expect to happen?

Running the Dangerfile and Danger commenting on my Bitbucket Server pull request.

## What happened instead?

> Could not set up API to Code Review site for Danger
>
> For Danger to run on this project, you need to expose a set of following the ENV vars:
> - GitHub: DANGER_GITHUB_API_TOKEN
> - GitLab: DANGER_GITLAB_API_TOKEN
> - BitbucketServer: DANGER_BITBUCKETSERVER_USERNAME, DANGER_BITBUCKETSERVER_PASSWORD, DANGER_BITBUCKETSERVER_HOST
> - BitbucketCloud: DANGER_BITBUCKETCLOUD_USERNAME, DANGER_BITBUCKETCLOUD_PASSWORD
> - VSTS: DANGER_VSTS_API_TOKEN, DANGER_VSTS_HOST
>
>
> Found these keys in your ENV: ..., DANGER_BITBUCKETSERVER_PASSWORD, ..., DANGER_BITBUCKETSERVER_HOST, ..., DANGER_BITBUCKETSERVER_USERNAME, ...
>
> Failing the build, Danger cannot run without API access.
> You can see more information at http://danger.systems/guides/getting_started.html

## Your Environment

* Which CI are you running on? Bitrise
* Are you running the latest version of Danger? Yes (5.5.5)
* What is your Dangerfile? irrelevant for this issue

**Comment by orta** [comment]
I'd make a fork adding those changes you mentioned, then use a gemfile to test it out locally - other than running it, I'm not sure how to confirm if it will all work. Could just be that easy.

**Comment by copini** [comment]
Thanks! I'm willing to try, but I read in #727 that running locally doesn't allow you to test against Bitbucket Server. But now that I think about it, I might be able to run a fork in Bitrise to test it... I'll check tomorrow ;-)

**Comment by orta** [comment]
Yep, I mean running just `danger` on the CI, `danger pr` won't work - no

**Comment by copini** [comment]
Works for us, see PR #940.
