### ISSUE TITLE
How to avoid redundant `git fetch` In the shallow cloned CI environment

### ISSUE THREAD

**Issue by serima** [danger/danger#945]
# Report

## What did you do?

Run `bundle exec danger` on CircleCI.

## What did you expect to happen?

I expected that processing terminates without any problem without additional git fetch being executed.

## What happened instead?

It took 42 seconds to finish running `bundle exec danger`.
The reason that it takes time is probably an additional `git fetch`.

![image](https://user-images.githubusercontent.com/1130921/35194098-d21cf948-fef0-11e7-8249-337782872e8d.png)

## Your Environment

* Which CI are you running on?
  * CircleCI
* Are you running the latest version of Danger?
  * Yes / Ruby 2.4
* What is your Dangerfile?
  ```ruby
  message("Hello, this worked")
  warn "PR is classed as Work in Progress" if github.pr_title.include? "[WIP]" 
  ```

My repo is huge. so I don't use default git checkout on CircleCI, use instead of below way.

```
checkout: &checkout
  run:
    name: Checkout repository
    command: |
      echo "machine github.com login $GITHUB_TOKEN" > ~/.netrc
      repository_https_url=$(echo $CIRCLE_REPOSITORY_URL | sed -e "s|git@github.com:|https://github.com/|")
      git clone --depth=1 --branch $CIRCLE_BRANCH --single-branch $repository_https_url .
      git reset --hard $CIRCLE_SHA1 || (echo "The branch was updated after the build was executed. Please rebuild." 1>&2; false)
```

Does danger has option to avoid redundant fetch?
Or if it is easy to implement this feature, please give me a hint.

**Comment by orta** [comment]
You could switch to Danger JS which uses the GitHub API instead. Danger Ruby _needs_ all the local git info, and it's a significant amount of work to switch it to the GH API.

Otherwise there's not really anything you can do.

**Comment by serima** [comment]
@orta Thank you so much. I will try Danger JS instead.
