### ISSUE TITLE
Ability to make danger less spammy for big PRs

### ISSUE THREAD

**Issue by JoeSSS** [danger/danger#948]
Currently, Danger has two options to report back to GitHub, either update the comment or create a new one. 
That would be really helpful if she has also a possibility to replace a comment but put the comment in the end of the PR rather than updating it somewhere on the page 'x'.

Motivation: 
- `--new-comment` is very nice but can become a bit spammy for big projects and PRs, as you may want to post several danger outputs for every PR
- updating the comment can be easily lost, as it can be somewhere in the very beginning of the PR

**Comment by orta** [comment]
I think that makes sense as a feature, I'm not going to build it personally, but I have no problems accepting a (well tested) PR for a new CLI flag for putting the report in the main PR body. 👍

**Comment by BasThomas** [comment]
I think @JoeSSS's idea was not to put the output in the main PR body, but to always put it in the tail (last) comment and delete any previous Danger comment (that matches the ID).
