### ISSUE TITLE
Add List of CIs supported to README

### ISSUE THREAD

**Issue by bensussman** [danger/danger#95]
Hey @orta could you please list out the CIs that are supported in the README.md! thx!

Benno

**Comment by marcelofabri** [comment]
Meanwhile, you can find out the supported providers on the source code: https://github.com/danger/danger/tree/master/lib/danger/ci_source

* Buildkite
* Circle CI
* Jenkins
* Travis

**Comment by orta** [comment]
Gave it another look over - thanks
