### ISSUE TITLE
Is there a "success" command?

### ISSUE THREAD

**Issue by BasThomas** [danger/danger#951]
# Report

## What did you do?

Looked at the website and realized that there seems to be/have been a "success" command, which can be seen in the following image (the second message in the `error` table):

![danger-screenshot-074f084c](https://user-images.githubusercontent.com/4190298/35670567-323cec16-0739-11e8-9c37-191e1b0652ec.png)

## What did you expect to happen?

I expect that apart from `message`, `fail`, and `warn`, there would be something like `success` or `succeed` to actually tell a user that a (previously failed) check is succeeding; just like in the linked image.

## What happened instead?

There does not seem to be support for `success` or `succeed`.

## Your Environment
Danger 5.5.8

**Comment by orta** [comment]
That screenshot is when a failed test which is classed as sticky is then passed on a second CI run.

IMO a passed state is that it says nothing and doesn't have a comment, which is generally the unix way.  I'm not adverse to adding a success state, but I don't see much value over `message` or `markdown`.
