### ISSUE TITLE
Run command lines and/or unit tests

### ISSUE THREAD

**Issue by SpeakyDre** [danger/danger#953]
# Report

I would like to know if it is possible to run the unit tests of my project with Danger?
In the same idea, I would like to know if it's possible to run command lines with Danger? (like `git` commands, like `cd`, etc)

## What did you do?

Read the documentation.

Run `danger local`

But it doesn't work since I have the same issue as here: 
https://github.com/danger/danger/issues/477
https://github.com/danger/danger/issues/458
... and I don't want to have to install Danger all the way up to the CI to figure out if I can shell commands or run unit tests thanks to Danger. (I know usually the tests are run as part as the CI process in the PR but we are facing some limitations with our CI right now to run tests for a "pre-merge" of the two involved branches)

## Your Environment

* Environment:
Jenkins
Gitlab
iOS Swift project
* Are you running the latest version of Danger?
Yes
* What is your Dangerfile?
The default one for now.

Thank you.

**Comment by orta** [comment]
Running commands are covered in http://danger.systems/guides/a_quick_ruby_overview.html

Or you can send a PR to get `danger local` or `danger pr` working with things other than GitHub 👍

**Comment by SpeakyDre** [comment]
Oh ok I missed this page! Thanks :)
