### ISSUE TITLE
[init] Doesn’t work

### ISSUE THREAD

**Issue by alloy** [danger/danger#96]
It’s [expecting](https://github.com/danger/danger/blob/286fa5cf6134ffd9b2e9078f9c8efd7599381505/lib/danger/commands/runner.rb#L18-L20) a Dangerfile to exist.

**Comment by KrauseFx** [comment]
Thanks, working on a fix :rocket:

**Comment by KrauseFx** [comment]
Waiting for @orta's review https://github.com/danger/danger/pull/97 #ortareviewtimes

**Comment by KrauseFx** [comment]
@orta #ortareviewtimes was 10 hours, faster than 

**Comment by alloy** [comment]
You must have a good connection to his PR dept.
