### ISSUE TITLE
Circle CI PR detection is sad again

### ISSUE THREAD

**Issue by tomburns** [danger/danger#990]
# Report

## What did you do?

ran CI, no changes to our danger setup

## What did you expect to happen?

danger should run successfully as it has previously

## What happened instead?

```bundler: failed to load command: fastlane (/Users/distiller/project/vendor/bundle/ruby/2.3.0/bin/fastlane)
FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command 'bundle exec danger' was 1 instead of 0.
bundler: failed to load command: danger (/Users/distiller/project/vendor/bundle/ruby/2.3.0/bin/danger)
NoMethodError: undefined method `first' for nil:NilClass
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/danger-5.6.1/lib/danger/ci_source/circle_api.rb:33:in `fetch_pull_request_url'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/danger-5.6.1/lib/danger/ci_source/circle_api.rb:20:in `pull_request_url'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/danger-5.6.1/lib/danger/ci_source/circle_api.rb:8:in `pull_request?'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/danger-5.6.1/lib/danger/ci_source/circle.rb:59:in `validates_as_pr?'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/danger-5.6.1/lib/danger/danger_core/environment_manager.rb:15:in `pr?'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/danger-5.6.1/lib/danger/danger_core/executor.rb:62:in `validate_pr!'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/danger-5.6.1/lib/danger/danger_core/executor.rb:46:in `validate!'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/danger-5.6.1/lib/danger/danger_core/executor.rb:21:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/danger-5.6.1/lib/danger/commands/runner.rb:68:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/gems/danger-5.6.1/bin/danger:5:in `<top (required)>'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/bin/danger:22:in `load'
  /Users/distiller/project/vendor/bundle/ruby/2.3.0/bin/danger:22:in `<top (required)>'
```

## Your Environment

Circle CI, latest release of danger

**Comment by orta** [comment]
There were changes in https://github.com/danger/danger/pull/987

Perhaps those don't work with your setup?

**Comment by tomburns** [comment]
based on that trace, it looks like that element isn't present in the JSON at all, right? This setup was also working fine for quite a while until yesterday, though I wouldn't rule out an unnoticed change on our end if you have any ideas where to look

**Comment by orta** [comment]
At a guess, circle 1 vs circle 2?

**Comment by tomburns** [comment]
We are (and have been on 2.0) and I believe this API is actually shared between them -- I'll keep digging on my end 🕵️

**Comment by tomburns** [comment]
Probably worth pointing out that this is happening on both PR and non-PR builds for us right now too --- previously both of these were okay 😖

**Comment by tomburns** [comment]
Took out the circle API token from our env vars and added a manual env var check to our fastfile for now before running danger -- back to green, but I'll this open; let me know if there's anything I can to do help nail this down!

**Comment by orta** [comment]
I'm unsure TBH, I've not had any reports on the danger-js side of issues with circle and it didn't have the changes in #987

**Comment by allewun** [comment]
@tomburns would you be able to share a snippet of the JSON that danger is attempting to parse?

If your repo is public (e.g.):

```
$ curl https://circleci.com/api/v1/project/artsy/eigen/5234
```

If it's private, you have to add an API key to the request.

**Comment by tomburns** [comment]
Closing this for now, as I've got a workaround in place -- I'll be giving this another shot later in the week and will reopen if needed.

**Comment by dlackty** [comment]
Running into same issue and after debugging for a while, it turned out that my Circle CI API token was invalid. Not sure why this happened and how Danger worked before #987.

To test validity for your token, try:
```bash
curl https://circleci.com/api/v1.1/me?circle-token=YOUR-TOKEN
```

**Comment by orta** [comment]
I'd mention that to circle CI ^

**Comment by crsantos** [comment]
Beware that you need `:` before the token:

`curl https://circleci.com/api/v1.1/me?circle-token=:YOUR-TOKEN`

**Comment by huyvohcmc** [comment]
I'm having this issue too with the latest danger. Circle started to fails on development branch and not the others. My project shares the API token with other projects so there's no way it's invalid...
