### ISSUE TITLE
Travis: Danger check is not present in GitHub checks list 

### ISSUE THREAD

**Issue by brbrr** [danger/danger#996]
# Report

Running `yarn danger ci` in Travis did not update checks list in GitHub PR.
PR example: https://github.com/Automattic/jetpack/pull/9763
<img width="783" alt="test trigger danger checks by brbrr pull request 9763 automattic jetpack 2018-06-14 16-01-04" src="https://user-images.githubusercontent.com/5654161/41413621-4fb1bf62-6fec-11e8-9268-55c24e7649d8.png" width=50%>

## What did you do?
Run Travis build: https://travis-ci.org/Automattic/jetpack/builds/392227674
Run `WP_TRAVISCI="yarn danger ci"`

## What did you expect to happen?

Danger results will be present in GitHub checks list 

## What happened instead?

Danger results is missing in GitHub checks list 

## Your Environment

* Which CI are you running on? Travis
* Are you running the latest version of Danger? Yes
* What is your Dangerfile?

Danger file: https://github.com/Automattic/jetpack/blob/master/dangerfile.js

```js
/**
 * External dependencies
 */
import { danger, warn } from 'danger';

// No PR is too small to include a description of why you made a change
if ( danger.github.pr.body.length < 10 ) {
	warn( 'Please include a description of your PR changes.' );
}

// Use labels please!
if ( danger.github.issue.labels.length === 0 ) {
	warn( 'This PR is missing at least one label.' );
}
```

**Comment by orta** [comment]
In open source projects you've probably not given access to the bot to write to your repo, and thus make those API calls - http://danger.systems/guides/faq.html#why-am-i-seeing-quot-set-status-failed-quot-on-my-github-oss-project

It looks like you're using danger-js (this is the wrong repo BTW) but you can try using the [GitHub apps / checks](https://github.com/danger/danger-js/blob/master/CHANGELOG.md#370)  support for it (it's a bit undocumented ATM though)

**Comment by brbrr** [comment]
> this is the wrong repo BTW

Ouch, sorry. I thought this is a 'main' repo, and `rb` and `js` are just implementations :) Should I move this issue into relevant repo? 

> In open source projects you've probably not given access to the bot to write to your repo

Here is the list of scopes I've added into access token: `repo:status, repo_deployment, public_repo`
To make it clear - my user is newly created, and is not a member of org.

**Comment by orta** [comment]
> Ouch, sorry. I thought this is a 'main' repo, and rb and js are just implementations :) Should I move this issue into relevant repo?

Nah, no need, you're dealing with me either way :P

Yeah, I think the `repo:status` is read only, because we've never had it been able to set the commit status (those things at the bottom) on our OSS projects at Artsy, only on private repos.

**Comment by orta** [comment]
Or maybe not? https://github.com/danger/danger-js/issues/614

**Comment by brbrr** [comment]
Our folks have those things at the bottom here: https://github.com/wordpress-mobile/WordPress-iOS/pull/9577 (they using `-rb` and BuddyBuild CI)

**Comment by orta** [comment]
Yeah, OK, cool - this makes sense, let's turn https://github.com/danger/danger-js/issues/614 into the canonical issue for this, agree something's wrong 👍
